### ISSUE TITLE
Radio button 1st item could not get selected after switch to other item

### ISSUE THREAD

**Issue by kkpoon** [google/material-design-lite#4148] opened 2016-02-22 09:33 UTC
Version: 1.1.1

Browser: Mac Safari 9.0.3, Mac Chrome 48.0

```
[X] First    [ ] Second
```
In radio button, after click to select `Second`, then select back `First`, `First` not get selected. Neither my own code or getmdl.io demo work.

http://getmdl.io/components/index.html#toggles-section

![screen shot 2016-02-22 at 17 28 24](https://cloud.githubusercontent.com/assets/191992/13214318/d9c079ce-d989-11e5-87c3-41803a9b4e1d.png)
![screen shot 2016-02-22 at 17 28 32](https://cloud.githubusercontent.com/assets/191992/13214324/defe1f22-d989-11e5-9325-f9e3eda80a40.png)
![screen shot 2016-02-22 at 17 28 39](https://cloud.githubusercontent.com/assets/191992/13214331/e3f79170-d989-11e5-8d1b-9411faadf47a.png)

**Comment by BurningLights** [comment] 2016-02-22 20:24
This also occurs on both Microsoft Edge 13 and Google Chrome 48 on Windows 10.

**Comment by Garbee** [comment] 2016-02-22 22:37
Marking as a critical issue since this is a regression affecting form controls.

cc @surma and @sgomes either of you want to take a peek at debugging this? I can't remember who wrote this component.

**Comment by surma** [comment] 2016-02-22 23:00
I probably won’t be able to take a stab at this for at least a week or two. Sorry :confused:

**Comment by Garbee** [comment] 2016-02-22 23:30
Alright, I'll take a look first thing in the morning.

**Comment by kkpoon** [comment] 2016-02-22 23:34
This could be happened when there has one of the radio initially marked `checked`

Thank you.

**Comment by mfonville** [comment] 2016-02-23 12:47
Also check the checkboxes at the top of the same page. The first checkbox can't even be unchecked, which I also believe is erroneous.

**Comment by Garbee** [comment] 2016-02-23 13:29
@jwashin has spotted the problem in issue #4149. There isn't a regression in the code but instead documentation samples conflicting.

The list samples added controls as well, which were copy & pasted from the main controls. This is fine when testing individually as we were, but upon generating the documentation page the ID and names conflict which causes the problems.

All we need to do is update the list examples and this should be good. I'll work on that patch in just a few minutes.

**Comment by sgomes** [comment] 2016-03-03 16:28
This should now be fixed in `mdl-1.1` after the merge of #4161.

**Closed by sgomes** 2016-03-03 16:28 UTC
Labels: P0, Radio
