### ISSUE TITLE
There does not seem to be a built in way of making the mdl-layout__drawer pull out.

### ISSUE THREAD

**Issue by noah2828** [google/material-design-lite#1446] opened 2015-08-20 11:39 UTC
I have been looking and I can't find a good way of making the mdl-layout__drawer pull out on mobile. This is something which is really necessary for easy access to the side bar on mobile and can be done in other frameworks easily. ex in materialize `$(".button-collapse").sideNav();`. Am I missing something or is this not supported with MDL?

**Comment by Garbee** [comment] 2015-08-20 11:57
Can you please specify what you mean by "pull out"?

**Comment by noah2828** [comment] 2015-08-20 12:14
@Garbee I mean the type of menu that is in the inbox and until very recently was in YouTube. The type that you swipe right to pull out and left to push in so you don't have to press the hamburger button to move the side menu in and out of view.

**Comment by Garbee** [comment] 2015-08-20 12:23
So, this is a duplicate of #1023 it seems. There currently is no public API for drawer toggling within the layout.

**Closed by Garbee** 2015-08-20 12:23 UTC
