### ISSUE TITLE
Main content displaying on top of transparent header with background

### ISSUE THREAD

**Issue by f3yisayo** [google/material-design-lite#958] opened 2015-07-11 06:34 UTC
I'm not sure if its me not doing things correctly or how its supposed to look like, but I tried to use the transparent header with a background image, everything looks fine until you add content in 
`<main></main>` . The content is also drawn on top of the background, doesn't look like it was intended.

Have a look:

![hh](https://cloud.githubusercontent.com/assets/9140532/8632685/180801f0-279e-11e5-9b92-00a8012865c5.png)

Also, the drawer on mobile/responsive mode doesn't take its full height, increasing the `height` of the background in css fixed it though but that seems to defeat its purpose of the background being a header.

Here:

![cc](https://cloud.githubusercontent.com/assets/9140532/8632709/1c85088a-279f-11e5-9a69-7f278db9f344.png)

Codepen: http://codepen.io/feyisayo/pen/mJLzKx

**Comment by kybarg** [comment] 2015-07-11 09:23
Hard to say smth looking only to screens)

**Comment by surma** [comment] 2015-07-11 12:20
@f3yisayo Would you mind providing a codepen that reproduces that issue for you?

**Comment by f3yisayo** [comment] 2015-07-11 13:17
@surma  Oh here: http://codepen.io/f3yisayo/pen/mJLzKx

**Comment by Garbee** [comment] 2015-07-11 14:08
This is because you had the class for applying the background image on the wrong element. You need to move it to the `header` element, not the full container.

The fact that `<main>` was being used is entirely irrelevant.

Working codepen: http://codepen.io/anon/pen/bdMmzZ

It also seems that fixes the drawer on mobile.

Closing this issue since it isn't a core problem.

**Closed by Garbee** 2015-07-11 14:08 UTC
Labels: Layout

**Comment by f3yisayo** [comment] 2015-07-11 14:44
@Garbee I was actually following the guidelines on how to use transparent background headers so that might have to be updated with the correct markup.


![screenshot-www getmdl io 2015-07-11 15-31-56](https://cloud.githubusercontent.com/assets/9140532/8634121/90dc31b0-27e3-11e5-985e-c4055a2b6a1c.png)

**Comment by Garbee** [comment] 2015-07-11 15:17
Comment right at the top of that, "Uses a transparent header that draws on top of the layout's background". So the layout itself has a full background and the header is transparent so you can see through it.
