### ISSUE TITLE
Search icon of Dashboard template not aligned vertically in 1.2.0

### ISSUE THREAD

**Issue by trepidacious** [google/material-design-lite#4699] opened 2016-08-26 10:59 UTC
Search icon in header of [dashboard template](https://getmdl.io/templates/dashboard/index.html#) is not aligned vertically.

![screen shot 2016-08-26 at 11 53 37](https://cloud.githubusercontent.com/assets/172154/18003201/36e614f6-6b84-11e6-9274-2a13862e4a81.png)

When the icon is clicked to expand the text field, the text field itself is aligned correctly. The icon moves horizontally in the expected way, but is still much too low vertically.

MDL version 1.2.0, Chrome 52.0.2743.116 (64-bit), OS X 10.11.6

**Comment by Garbee** [comment] 2016-08-26 11:13
Duplicate of #4690

**Closed by Garbee** 2016-08-26 11:13 UTC
