### ISSUE TITLE
Responsive break points issues

### ISSUE THREAD

**Issue by nobitakun** [google/material-design-lite#1197] opened 2015-07-24 07:20 UTC
Hi. I try to resize browser to smaller and i aware that some break points in responsive not work as expected.

Eg: width = 800px;

**Comment by SnaKKo** [comment] 2015-07-24 09:18
I don't know if it's the same bug but i try anyway: if you check the "dashboard template" and you try to resize the browser you will see the bug.

![schermata del 2015-07-24 11 15 36](https://cloud.githubusercontent.com/assets/4040872/8871418/598ae38e-31f5-11e5-9fe6-889b03349a30.png)

**Comment by mspl13** [comment] 2015-07-24 09:26
Duplicate of #1185.

**Comment by nobitakun** [comment] 2015-07-24 09:26
yep! It is.

**Closed** 2015-07-24 10:58 UTC

**Comment by nobitakun** [comment] 2015-07-24 11:24
Hi @surma  does it fixed?

**Comment by mspl13** [comment] 2015-07-24 13:26
Nope, it is not fixed but this is a duplicate and duplicates usually get closed. Also the an explanation from  @surma to the issue in the original [issue](https://github.com/google/material-design-lite/issues/1185#issuecomment-124117470).
