### ISSUE TITLE
Add a class to allow links to visually be disabled

### ISSUE THREAD

**Issue by Ninir** [google/material-design-lite#1268] opened 2015-07-31 10:29 UTC
Hello guys!

As you all know, buttons can be disabled using the dedicated attribute, `<a>` tags can not (while it work on Chrome and some more perhaps, it is not W3C valid, as far as I know). 
I think there are cases where you may want to render links as buttons, and benefit from the "disabled" design already made for button tags. 

What do you think of adding a "mdl-button-disabled" class?

Hope it doesn't add any drawback or is acting against the project vision! :smile: 

Thanks for your time and!

**Comment by sgomes** [comment] 2015-07-31 10:52
Thanks for the suggestion, @Ninir!

I don't see any problems with adding a class to a future minor version. To confirm, you're just looking for the visual effect, right?

**Comment by surma** [comment] 2015-07-31 10:54
We could even disable clickability with `pointer-events: none`. But I agree, suggestion makes sense.

**Comment by Ninir** [comment] 2015-07-31 10:55
@sgomes Exactly!

@surma Event better yes! :)

Do you want me to add something in the button.scss file, under a `mdl-button--disabled` class or do you have something better in mind?

**Comment by sgomes** [comment] 2015-07-31 11:02
A status class (`is-disabled`) is probably best in this case, actually; so you'd basically need to add `.mdl-button.is-disabled` instead. Want to give that a try, @Ninir?

**Comment by Garbee** [comment] 2015-07-31 11:54
duplicate of  #887

**Comment by sgomes** [comment] 2015-07-31 11:56
Not a duplicate, this is for `mdl-button`.

**Comment by Garbee** [comment] 2015-07-31 11:59
You can just use the disabled attribute and get the disabled button styling (although with technically invalid markup.)

**Comment by surma** [comment] 2015-07-31 12:46
> ... although with technically invalid markup
I don’t think that’s something we should promote. That’s why I think a class is called for.

**Comment by Garbee** [comment] 2015-07-31 13:40
If we are adding a class, it shouldn't be a "status class" like `is-disabled`. It should be a modifier `--disabled` as originally suggested. It would only need to be added to the current disabled state rules. Modifying the pointer-events seems a bit much. While this is stylistic, if developers are triggering a disabled state then they can make sure the href is removed as well in order to make sure the anchor doesn't function when disabled.

**Comment by sgomes** [comment] 2015-07-31 13:46
I don't feel strongly either way, but why do you think `mdl-button--disabled` would be better than an `is-disabled` status class, @Garbee? It seems inconsistent with our approach elsewhere, where we use `--foo` for options and `is-foo` for transient states.

**Comment by Garbee** [comment] 2015-07-31 13:48
Because in this case the developer is setting it in their code directly. Where with the other states they are applied using JS using the widget methods.

**Comment by sgomes** [comment] 2015-07-31 13:54
Fair enough, that sounds like a reasonable distinction :)

**Comment by addyosmani** [comment] 2015-08-04 13:03
Adding as a stretch for 1.0.3 but this may well make it to 1.1. @Garbee or @sgomes do either of you want to claim this one?

**Comment by surma** [comment] 2015-08-04 13:25
I’ll just snatch it ;)

**Closed** 2015-08-06 14:08 UTC
Labels: feature-request, P1

**Comment by Ninir** [comment] 2015-08-10 13:57
Forgot to thank you guys! So... thanks :-)
