### ISSUE TITLE
data tables and white-space:nowrap;

### ISSUE THREAD

**Issue by apollo13** [google/material-design-lite#1088] opened 2015-07-17 08:56 UTC
Data tables are currently using `white-space: nowrap;` which is causing a table to overflow it's grid cell if the inserted data is too long. Is this on purpose, and if yes, how should I work around it, or is that a bug that needs fixing.

**Comment by surma** [comment] 2015-07-31 16:41
It’s not a bug per se, if you remove that attribute the table becomes highly distorted because browsers tend to make tables as narrow as possible. For now we would suggest to just manually remove the `white-space` attribute from the cells with large amounts of contents.

However, if you have a solution in mind that solves this problem generically, I’d be happy to look over a PR :D

Closing this for now.

**Closed by surma** 2015-07-31 16:41 UTC
Labels: confirmed, Data Table

**Comment by apollo13** [comment] 2015-07-31 16:44
Well, what about some selector which detects if the table is a grid cell? That one just would need to be more specific then the original and it could override it… Though that somehow couples those two components strongly together.

**Comment by innerpeace0** [comment] 2015-07-31 16:58
> browsers tend to make tables as narrow as possible.

    table {
      width: 100% }

**Comment by surma** [comment] 2015-07-31 17:02
@apollo13 I did not realize you were talking about the grid as well. Just to avoid a misunderstanding, would you mind whipping up a quick codepen?

**Comment by Garbee** [comment] 2015-07-31 17:05
A 100% width on data tables causes alignment issues if they are selectable FTR.

**Comment by apollo13** [comment] 2015-07-31 17:08
@surma http://codepen.io/anon/pen/xGmOdN
