### ISSUE TITLE
Active chackboxes does not show the blue tick mark.

### ISSUE THREAD

**Issue by reinhart1010** [google/material-design-lite#4663] opened 2016-08-12 14:13 UTC
It seems that in Firefox 49 and up, the checkboxes, which is contained in https://getmdl.io/components/index.html#toggles-section/checkbox , the active checkbox only show the blue outline instead of a check/tick mark.

The screenshot below is reproduced in Safari (top) and Firefox (bottom).
![68747470733a2f2f776562636f6d7061742e636f6d2f75706c6f6164732f323031362f382f38663466323764372d653135622d343435662d386639642d3661366339393530653863312e6a7067](https://cloud.githubusercontent.com/assets/17312341/17625254/39400868-60d2-11e6-8282-bf382087de36.jpg)

More details on https://github.com/webcompat/web-bugs/issues/2992

**Comment by Garbee** [comment] 2016-08-12 14:23
Duplicate of #4649

**Closed by Garbee** 2016-08-12 14:23 UTC
