### ISSUE TITLE
Ensure `overflow:hidden` on code blocks to avoid horizontal scrollbars

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#485] opened 2015-06-26 09:57 UTC

**Comment by Garbee** [comment] 2015-12-25 01:49
/me coughs.

`overflow-x: hidden` is more appropriate if you just want horizontal to not exist. Seems fully reasonable to me. Just toss it in if the problem is still happening and move on. Don't even PR the change, just do it and close this issue up.

If the issue still isn't happening, go ahead and close this up. Looks like low-hanging fruit against the microsite.

**Comment by sgomes** [comment] 2016-07-01 16:15
Closing, since the documentation will be entirely rewritten.

**Closed by sgomes** 2016-07-01 16:15 UTC
Labels: Microsite
