### ISSUE TITLE
Any chances to have select dropdown component?

### ISSUE THREAD

**Issue by wzup** [google/material-design-lite#4273] opened 2016-04-16 01:48 UTC
Do you have `<select>`s? There is a `menu` you provide, but it is not actually a full-featured select.

**Comment by mspl13** [comment] 2016-04-16 07:34
According to a post from @sgomes there isn't such a dropdown component yet (your can find the post [here](https://github.com/google/material-design-lite/issues/108#issuecomment-114816837)). Also if you are not able to find something on the [components page](https://www.getmdl.io/components/index.html) there is a really good chance that it isn't available. Please have a look over there before creating issues like this. Thanks!

**Comment by Garbee** [comment] 2016-04-18 15:03
Closing as duplicate of #854.

**Closed by Garbee** 2016-04-18 15:03 UTC
