### ISSUE TITLE
[website] admin template marked as virus 

### ISSUE THREAD

**Issue by mantissa7** [google/material-design-lite#1851] opened 2015-11-05 21:30 UTC
This is an issue with the website.

Just tried to download the admin theme (preview http://www.getmdl.io/templates/dashboard/index.html) but get repeated errors of a virus detected.

details:
- admin template marked as virus 
- windows 10 
- Chrome  46.0.2490.80 m
- default antivirus (windows defender)

![virus_message](https://cloud.githubusercontent.com/assets/13873136/10982261/2d43c35c-8404-11e5-91bd-43d15ca232be.jpg)

**Comment by surma** [comment] 2015-11-06 08:51
Duplicate of #1754. Nothing we can do about this, sadly :(

**Closed by surma** 2015-11-06 08:51 UTC
