### ISSUE TITLE
Bug: Table rows borders do not renders (Chrome)

### ISSUE THREAD

**Issue by blobor** [google/material-design-lite#4325] opened 2016-05-06 14:44 UTC
MDL version: 1.1.3
Browser: Chrome
Browser version: 50.0.2661.94
Operating system: Windows 
Operating system version: 6.3.9600
URL: http://codepen.io/blobor/pen/WwLVOm

Table "mdl-data-table", it's not shows borders of rows until you hover over on them.

Possible solution:
Basically we need to change border rendering from table cell to table row.

Instead:
```css
.mdl-data-table td {
    border-top: 1px solid rgba(0, 0, 0, 0.12);
    border-bottom: 1px solid rgba(0, 0, 0, 0.12);
}
```

Use this:
```css
.mdl-data-table tbody tr {
    border-top: 1px solid rgba(0, 0, 0, 0.12);
    border-bottom: 1px solid rgba(0, 0, 0, 0.12);
}
``` 

Screenshot:
![image](https://cloud.githubusercontent.com/assets/4813007/15076074/726134a6-13b0-11e6-948a-3cb7f5dcf3cd.png)

**Comment by Garbee** [comment] 2016-05-06 17:42
Working here just fine (on Dev channel.)

Have you tried a clean profile with no extensions to see if the problem persists?

**Comment by blobor** [comment] 2016-05-06 19:14
@Garbee, have you tried codepen url?

I have tried on Edge, Firefox and Brave and it works fine.
Issue is reproducible on Chrome stable and Chrome Canary (in private mode also).

**Comment by Garbee** [comment] 2016-05-07 00:44
Yea, the codepen is working 100% perfectly here. Seems to be a bug in something of your Chrome configs.

Try grabbing Chromium itself from [appspot](https://download-chromium.appspot.com/) and run under that since it will use a completely isolated profile.

**Comment by mfonville** [comment] 2016-05-07 14:29
Duplicate of #4270

**Comment by tleunen** [comment] 2016-05-07 14:49
I have the exact same issue :(
https://tleunen.github.io/react-mdl/components/datatable/

**Comment by dazza999** [comment] 2016-05-07 16:59
Seems like it's this issue https://bugs.chromium.org/p/chromium/issues/detail?id=606351

I see it in v50 but not current canary (v52)

**Comment by blobor** [comment] 2016-05-08 10:49
@mfonville, sorry for that. I guess issues could be closed.

**Closed** 2016-05-11 13:41 UTC

**Comment by maiakaat** [comment] 2016-05-25 12:44
You can usually force display by setting border-style in the css class
