### ISSUE TITLE
[1.0.3] Weird tooltip positioning

### ISSUE THREAD

**Issue by Zodiase** [google/material-design-lite#1416] opened 2015-08-18 02:28 UTC
See [this screenshot](http://cl.ly/image/400O1p213o1q). The highlighted button is being hovered.
I'm using the `material.css` from the latest build (1.0.3).

Also [here's a codepen for it](http://codepen.io/Zodiase/pen/aOrEma).

**Comment by Zodiase** [comment] 2015-08-18 02:32
BTW this issue wasn't present in 1.0.2.

**Comment by addyosmani** [comment] 2015-08-18 07:59
Btw, I.0.3 isn't quite 'out' :) It's in master but hasn't been tagged or pushed to npm just yet. We were going to do that shortly, but will look at this bug first. Thanks for the report!

@surma I've pushed latest to the release branch but will pause on the release until we've verified if this is a regression. Could you take a look at this one before we move ahead?

**Comment by tleunen** [comment] 2015-08-18 09:58
I also noticed the version bump in master. I know there's another discussion on that but it would be a lot better and less confusing if the process of building and releasing a version was different.

**Comment by surma** [comment] 2015-08-18 10:40
@tleunen I’d be interested to hear in what your suggestions are. Please move that to a new issue, though.

**Comment by surma** [comment] 2015-08-18 10:41
For documentation purposes, this issues got introduces with #1408. Labels use fixed positioning and `transform` resets the origin for fixed positioning. So tooltips inside tables got broken. I’m currently looking for a fix

**Comment by Garbee** [comment] 2015-08-18 11:45
@addyosmani Looks like this issue should block the release. It is a regression that causes BC breakage.

If @surma can't find a solution shortly, perhaps we should rollback the iOS table fix and push that to 1.1.

**Comment by surma** [comment] 2015-08-18 11:48
@Garbee I got something that almost works :D I’ll keep you posted. Rollback is definitely appropriate if this doesn’t work out

**Comment by surma** [comment] 2015-08-18 13:16
This has been fixed by reverting #1408 in #1420.

**Closed by surma** 2015-08-18 13:16 UTC
Labels: P0, Tooltip
