### ISSUE TITLE
Microsoft Surface Pro 2 and 16:9 devices in general

### ISSUE THREAD

**Issue by steamonimo** [google/material-design-lite#1453] opened 2015-08-22 17:31 UTC
For Surface 2 and 16:9 devices it seems that hiding divs with class mdl-cell--hide-tablet does not work as expected in portrait mode as you can see here:
https://drive.google.com/file/d/0B3WE_sGto9DjNzFlUHBjOHRyYW8/view?usp=sharing

I expected that in portrait the full width would be taken by the content - as is true for phones. The same too narrow display can be seen on the Surface with the template "stand-alone article":
http://www.getmdl.io/templates/article/index.html

In landscape mode it displays as expected - as you can see here:
https://drive.google.com/file/d/0B3WE_sGto9Djb3p3MU0zWkxqenM/view?usp=sharing

In addition: the page getmdl.io has problems to be displayed and used properly on the Surface Pro 2 but this can be related to compatibility issues of the W8.1 Internet Explorer in tablet mode.

Keep up the good work and thanks for listening!

**Comment by surma** [comment] 2015-08-22 18:25
Hey @steamonimo. Thanks for the screenshots, this is actually good to have to show to the MD team.

What you describe probably means that you the Surface 2 has a [width above 840px](https://github.com/google/material-design-lite/blob/master/src/_variables.scss#L505) and therefore falls into the desktop category (for now). We are still working with the MD team to make the [Adaptive UI spec](https://www.google.com/design/spec/layout/adaptive-ui.html) more reliable, so this is likely going to change (or dare I say “improve”) in the future.

Closing this for now as it is working as intended. But we are aware of the flaws.

**Closed by surma** 2015-08-22 18:25 UTC
