### ISSUE TITLE
[Component Request] Material Transitions

### ISSUE THREAD

**Issue by amniskin** [google/material-design-lite#4355] opened 2016-05-17 21:24 UTC
In the material design spec, it specifies how materials should transform into one another. It would be nice if there was a library that did exactly that. Ideally one would be able to transform a card/button/what-have-you to a full page/ another card/ etc, and then back again.

https://www.google.com/design/spec/motion/transforming-material.html#transforming-material-radial-transformation

For instance, if you're writing a web app, and you'd like one card to expand to a full screen field.

**Comment by jiaming10** [comment] 2016-05-19 02:59
From what I know, this is currently not in the scope of the project, so we will need to implement it our own.

**Comment by Garbee** [comment] 2016-05-19 10:05
Quasi-duplicate of #1897

No simple way to integrate this for a general use-case. This is where developers will need to implement part of the specification themselves if they need it.

Thanks for the suggestion, but it simply isn't something we can feasibly handle in a generic way.

**Closed by Garbee** 2016-05-19 10:05 UTC
