### ISSUE TITLE
Dashboard template bug: header resize "truncate" text

### ISSUE THREAD

**Issue by SnaKKo** [google/material-design-lite#1262] opened 2015-07-30 13:35 UTC
**Desktop**
![schermata del 2015-07-30 15 33 50](https://cloud.githubusercontent.com/assets/4040872/8984219/839f9464-36d0-11e5-9f6c-8cd6e5e7a5e5.png)

**Mobile**
![schermata del 2015-07-30 15 34 05](https://cloud.githubusercontent.com/assets/4040872/8984221/87984f3e-36d0-11e5-94ad-dcd4289cc450.png)

**Comment by mspl13** [comment] 2015-07-30 13:41
This is a duplicate of #1245 and should be fixed by #1249 AFAIK. I think the fix will be part of the 1.0.3 release.

**Comment by surma** [comment] 2015-07-30 13:54
@mspl13 Correct. Thanks for reporting, though, @SnaKKo :)

**Closed by surma** 2015-07-30 13:54 UTC
