### ISSUE TITLE
Drawer cover element not visible

### ISSUE THREAD

**Issue by tylermakin** [google/material-design-lite#1696] opened 2015-10-05 18:58 UTC
The element for covering the main body of MDL pages when opening the drawer is not visible in some browsers.

This issue is relating to the visibility of the mdl-layout__obfuscator class element in MDL pages such as the [Android.com sample template](http://www.getmdl.io/templates/android-dot-com/index.html)

Issue occurred while testing across three third-party kiosk browser apps on iPad running iOS 9:
* Sandbox Web Browser
* Kiosk Pro Lite
* Mobile Kiosk

Possible cause could be the CSS "visibility" attribute not being supported by browser.

Correct display:
![untitled](https://cloud.githubusercontent.com/assets/11431414/10290234/c610d9e6-6b57-11e5-88ff-e0ae6f6d3f45.png)

Erroneous display:
![img_0001](https://cloud.githubusercontent.com/assets/11431414/10290238/cabfb28c-6b57-11e5-8cd0-270632849c3f.PNG)

**Comment by surma** [comment] 2015-10-06 09:49
Tried to reproduce on iPhone 6+, where the obfuscator is working fine. 
![x1acoh4](https://cloud.githubusercontent.com/assets/234957/10305407/dd118e18-6c17-11e5-8bd6-c7a1c7d81c13.jpg)

Not sure what I can do here :confused:

**Comment by theorangutan** [comment] 2015-10-06 21:54
My project is also experiencing this issue on iOS 9.  I'd like to add that the drawer closing functionality does not work when this occurs, leaving the drawer in a locked open state.

**Comment by surma** [comment] 2015-10-06 21:59
@theorangutan @tylermakin I think we need your help with this! If possible, any of the following things would make things a lot easier and would be greatly appreciated, so we can reproduce the issue on our side:

* A list of browsers / apps (including versions) that exhibit the issue you are referring to
* A minimalistic codepen that contains the code that exhibits the issue
* Screenshots or videos of the issue

**Comment by tylermakin** [comment] 2015-10-06 22:14
@surma 

Per my original comment, the affected browsers include:
* Sandbox Web Browser
* Kiosk Pro Lite
* Mobile Kiosk

Safari in iOS 9 does not seem to present this issue and this issue was seen on an iPad Air (original).

The issue is present in the above-mentioned Android website template on [getmdl.io](http://www.getmdl.io/):
* [demo](http://www.getmdl.io/templates/android-dot-com/index.html)
* [template download via getmdl.io](https://storage.googleapis.com/code.getmdl.io/1.0.5/mdl-templates.zip)

**Comment by theorangutan** [comment] 2015-10-07 15:25
@surma 

Using the [demo](http://www.getmdl.io/templates/android-dot-com/index.html) site

iPad Air
iOS 9.0.2
Chrome 45.0.2454.89

![img_0030](https://cloud.githubusercontent.com/assets/476854/10342112/63438e28-6ccc-11e5-8e19-76f94aeb1708.PNG)

I originally found this in OS X (10.11) using the iPhone 5 simulator and Safari.

![untitled](https://cloud.githubusercontent.com/assets/476854/10342093/535eb960-6ccc-11e5-858f-ec85982bf7d8.jpg)

**Comment by surma** [comment] 2015-10-07 16:18
Hooray! It’s iOS 9!

My bad guys, I was on iOS 8.4 without realizing. Bug is confirmed for iOS 9 WebViews (*not* Safari).

@sgomes I come bearing bad news!

**Comment by sgomes** [comment] 2015-10-07 16:25
@surma So the obfuscator (which should be super straightforward) is not working, it only happens on iOS 9, and even there only in WebViews? My sanity meter is dropping rapidly... *sigh*

Do we have a good way of testing this?

**Comment by tylermakin** [comment] 2015-10-08 22:31
Perhaps it is related to the ~ sibling selector?

**Comment by sgomes** [comment] 2015-10-09 14:08
An update: this is indeed due to the sibling selector, which doesn't seem to be working correctly in some cases. I'm preparing a workaround for the bug.

**Comment by sgomes** [comment] 2015-10-09 15:07
This issue is now fixed in the `mdl-1.0` branch and will be part of 1.0.6.

**Closed by sgomes** 2015-10-09 15:07 UTC
Labels: bug, confirmed, Layout
