### ISSUE TITLE
npm install material-design-lite doesn't have default entry point

### ISSUE THREAD

**Issue by smithb1994** [google/material-design-lite#1214] opened 2015-07-26 08:48 UTC
Doing
```javascript
npm install material-design-lite
```
then in my code
```javascript
require('material-design-lite')
```
The require doesn't point to a js file, have to do it manually with
```javascript
require('material-design-lite/material.min.js')
```
Please consider updating the package.json to point to the correct javascript files when requiring it from npm.

**Comment by Swatinem** [comment] 2015-07-26 10:01
Dupe of #833 I would say. An external contributor is working on a patch, hopefully with results soon :-)

**Closed** 2015-07-26 11:12 UTC

**Comment by jjalonso** [comment] 2015-07-26 13:35
+1

**Comment by zuhairnaqvi** [comment] 2015-07-28 03:54
Can't wait!

**Comment by olegt-indicee** [comment] 2015-12-11 19:13
I think this issue should be re-opened. The workaround above `require('material-design-lite/material.min.js')` does not work when I use webpack's CommonsChunkPlugin to extract vendor libraries:

```
webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.dist.js')
```

I get the following error at compile time:

```
ERROR in multi vendor
Module not found: Error: Cannot resolve module 'material-design-lite' in /project-path/myproject
 @ multi vendor
```

And my `vendor.dist.js` has this error:

```
...
__webpack_require__(324);
(function webpackMissingModule() { throw new Error("Cannot find module \"material-design-lite\""); }());
...
```

Manually adding `"main": "material.js”` or `"main": "material.min.js”` fixes this issue. Obviously, manual code editing is not an option for when building in Jenkins. 

I've created a fork with a fix, please consider merging it in:
https://github.com/google/material-design-lite/pull/2000

**Comment by alhajee** [comment] 2017-07-10 03:27
i had the same issue too but i managed to fix it by adding `"material-design-lite": "^1.3.0"` to the `dependencies` in my `package.json` then i ran `npm install` once again
