### ISSUE TITLE
Adding 'mdl-cell--6-col' (or other sizes) to a 'mdl-data-table' with 'mdl-data-table--selectable' causes the header selectable to be misaligned

### ISSUE THREAD

**Issue by cthielen** [google/material-design-lite#1383] opened 2015-08-13 00:09 UTC
If you try to set the width of a table using a size class such as 'mdl-cell--6-col' in a data table using the 'mdl-data-table--selectable' option, it causes the th header's checkbox to be misaligned. The issue appears to be due to td-based selectable checkboxes being position: absolute with left: 24px while the th selectable checkboxes have no such positioning.

See: https://jsfiddle.net/2jrwh45u/6/ (you'll need to resize the result window to be larger to see the th checkbox drift)

**Comment by sgomes** [comment] 2015-08-13 11:13
Good catch, thanks @cthielen! We'll try to get this in for 1.0.3.

**Comment by sgomes** [comment] 2015-08-13 11:18
Actually, closing this one as it seems to be a duplicate of #923. Let's track this there.

**Closed by sgomes** 2015-08-13 11:18 UTC
Labels: bug, confirmed, Data Table
