### ISSUE TITLE
PostCSS instead of SASS in MDL v2

### ISSUE THREAD

**Issue by JosefJezek** [google/material-design-lite#4022] opened 2016-01-24 09:12 UTC
https://github.com/postcss/postcss
https://github.com/postcss/benchmark
https://www.smashingmagazine.com/2015/12/introduction-to-postcss/

Check out this projects
https://github.com/ampproject/amphtml
https://github.com/StartPolymer/polymer-starter-kit-plus

Nice plugins
https://github.com/postcss/postcss-custom-media
https://github.com/hail2u/node-css-mqpacker
https://github.com/postcss/postcss-import

**Comment by Garbee** [comment] 2016-01-24 11:21
Duplicate of #811

**Closed by Garbee** 2016-01-24 11:21 UTC
