### ISSUE TITLE
404 in blog template

### ISSUE THREAD

**Issue by JoseAlcerreca** [google/material-design-lite#1459] opened 2015-08-24 10:13 UTC
http://www.getmdl.io/templates/blog/index.html

shows 404: http://www.getmdl.io/templates/blog/images/touch/chrome-touch-icon-192x192.png

**Comment by surma** [comment] 2015-08-24 10:47
Duplicate of #1418 :)

**Comment by surma** [comment] 2015-08-24 10:47
Uhm, I meant #1449

**Closed by surma** 2015-08-24 10:47 UTC
