### ISSUE TITLE
Performance issues in the Components page (IE11)

### ISSUE THREAD

**Issue by steven-qi** [google/material-design-lite#847] opened 2015-07-08 03:23 UTC
Visit http://www.getmdl.io/components/index.html page on IE11, the main content panel is blank, and browser tab always shows the 'loading' indicator. Content only shows up after <strong>several</strong> minutes.

![blank](https://cloud.githubusercontent.com/assets/6123222/8562253/9c9d60e2-2562-11e5-92b6-8742deed62f1.PNG)

In network tab of dev tools, there are many pending HEAD requests to ```/assets/clippy.swf```.

![pending requests](https://cloud.githubusercontent.com/assets/6123222/8562188/c4e4fad4-2561-11e5-9bae-2941366d2576.PNG)

Although it works ok on Chrome, those '*.swf' really makes me feel that I am back to ten years ago...

**Comment by addyosmani** [comment] 2015-07-08 06:52
We've been heavily testing in IE10, 11 and Edge and weren't able to reproduce this earlier, but I'll take another look in case a regression was introduced. Are you on Windows 8.1 or 10?.

Flash: we hate having to use it, but copy/paste is unfortunately not possible cross-browser today without using it.

**Comment by steven-qi** [comment] 2015-07-08 06:59
Thanks @addyosmani I am on Windows 8.1. BTW, I am behind a proxy as the site is not accessible from mainland China...

**Comment by steven-qi** [comment] 2015-07-08 07:12
Here is the details of the pending request I mentioned, in case it is helpful.

![head request](https://cloud.githubusercontent.com/assets/6123222/8564957/94b05be8-2583-11e5-91ab-77bfe5aabdf0.PNG)

**Comment by addyosmani** [comment] 2015-07-08 09:23
I'm going to start profiling this now.

**Comment by addyosmani** [comment] 2015-07-08 10:13
Profiling the index of the Components page in IE11:

We're spending ~2s in DOM load atm:

![](http://i.imgur.com/KvyZV2d.png)

~1.69s of which comes from time spent initialising ripples:

![](http://i.imgur.com/dMP1ttY.png)

The upgrade flow here (automagical adding of ripples based on class) appears to be costing the most time here.

We spend the rest of this time initializing the Codepen buttons:

![](http://i.imgur.com/5tlImjf.png)

Most of which is a series of `document.createElement` followed by `appendChild`. As noted before we launched, I think most of the work for CodePen buttons should be done at build-time via the templating engine rather than doing this work in JS.

**Comment by addyosmani** [comment] 2015-07-08 10:17
Performance is slightly better on pages like Cards, where the bottleneck seems to be our use of `scrollTop`. Below it's causing ~73ms of Layout work.

![](http://i.imgur.com/LUXJaXu.png)

**Comment by addyosmani** [comment] 2015-07-08 10:19
Spinners are averaging out at about 50fps. There's a lot of constant style recalc and paint in there otherwise:

![](http://i.imgur.com/YY231Ip.png)

**Comment by addyosmani** [comment] 2015-07-08 10:22
Running into a similar issue with `scrollTop` costs when switching to our Menu page:

![](http://i.imgur.com/D2lSGEM.png)

**Comment by steven-qi** [comment] 2015-07-08 10:27
@addyosmani I think that the key issue here is that, those HEAD requests to clippy.swf are somehow blocked and never success on IE 11, and the page only shows up after request timeout.

**Comment by addyosmani** [comment] 2015-07-08 10:29
@steven-qi I've hi-jacked this issue to document the other perf issues with this page in IE too. Sorry about that :) We should be fixing the clippy.swf issues (if they're a bottleneck) as well as the others listed. I'm going to try digging specifically into clippy issues in just a sec.

**Comment by addyosmani** [comment] 2015-07-08 10:29
The three top items I think we need to fix here are:

* Cost of switching to a component sub-page. We should work around reading `scrollTop` to reduce relayout costs.
* Cost of using JS to inject the CodePen buttons vs doing this at build time through templating
* Did deeper into the slowness caused by the ripple implementation.

Moving onto clippy.swf specifically next.

**Comment by addyosmani** [comment] 2015-07-08 10:50
I've reproduced the issue you were initially seeing with clippy:

![](http://i.imgur.com/Cy5gJXh.png)

For some weird reason (or I'm being dumb), even after the first fetch of clippy.swf, each subsequent request appears to be taking a varied amount of time. I would have expected the first request to cache the asset and then us just deal with read-from-cache times after that.

Looking at Headers from your screenshots and my own, we're `pragma: no-cache` here. @marcacohen any thoughts on whether our GCS config needs some tweaking to enable caching for Flash assets? 

![](http://i.imgur.com/gsulmPs.png)

**Comment by marcacohen** [comment] 2015-07-08 11:33
@addyosmani pragma:no-cache looks like it's appearing in the request, not the response (i.e. client is requesting uncached copy). I wonder if that's because you're doing a page re-load. Can you retry in a new window?

**Comment by marcacohen** [comment] 2015-07-08 11:51
Ignore, I can try this myself. I'll run with it.

**Comment by nicolasgarnier** [comment] 2015-07-08 12:04
If creating elements on the page for each <pre> blocks is taking so long I'm surprised that the syntax highlighting is not also taking a while because it's creating a lot more elements (although we have less control over it so not mu ch we could do there to improve things)

**Comment by nicolasgarnier** [comment] 2015-07-08 12:04
If creating elements on the page for each `<pre>` blocks is taking so long I'm surprised that the syntax highlighting is not also taking a while because it's creating a lot more elements (although we have less control over it so not mu ch we could do there to improve things)

**Comment by nicolasgarnier** [comment] 2015-07-08 14:25
@marcacohen I tried doing this:

```bash
curl -X HEAD www.getmdl.io/assets/clippy.swf
```

And this request it hangs for a long time and then you eventually get a timeout.
It seems that GCS hangs on HEAD requests.

**Comment by surma** [comment] 2015-07-08 14:31
Can confirm, `HEAD` requests don’t seem to be handled. curl has been hanging for a few minutes now.

**Comment by nicolasgarnier** [comment] 2015-07-08 14:37
Yes this might also explain why the cache is not used: because the browser never received a valid response for the HEAD request so it re-tries every time.

@marcacohen is investigating, it seems we have to manually enable HEAD requests on the Cloud Storage bucket.

**Comment by nicolasgarnier** [comment] 2015-07-08 15:03
It's even stranger than this... The following works:

```
curl --head www.getmdl.io/assets/clippy.swf
```

the only difference between `curl --head` and `curl -X HEAD` is that one uses IPv6 and the other IPv4. IPv6 works.

I'm betting the 2 types of requests end up in differently configured Cloud Storage servers. Seems like this is a GCS bug, @marcacohen will try to enable `HEAD` requests manually though to see if this changes something. Otherwise => bug report to the GCS team...

**Comment by nicolasgarnier** [comment] 2015-07-08 16:36
FYI there seem to be no bugs associated with HEAD requests, we simply didn't read the curl docs:

>This option only changes the actual word used in the HTTP request, it does not alter the way curl behaves. So for example if you want to make a proper HEAD request, using  -X HEAD will not suffice. You need to use the -I, --head option.

This means that basically HEAD requests to clippy.swf work fine since `curl --head www.getmdl.io/assets/clippy.swf` works... Not sure what's up with @steven-qi's setup then. We definitely need to try to replicate with the same browser/OS combination...

**Comment by marcacohen** [comment] 2015-07-08 18:41
@steven-qi We're digging through logs. Can you tell me roughly when (date/time of day), you saw the hanging HEAD requests? That would help focus our examination. Thanks!

**Comment by steven-qi** [comment] 2015-07-09 02:27
@marcacohen I tried this many times yesterday and today. For me, this is 100% reproducible. I also notice that on Chrome, it is a GET instead of HEAD. And if I copy the url of clippy.swf to browser and navigate to it directly, the swf file will be loaded instantly with no delay.

**Comment by steven-qi** [comment] 2015-07-09 03:36
BTW, I actually tried the following, and it works fine...
```
 curl -x http://<--proxy-->:80 --head http://www.getmdl.io/assets/clippy.swf
```

**Comment by steven-qi** [comment] 2015-07-09 04:54
And ```-X HEAD``` shows following error after a long pending:

```
$ curl -x http://<proxy>:80 -X HEAD http://www.getmdl.io/assets/clippy.swf

curl: (18) transfer closed with 5380 bytes remaining to read
```

**Comment by steven-qi** [comment] 2015-07-09 05:11
And if I visit the site with ```https```, it works, and the swf file is fetched over SPDY/3.

**Comment by marcacohen** [comment] 2015-07-09 08:42
@steven-qi The fact that --head works for you and -X HEAD does not is entirely consistent with what we're seeing. As Nicolas noted upthread...

This option only changes the actual word used in the HTTP request, it does not alter the way curl behaves. So for example if you want to make a proper HEAD request, using -X HEAD will not suffice. You need to use the -I, --head option.

Given you're traversing proxies (some of which I presume are outside of your control) I have a feeling there is something subtle going on here which may not be obvious from the Chrome Devtools network view. Perhaps a packet trace would help. Do you have access to Wireshark, by any chance?

**Comment by steven-qi** [comment] 2015-07-09 09:51
I don't think that I can run a packet trace... but I found the following facts:
1. by chaining up my fiddler (a local proxy) to the out-proxy, I found that the out-proxy actually respond to the HEAD request instantly, but IE still says that is is 'pending'...
2. after a long time, IE shows response headers from proxy in devtools correctly (which is 200 OK), but in response body tab, it shows 408 timeout:

![response](https://cloud.githubusercontent.com/assets/6123222/8592553/dd9c0dd6-2662-11e5-91c4-3a806a51e78c.PNG)


```
HTTP/1.1 408 Request Timed Out
Date: Thu, 09 Jul 2015 09:35:24 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Cache-Control: no-cache, must-revalidate
Timestamp: 17:35:24.714

The client failed to send a complete request before the timeout period elapsed.               
```

It seems that IE (or the flash plugin?) is expecting a body for HEAD request just like ```curl -X HEAD```. Wired enough...

**Comment by steven-qi** [comment] 2015-07-09 10:21
By letting fiddler response to clippy.swf request from a local file, IE works OK (although copy still don't work).

![response from fiddler](https://cloud.githubusercontent.com/assets/6123222/8593110/53999e14-2667-11e5-9965-4ee960379f6f.PNG)


The only difference I call tell is that, fiddler respond with ```HTTP/1.1 200```, while the out-proxy (or GCS) returns ```HTTP/1.0 200```. Not sure that if any chance that ```HEAD``` might only be defined in HTTP 1.1, which cause IE to expect a response body when seeing ```HTTP/1.0 200``` for ```HEAD```.

**Comment by nicolasgarnier** [comment] 2015-07-09 10:37
On my side I get a response with `HTTP/1.1 200` from GCS:

```bash
nivco> curl -v -X HEAD www.getmdl.io/assets/clippy.swf

* Hostname was NOT found in DNS cache
*   Trying 64.233.167.128...
* Connected to www.getmdl.io (64.233.167.128) port 80 (#0)
> HEAD /assets/clippy.swf HTTP/1.1
> User-Agent: curl/7.37.1
> Host: www.getmdl.io
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-GUploader-UploadID: AEnB2Uqg4QNs6FQh9AzTPJ8GK-Cj5hwzNlTs02oPOT9rP4-uKcYPm5UeoD6guzQ8oPR4RocQyNOtAQ2A7SYJ8Uc6MWI44cK6YQ
< Date: Thu, 09 Jul 2015 10:33:21 GMT
< Expires: Thu, 09 Jul 2015 10:34:21 GMT
< Last-Modified: Tue, 07 Jul 2015 17:52:46 GMT
< ETag: "b0125fa4276f0734dc6f9345292a9176"
< x-goog-generation: 1436291566492000
< x-goog-metageneration: 2
< x-goog-stored-content-encoding: identity
< x-goog-stored-content-length: 5380
< Content-Type: application/x-shockwave-flash
< x-goog-hash: crc32c=99+AVQ==
< x-goog-hash: md5=sBJfpCdvBzTcb5NFKSqRdg==
< x-goog-storage-class: STANDARD
< Accept-Ranges: bytes
< Vary: Accept-Encoding
< Content-Length: 5380
* Server UploadServer is not blacklisted
< Server: UploadServer
< Cache-Control: public,max-age=60
< Age: 7
< Alternate-Protocol: 80:quic,p=0
```

If you are seeing `HTTP/1.0 200` maybe the proxy is changing that. Not sure at this point if that's what would cause the issue thought...

**Comment by nicolasgarnier** [comment] 2015-07-09 10:40
Although if you have the chance it might be worth trying all this on your side using a VPN instead of a proxy to see if the proxy may be at fault...

**Comment by steven-qi** [comment] 2015-07-09 11:16
Well, I created a web server myself, and reproduced the same behavior.

Looks like that it is not caused by ```http/1.0```, but the ```Connection: keep-alive``` header. As long as the header is there, I can reproduce the issue with either HTTP/1.1 or 1.0.

From your post, I guess that the header is added by the out-proxy somehow...

**Comment by steven-qi** [comment] 2015-07-09 11:19
@nicolasgarnier I guess it will work with VPN, but I don't have a chance to try it myself. I will try to look into the out-proxy configuration (maybe a bug of squid/2.7).

**Comment by steven-qi** [comment] 2015-07-09 11:30
Verbose output of curl.
```
$ curl -x http://<proxy>:80 -v --head www.getmdl.io/assets/clippy.swf
*   Trying <proxy>...
* Connected to <proxy> (<proxy>) port 80 (#0)
> HEAD HTTP://www.getmdl.io/assets/clippy.swf HTTP/1.1
> User-Agent: curl/7.41.0
> Host: www.getmdl.io
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
HTTP/1.0 200 OK
< X-GUploader-UploadID: AEnB2UqylxLAXyPy3LbTM502OscZHPef0Zfldem8obxXGkcE88NVByksIaoURx7AqYZS9P989e_Ir5prd-6oWCvzhZsVnw5-Hw
X-GUploader-UploadID: AEnB2UqylxLAXyPy3LbTM502OscZHPef0Zfldem8obxXGkcE88NVByksIaoURx7AqYZS9P989e_Ir5prd-6oWCvzhZsVnw5-Hw
< Date: Thu, 09 Jul 2015 11:23:31 GMT
Date: Thu, 09 Jul 2015 11:23:31 GMT
< Cache-Control: public,max-age=60
Cache-Control: public,max-age=60
< Expires: Thu, 09 Jul 2015 11:24:31 GMT
Expires: Thu, 09 Jul 2015 11:24:31 GMT
< Last-Modified: Tue, 07 Jul 2015 17:52:46 GMT
Last-Modified: Tue, 07 Jul 2015 17:52:46 GMT
< ETag: "b0125fa4276f0734dc6f9345292a9176"
ETag: "b0125fa4276f0734dc6f9345292a9176"
< x-goog-generation: 1436291566492000
x-goog-generation: 1436291566492000
< x-goog-metageneration: 2
x-goog-metageneration: 2
< x-goog-stored-content-encoding: identity
x-goog-stored-content-encoding: identity
< x-goog-stored-content-length: 5380
x-goog-stored-content-length: 5380
< Content-Type: application/x-shockwave-flash
Content-Type: application/x-shockwave-flash
< x-goog-hash: crc32c=99+AVQ==
x-goog-hash: crc32c=99+AVQ==
< x-goog-hash: md5=sBJfpCdvBzTcb5NFKSqRdg==
x-goog-hash: md5=sBJfpCdvBzTcb5NFKSqRdg==
< x-goog-storage-class: STANDARD
x-goog-storage-class: STANDARD
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Vary: Accept-Encoding
Vary: Accept-Encoding
< Content-Length: 5380
Content-Length: 5380
< Server: UploadServer
Server: UploadServer
< Alternate-Protocol: 80:quic,p=0
Alternate-Protocol: 80:quic,p=0
< X-Cache: MISS from <cache-server>
X-Cache: MISS from <cache-server>
< X-Cache-Lookup: MISS from <cache-server>:80
X-Cache-Lookup: MISS from <cache-server>:80
< Via: 1.0 <cache-server>:80 (squid/2.7.STABLE8)
Via: 1.0 <cache-server>:80 (squid/2.7.STABLE8)
* HTTP/1.0 connection set to keep alive!
< Connection: keep-alive
Connection: keep-alive
* HTTP/1.0 proxy connection set to keep alive!
< Proxy-Connection: keep-alive
Proxy-Connection: keep-alive

<
* Connection #0 to host <proxy> left intact
```

**Comment by nicolasgarnier** [comment] 2015-07-09 19:14
Hey @steven-qi since this doesn't seems to be related to an issue specific to MDL lets close this bug. you can still update this thread with your findings as it may help someone and/or reopen if this appears to be an MDL issue. Also we've tested the copy paste feature after the Fix for Firefox and it seems this worked well. Furthermore we've made some performance improvements on the components page such as generating the codepen buttons at build time and removing lots of the ripples on the page. There are still more improvements we can do but we'll open a specific issue for this as it is not IE specific. Thanks for looking into this and  please let us know how this goes!

**Closed by nicolasgarnier** 2015-07-09 19:14 UTC

**Comment by steven-qi** [comment] 2015-07-10 01:23
Thanks @nicolasgarnier :+1:
