### ISSUE TITLE
Search Icon on the wrong position

### ISSUE THREAD

**Issue by etrupja** [google/material-design-lite#4695] opened 2016-08-25 09:39 UTC
The search icon seems to be on the wrong postition. I am using latest Google chrome version. 
![image](https://cloud.githubusercontent.com/assets/20356633/17964043/83402cdc-6ab8-11e6-8b15-bdb8dc32a142.png)

**Comment by Garbee** [comment] 2016-08-25 10:56
Duplicate of #4690

**Closed by Garbee** 2016-08-25 10:56 UTC
