### ISSUE TITLE
Responsive is falling apart

### ISSUE THREAD

**Issue by TheOriginalMementoMori** [google/material-design-lite#4722] opened 2016-09-05 18:54 UTC
Version: 1.2.0
Browser: Firefox 48.0.2
OS: Windows 10

-What are the steps to reproduce the bug?

Switch any mobile layout to landscape

What is the expected behavior?

I was expecting just a resize of the elements, not everything breaking.

What is the actual behavior?

Evertyhing seems ok in portrait mode, but when I switch to landscape, the phone starts to behave like tablet and tablet like desktops, and everyhing in the layout falls apart.

Using the "rotate" button on "Toggle Responsive Design Mode" plugin for FF.

**Comment by sgomes** [comment] 2016-09-08 15:40
Hello! Could you provide an example URL where the bug happens?
Any screenshots would be super helpful as well, as it's not clear exactly what's "breaking".

Thanks!

**Comment by PAFaieta** [comment] 2016-09-08 20:49
Firefox is essentially trying to simulate a mobile view, but the browser is probably misinterpreting the breakpoints. I wouldn't consider this an accurate depiction of the framework's behavior. I noticed a few oddities in Chrome using the element inspector which don't show up once the code is actually deployed.

**Comment by sgomes** [comment] 2016-09-09 09:43
I'm afraid I can't reproduce the issue. Trying out Firefox 48 OS X in Responsive Design mode and flipping between portrait and landscape orientations works fine for me in https://getmdl.io

From your description, it sounds like it's more likely a browser issue than anything wrong with MDL, but it's hard to tell without any screenshots or even a URL to look at.

As such, I'm closing the issue for now, but happy to reopen if we get more info.

**Closed by sgomes** 2016-09-09 09:43 UTC
