### ISSUE TITLE
Creation of CustomEvent in componentHandler.upgradeElementInternal does not respect globally defined CustomEvent constructor polyfill

### ISSUE THREAD

**Issue by leifoolsen** [google/material-design-lite#4264] opened 2016-04-12 11:59 UTC
MDL version: 1.1.3
Browser: Internet Explorer
Browser version: 11, edge
Operating system: Windows
Operating system version: 
URL, if applicable (you can use a [codepen as a starting point][http://codepen.io/pen/def?fork=xGWgXa]):

**What steps will reproduce the problem:**
&nbsp;1. Create a HTML page
&nbsp;2. Import CSS
```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="styles/dialog-polyfill.css">
<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.grey-orange.min.css">
```
&nbsp;3. Code a div element for MDL layout and add some MDL components, e.g. 
```html
<div class="mdl-layout mdl-js-layout">
  <div class="mdl-button mdl-js-button>
  .....
```
&nbsp;4. Import CustomEvent polyfill script 
&nbsp;5. Import material.js
```html
<script src="scripts/custom-event-polyfill.js" type="text/javascript" charset="utf-8"></script>
<script src="scripts/dialog-polyfill.js" type="text/javascript" charset="utf-8"></script>
<script src="https://code.getmdl.io/1.1.3/material.min.js" type="text/javascript" charset="utf-8"></script>
```
&nbsp;6. Open the HTML i Internet Explorer 11

**What is the expected result?**
MDL should return the `mdl-componentupgraded` event

**What happens instead of that?**
MDL fails fails with the following error: **"Object doesn't support this action"**. 

**Please provide any other information below, and attach a screenshot if possible.**

This is the CustomEvent polyfill I use:
```javascript
// code pulled from:
// https://github.com/d4tocchini/customevent-polyfill
// https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent#Polyfill
// https://github.com/webcomponents/webcomponentsjs/blob/v0.7.12/CustomElements.js#L950

try {
  new window.CustomEvent("test");
}
catch(e) {
  window.CustomEvent = function(inType, params) {
    params = params || {
        bubbles: false,
        cancelable: false,
        detail: null
      };

    var e = document.createEvent("CustomEvent");
    e.initCustomEvent(inType, Boolean(params.bubbles), Boolean(params.cancelable), params.detail);
    e.preventDefault = function() {
      Object.defineProperty(this, "defaultPrevented", {
        get: function() {
          return true;
        }
      });
    };
    return e;
  };
  window.CustomEvent.prototype = window.Event.prototype;
}
``` 

Many third-party libraries relies on a polyfill for a shortfall in functionality related to the CustomEvent constructor in Internet Explorer 11. Obviously a conflict arises in MDL code if an polyfill already exist. The code in MDL must be rewritten so that it does not conflict with an existing polyfill. If it is not desirable to use a separate polyfill, one can for example use a factory method - something similar to what the Google dialog-polyfill does. I have also looked at corresponding code in the v2 branch - and to me it seems that the changes do not resolve the problem. 

Here is an example of a factory that might work:

```javascript
/**
 * @param {string} typeArg Is a String representing the name of the event.
 * @param {Object} customEventInit Is an EventInit dictionary, having the following fields:
 *        "bubbles", optional and defaulting to false, of type Boolean, indicating if the event bubbles or not.
 *        "cancelable", optional and defaulting to false, of type Boolean, indicating if the event can be canceled or not.
 *        "detail", optional and defaulting to null, of type any, that is an event-dependent value associated with the event.
 */

export function createCustomEvent( typeArg, customEventInit = { bubbles: false, cancelable: false, detail: null } ) {
  'use strict';

  try {
    // Modern browsers
    return new window.CustomEvent(typeArg, customEventInit);
  }
  catch(e) {
    // Copied from https://github.com/webcomponents/webcomponentsjs/blob/v0.7.12/CustomElements.js#L950
    // Copied from http://stackoverflow.com/questions/23349191/event-preventdefault-is-not-working-in-ie-11-for-custom-events
    const ce = document.createEvent('CustomEvent');
    ce.initCustomEvent(typeArg, customEventInit.bubbles, customEventInit.cancelable, customEventInit.detail);

    ce.preventDefault = function() {
      Object.defineProperty(this, 'defaultPrevented', {
        get: function() {
          return true;
        }
      });
    };
    return ce;
  }
  // Don't care about older browsers
  // Let them throw whatewer they want to throw
}
```

This is a critical error! None of the loaded js-libs works after failure in MDL.

Regards
Leif Olsen

**Comment by Garbee** [comment] 2016-05-12 18:15
Duplicate of #4239.

**Closed by Garbee** 2016-05-12 18:15 UTC
