### ISSUE TITLE
mocha-phantomjs error when building under Windows 8.1

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#1089] opened 2015-07-17 10:47 UTC
Keen to build the project so I can contribute pull requests. It's been a bit of a process getting it going under windows but I'm getting there, I'm currently stuck on an error. I understand its a version issue with mocha-phantomjs but I'm not sure how to fix it.

```
C:\...\material-design-lite>npm install

> material-design-lite@1.0.0 install C:\...\material-design-lite
> napa mojombo/clippy

info git git://github.com/mojombo/clippy into clippy
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\
\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mocha-phantomjs@3.6.0 wants phantomjs@1.9.1 - 1.9.7-15
```

**Comment by hugofqueiros** [comment] 2015-07-17 13:56
+1 same on Ubuntu 14.04
npm ERR! peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mocha-phantomjs@3.6.0 wants phantomjs@1.9.1 - 1.9.7-15

**Comment by JoshuaKGoldberg** [comment] 2015-07-18 22:45
Try updating the gulp-mocha-phantomjs version in package.json?

**Comment by pho3nixf1re** [comment] 2015-07-19 14:41
Is this a duplicate of https://github.com/google/material-design-lite/pull/947 perchance?

**Comment by Garbee** [comment] 2015-07-19 14:45
No, this is an actual dep issue. It seems something has happened within the dep requirements to cause them to not install properly anymore. Nothing has changed recently in our package.json to cause this and  it was working at and shortly after launch just fine.

NPM woes, oh boy.

**Comment by Garbee** [comment] 2015-07-19 14:49
Also, the gulp setup is being reworked in the next few days as I recall. So it will probably get debugged and fixed as a part of that process. Leaving open as an issue,  but un-tagged since we don't currently have a good tag for these types of issues.

**Comment by Garbee** [comment] 2015-07-19 21:29
Maybe just trying it later?

I had this same error this morning, but now it installs fine.

NPM, oh how I hate thee.

**Comment by kelsmj** [comment] 2015-07-20 14:04
For what it is worth, I am still getting the same error on latest code.

**Comment by Garbee** [comment] 2015-07-20 15:00
We just realized in #1126 that node 0.12 is having issues unless we explicitly define the phantomjs version. Once that is pulled in then master should begin working fine.

**Comment by SeanBannister** [comment] 2015-07-22 06:09
Thanks kelsmj, that got me past that bug. I'm now stuck with the following when I ```gulp serve```. Hopefully the gulp re-factor fixes this:
```
[16:05:09] Using gulpfile ~\SkyDrive\Development\3rd party\material-design-lite\gulpfile.js
[16:05:09] Starting 'clean'...
[16:05:09] Starting 'styletemplates'...
[16:05:10] Finished 'clean' after 575 ms
[16:05:13] 'styles' all files 483.82 kB
[16:05:13] Finished 'styletemplates' after 3.94 s
[16:05:13] Starting 'styles'...
[16:05:16] 'styles' all files 483.05 kB
[16:05:16] Finished 'styles' after 2.57 s
[16:05:16] Starting 'mocha'...
'C:\Users\Sean\SkyDrive\Development\3rd' is not recognized as an internal or external command,
operable program or batch file.
[16:05:16] 'mocha' errored after 290 ms
[16:05:16] Error in plugin 'gulp-mocha-phantomjs'
test failed
```

**Comment by surma** [comment] 2015-07-22 08:40
There error message makes me assume you have a space in your path and either us or the plugin doesn't handle that (well). Can you try a path without spaces to confirm?

**Comment by surma** [comment] 2015-07-30 14:34
I finally got around to looking at this with a fresh Windows 8.1.

There’s an issue with `gulp-mocha-phantomjs` when the current path contains space (which, sadly, is almost always the case if you are working in your user directory). Haven’t looked into the plugin myself, for now I’m working in `C:\dev`.

There’s also an issue if you checkout the files with crlf ending. See #743 for more details on how to handle that.

Other than that, though, I can’t reproduce your issue (anymore) and everything seems to work. I’m closing this as this has been silent for over a week. If you still run into issues, please let me know.

**Closed by surma** 2015-07-30 14:34 UTC

**Comment by vasiliy-pdk** [comment] 2015-09-03 21:57
Hi, guys. I got the same error on Ubuntu 14.04. 

I fixed it with explicitly setting version for phantomjs like `"phantomjs": "1.9.7-14"`. 

npm-debug.log content:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/vazia/.nvm/versions/node/v0.12.7/bin/node',
1 verbose cli   '/home/vazia/.nvm/versions/node/v0.12.7/bin/npm',
1 verbose cli   'install' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose readDependencies loading dependencies from /home/vazia/dev/material-design-lite/package.json
5 verbose install where, deps [ '/home/vazia/dev/material-design-lite',
5 verbose install   [ 'acorn',
5 verbose install     'apache-server-configs',
5 verbose install     'browser-sync',
5 verbose install     'chai',
5 verbose install     'chai-jquery',
5 verbose install     'del',
5 verbose install     'drool',
5 verbose install     'escodegen',
5 verbose install     'gulp',
5 verbose install     'gulp-autoprefixer',
5 verbose install     'gulp-cache',
5 verbose install     'gulp-changed',
5 verbose install     'gulp-concat',
5 verbose install     'gulp-connect',
5 verbose install     'gulp-css-inline-images',
5 verbose install     'gulp-csso',
5 verbose install     'gulp-file',
5 verbose install     'gulp-filter',
5 verbose install     'gulp-flatten',
5 verbose install     'gulp-front-matter',
5 verbose install     'gulp-gh-pages',
5 verbose install     'gulp-header',
5 verbose install     'gulp-if',
5 verbose install     'gulp-iife',
5 verbose install     'gulp-imagemin',
5 verbose install     'gulp-jscs',
5 verbose install     'gulp-jshint',
5 verbose install     'gulp-load-plugins',
5 verbose install     'gulp-markdown',
5 verbose install     'gulp-marked',
5 verbose install     'gulp-minify-html',
5 verbose install     'gulp-mocha-phantomjs',
5 verbose install     'gulp-open',
5 verbose install     'gulp-rename',
5 verbose install     'gulp-replace',
5 verbose install     'gulp-sass',
5 verbose install     'gulp-shell',
5 verbose install     'gulp-size',
5 verbose install     'gulp-sourcemaps',
5 verbose install     'gulp-subtree',
5 verbose install     'gulp-tap',
5 verbose install     'gulp-uglify',
5 verbose install     'gulp-useref',
5 verbose install     'gulp-util',
5 verbose install     'gulp-zip',
5 verbose install     'humanize',
5 verbose install     'jquery',
5 verbose install     'jshint-stylish',
5 verbose install     'merge-stream',
5 verbose install     'mocha',
5 verbose install     'opn',
5 verbose install     'phantomjs',
5 verbose install     'prismjs',
5 verbose install     'require-dir',
5 verbose install     'run-sequence',
5 verbose install     'swig',
5 verbose install     'through2',
5 verbose install     'vinyl-paths' ] ]
6 verbose install where, peers [ '/home/vazia/dev/material-design-lite', [] ]
7 verbose installManyTop reading for lifecycle /home/vazia/dev/material-design-lite/package.json
8 info preinstall material-design-lite@1.0.4
9 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/acorn/package.json
10 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/apache-server-configs/package.json
11 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/browser-sync/package.json
12 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/chai/package.json
13 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/chai-jquery/package.json
14 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/del/package.json
15 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/drool/package.json
16 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/escodegen/package.json
17 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp/package.json
18 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-autoprefixer/package.json
19 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-cache/package.json
20 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-changed/package.json
21 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-concat/package.json
22 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-connect/package.json
23 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-css-inline-images/package.json
24 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-csso/package.json
25 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-file/package.json
26 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-filter/package.json
27 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-flatten/package.json
28 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-front-matter/package.json
29 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-gh-pages/package.json
30 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-header/package.json
31 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-if/package.json
32 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-iife/package.json
33 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-imagemin/package.json
34 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-jscs/package.json
35 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-jshint/package.json
36 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-load-plugins/package.json
37 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-markdown/package.json
38 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-marked/package.json
39 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-minify-html/package.json
40 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-mocha-phantomjs/package.json
41 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-open/package.json
42 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-rename/package.json
43 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-replace/package.json
44 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-sass/package.json
45 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-shell/package.json
46 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-size/package.json
47 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-sourcemaps/package.json
48 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-subtree/package.json
49 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-tap/package.json
50 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-uglify/package.json
51 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-useref/package.json
52 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-util/package.json
53 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/gulp-zip/package.json
54 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/humanize/package.json
55 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/jquery/package.json
56 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/jshint-stylish/package.json
57 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/merge-stream/package.json
58 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/mocha/package.json
59 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/opn/package.json
60 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/phantomjs/package.json
61 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/prismjs/package.json
62 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/require-dir/package.json
63 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/run-sequence/package.json
64 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/swig/package.json
65 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/through2/package.json
66 verbose installManyTop reading scoped package data from /home/vazia/dev/material-design-lite/node_modules/vinyl-paths/package.json
67 info package.json humanize@0.0.9 No license field.
68 info package.json apache-server-configs@2.14.0 license should be a valid SPDX license expression
69 info package.json chai-jquery@2.0.0 No license field.
70 info package.json drool@0.2.1 No repository field.
71 info package.json drool@0.2.1 No license field.
72 info package.json escodegen@1.6.1 No license field.
73 info package.json gulp-file@0.2.0 license should be a valid SPDX license expression
74 info package.json gulp-if@1.2.5 No license field.
75 info package.json gulp-marked@1.0.0 No repository field.
76 info package.json gulp-marked@1.0.0 No license field.
77 info package.json gulp-open@0.3.2 No license field.
78 info package.json gulp-rename@1.2.2 No license field.
79 info package.json jquery@2.1.4 No license field.
80 verbose readDependencies loading dependencies from /home/vazia/dev/material-design-lite/package.json
81 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/acorn/package.json
82 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/apache-server-configs/package.json
83 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/browser-sync/package.json
84 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/chai/package.json
85 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/chai-jquery/package.json
86 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/del/package.json
87 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/drool/package.json
88 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/escodegen/package.json
89 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp/package.json
90 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-autoprefixer/package.json
91 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-cache/package.json
92 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-changed/package.json
93 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-concat/package.json
94 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-connect/package.json
95 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-css-inline-images/package.json
96 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-csso/package.json
97 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-file/package.json
98 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-filter/package.json
99 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-flatten/package.json
100 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-front-matter/package.json
101 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-gh-pages/package.json
102 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-header/package.json
103 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-if/package.json
104 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-iife/package.json
105 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-imagemin/package.json
106 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-jscs/package.json
107 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-jshint/package.json
108 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-load-plugins/package.json
109 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-markdown/package.json
110 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-marked/package.json
111 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-minify-html/package.json
112 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-mocha-phantomjs/package.json
113 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-open/package.json
114 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-rename/package.json
115 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-replace/package.json
116 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-sass/package.json
117 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-shell/package.json
118 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-size/package.json
119 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-sourcemaps/package.json
120 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-subtree/package.json
121 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-tap/package.json
122 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-uglify/package.json
123 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-useref/package.json
124 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-util/package.json
125 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/gulp-zip/package.json
126 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/humanize/package.json
127 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/jquery/package.json
128 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/jshint-stylish/package.json
129 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/merge-stream/package.json
130 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/mocha/package.json
131 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/opn/package.json
132 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/phantomjs/package.json
133 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/prismjs/package.json
134 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/require-dir/package.json
135 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/run-sequence/package.json
136 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/swig/package.json
137 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/through2/package.json
138 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/vinyl-paths/package.json
139 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/.bin/acorn/package.json
140 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/.bin/opn/package.json
141 verbose targetResolver reading package data from /home/vazia/dev/material-design-lite/node_modules/.bin/phantomjs/package.json
142 verbose already installed skipping gulp-csso@^1.0.0 /home/vazia/dev/material-design-lite
143 verbose already installed skipping gulp-file@^0.2.0 /home/vazia/dev/material-design-lite
144 verbose already installed skipping gulp-filter@^2.0.2 /home/vazia/dev/material-design-lite
145 verbose already installed skipping gulp-flatten@0.0.4 /home/vazia/dev/material-design-lite
146 verbose already installed skipping gulp-front-matter@^1.2.2 /home/vazia/dev/material-design-lite
147 verbose already installed skipping gulp-gh-pages@^0.5.0 /home/vazia/dev/material-design-lite
148 verbose already installed skipping gulp-header@^1.2.2 /home/vazia/dev/material-design-lite
149 verbose already installed skipping gulp-if@^1.2.1 /home/vazia/dev/material-design-lite
150 verbose already installed skipping gulp-iife@0.0.7 /home/vazia/dev/material-design-lite
151 verbose already installed skipping gulp-imagemin@^2.2.1 /home/vazia/dev/material-design-lite
152 verbose already installed skipping gulp-jscs@^1.6.0 /home/vazia/dev/material-design-lite
153 verbose already installed skipping gulp-jshint@^1.6.3 /home/vazia/dev/material-design-lite
154 verbose already installed skipping gulp-load-plugins@^0.10.0 /home/vazia/dev/material-design-lite
155 verbose already installed skipping gulp-markdown@^1.0.0 /home/vazia/dev/material-design-lite
156 verbose already installed skipping gulp-marked@^1.0.0 /home/vazia/dev/material-design-lite
157 verbose already installed skipping gulp-minify-html@^1.0.0 /home/vazia/dev/material-design-lite
158 verbose already installed skipping gulp-mocha-phantomjs@^0.6.1 /home/vazia/dev/material-design-lite
159 verbose already installed skipping gulp-open@^0.3.2 /home/vazia/dev/material-design-lite
160 verbose already installed skipping gulp-rename@^1.2.0 /home/vazia/dev/material-design-lite
161 verbose already installed skipping gulp-replace@^0.5.3 /home/vazia/dev/material-design-lite
162 verbose already installed skipping gulp-sass@2.0.* /home/vazia/dev/material-design-lite
163 verbose already installed skipping gulp-shell@^0.4.2 /home/vazia/dev/material-design-lite
164 verbose already installed skipping gulp-size@^1.0.0 /home/vazia/dev/material-design-lite
165 verbose already installed skipping gulp-sourcemaps@^1.3.0 /home/vazia/dev/material-design-lite
166 verbose already installed skipping gulp-subtree@^0.1.0 /home/vazia/dev/material-design-lite
167 verbose already installed skipping gulp-tap@^0.1.3 /home/vazia/dev/material-design-lite
168 verbose already installed skipping gulp-uglify@^1.0.1 /home/vazia/dev/material-design-lite
169 verbose already installed skipping gulp-useref@^1.0.1 /home/vazia/dev/material-design-lite
170 verbose already installed skipping gulp-util@^3.0.4 /home/vazia/dev/material-design-lite
171 verbose already installed skipping gulp-zip@^3.0.2 /home/vazia/dev/material-design-lite
172 verbose already installed skipping humanize@0.0.9 /home/vazia/dev/material-design-lite
173 verbose already installed skipping jquery@^2.1.3 /home/vazia/dev/material-design-lite
174 verbose already installed skipping jshint-stylish@^1.0.0 /home/vazia/dev/material-design-lite
175 verbose already installed skipping merge-stream@^0.1.7 /home/vazia/dev/material-design-lite
176 verbose already installed skipping mocha@^2.1.0 /home/vazia/dev/material-design-lite
177 verbose already installed skipping opn@^1.0.0 /home/vazia/dev/material-design-lite
178 verbose already installed skipping phantomjs@^1.9.17 /home/vazia/dev/material-design-lite
179 verbose already installed skipping prismjs@0.0.1 /home/vazia/dev/material-design-lite
180 verbose already installed skipping require-dir@^0.3.0 /home/vazia/dev/material-design-lite
181 verbose already installed skipping run-sequence@^1.0.2 /home/vazia/dev/material-design-lite
182 verbose already installed skipping swig@^1.4.2 /home/vazia/dev/material-design-lite
183 verbose already installed skipping through2@^2.0.0 /home/vazia/dev/material-design-lite
184 verbose already installed skipping vinyl-paths@^1.0.0 /home/vazia/dev/material-design-lite
185 verbose already installed skipping acorn@^2.2.0 /home/vazia/dev/material-design-lite
186 verbose already installed skipping apache-server-configs@^2.7.1 /home/vazia/dev/material-design-lite
187 verbose already installed skipping browser-sync@^2.2.3 /home/vazia/dev/material-design-lite
188 verbose already installed skipping chai@^2.0.0 /home/vazia/dev/material-design-lite
189 verbose already installed skipping chai-jquery@^2.0.0 /home/vazia/dev/material-design-lite
190 verbose already installed skipping del@^1.1.1 /home/vazia/dev/material-design-lite
191 verbose already installed skipping drool@^0.2.1 /home/vazia/dev/material-design-lite
192 verbose already installed skipping escodegen@^1.6.1 /home/vazia/dev/material-design-lite
193 verbose already installed skipping gulp@^3.8.11 /home/vazia/dev/material-design-lite
194 verbose already installed skipping gulp-autoprefixer@^2.0.0 /home/vazia/dev/material-design-lite
195 verbose already installed skipping gulp-cache@^0.2.6 /home/vazia/dev/material-design-lite
196 verbose already installed skipping gulp-changed@^1.0.0 /home/vazia/dev/material-design-lite
197 verbose already installed skipping gulp-concat@^2.4.1 /home/vazia/dev/material-design-lite
198 verbose already installed skipping gulp-connect@^2.2.0 /home/vazia/dev/material-design-lite
199 verbose already installed skipping gulp-css-inline-images@^0.1.1 /home/vazia/dev/material-design-lite
200 silly install resolved []
201 info build /home/vazia/dev/material-design-lite
202 info linkStuff material-design-lite@1.0.4
203 silly linkStuff material-design-lite@1.0.4 has /home/vazia/dev as its parent node_modules
204 verbose linkBins material-design-lite@1.0.4
205 verbose linkMans material-design-lite@1.0.4
206 verbose rebuildBundles material-design-lite@1.0.4
207 verbose rebuildBundles [ '.bin',
207 verbose rebuildBundles   'acorn',
207 verbose rebuildBundles   'apache-server-configs',
207 verbose rebuildBundles   'browser-sync',
207 verbose rebuildBundles   'chai',
207 verbose rebuildBundles   'chai-jquery',
207 verbose rebuildBundles   'del',
207 verbose rebuildBundles   'drool',
207 verbose rebuildBundles   'escodegen',
207 verbose rebuildBundles   'gulp',
207 verbose rebuildBundles   'gulp-autoprefixer',
207 verbose rebuildBundles   'gulp-cache',
207 verbose rebuildBundles   'gulp-changed',
207 verbose rebuildBundles   'gulp-concat',
207 verbose rebuildBundles   'gulp-connect',
207 verbose rebuildBundles   'gulp-css-inline-images',
207 verbose rebuildBundles   'gulp-csso',
207 verbose rebuildBundles   'gulp-file',
207 verbose rebuildBundles   'gulp-filter',
207 verbose rebuildBundles   'gulp-flatten',
207 verbose rebuildBundles   'gulp-front-matter',
207 verbose rebuildBundles   'gulp-gh-pages',
207 verbose rebuildBundles   'gulp-header',
207 verbose rebuildBundles   'gulp-if',
207 verbose rebuildBundles   'gulp-iife',
207 verbose rebuildBundles   'gulp-imagemin',
207 verbose rebuildBundles   'gulp-jscs',
207 verbose rebuildBundles   'gulp-jshint',
207 verbose rebuildBundles   'gulp-load-plugins',
207 verbose rebuildBundles   'gulp-markdown',
207 verbose rebuildBundles   'gulp-marked',
207 verbose rebuildBundles   'gulp-minify-html',
207 verbose rebuildBundles   'gulp-mocha-phantomjs',
207 verbose rebuildBundles   'gulp-open',
207 verbose rebuildBundles   'gulp-rename',
207 verbose rebuildBundles   'gulp-replace',
207 verbose rebuildBundles   'gulp-sass',
207 verbose rebuildBundles   'gulp-shell',
207 verbose rebuildBundles   'gulp-size',
207 verbose rebuildBundles   'gulp-sourcemaps',
207 verbose rebuildBundles   'gulp-subtree',
207 verbose rebuildBundles   'gulp-tap',
207 verbose rebuildBundles   'gulp-uglify',
207 verbose rebuildBundles   'gulp-useref',
207 verbose rebuildBundles   'gulp-util',
207 verbose rebuildBundles   'gulp-zip',
207 verbose rebuildBundles   'humanize',
207 verbose rebuildBundles   'jquery',
207 verbose rebuildBundles   'jshint-stylish',
207 verbose rebuildBundles   'merge-stream',
207 verbose rebuildBundles   'mocha',
207 verbose rebuildBundles   'opn',
207 verbose rebuildBundles   'phantomjs',
207 verbose rebuildBundles   'prismjs',
207 verbose rebuildBundles   'require-dir',
207 verbose rebuildBundles   'run-sequence',
207 verbose rebuildBundles   'swig',
207 verbose rebuildBundles   'through2',
207 verbose rebuildBundles   'vinyl-paths' ]
208 info install material-design-lite@1.0.4
209 info postinstall material-design-lite@1.0.4
210 info prepublish material-design-lite@1.0.4
211 verbose validateInstall loading /home/vazia/dev/material-design-lite/package.json for validation
212 warn unmet dependency /home/vazia/dev/material-design-lite/node_modules/browser-sync requires opn@'^2.0.1' but will load
212 warn unmet dependency /home/vazia/dev/material-design-lite/node_modules/opn,
212 warn unmet dependency which is version 1.0.2
213 warn unmet dependency /home/vazia/dev/material-design-lite/node_modules/mocha/node_modules/jade requires commander@'~2.6.0' but will load
213 warn unmet dependency /home/vazia/dev/material-design-lite/node_modules/mocha/node_modules/commander,
213 warn unmet dependency which is version 2.3.0
214 warn unmet dependency /home/vazia/dev/material-design-lite/node_modules/gulp-jshint/node_modules/jshint requires lodash@'3.7.x' but will load
214 warn unmet dependency /home/vazia/dev/material-design-lite/node_modules/gulp-jshint/node_modules/lodash,
214 warn unmet dependency which is version 3.10.1
215 warn unmet dependency /home/vazia/dev/material-design-lite/node_modules/gulp-mocha-phantomjs/node_modules/mocha-phantomjs/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load
215 warn unmet dependency /home/vazia/dev/material-design-lite/node_modules/gulp-mocha-phantomjs/node_modules/mocha-phantomjs/node_modules/commander,
215 warn unmet dependency which is version 2.0.0
216 warn unmet dependency /home/vazia/dev/material-design-lite/node_modules/gulp-mocha-phantomjs/node_modules/mocha-phantomjs/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load
216 warn unmet dependency /home/vazia/dev/material-design-lite/node_modules/gulp-mocha-phantomjs/node_modules/mocha-phantomjs/node_modules/mocha/node_modules/mkdirp,
216 warn unmet dependency which is version 0.3.5
217 verbose stack Error: The package phantomjs does not satisfy its siblings' peerDependencies requirements!
217 verbose stack     at /home/vazia/.nvm/versions/node/v0.12.7/lib/node_modules/npm/lib/install.js:125:32
217 verbose stack     at /home/vazia/.nvm/versions/node/v0.12.7/lib/node_modules/npm/lib/install.js:267:7
217 verbose stack     at /home/vazia/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/read-installed/read-installed.js:138:5
217 verbose stack     at /home/vazia/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
217 verbose stack     at cb (/home/vazia/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
217 verbose stack     at /home/vazia/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
217 verbose stack     at cb (/home/vazia/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
217 verbose stack     at /home/vazia/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
217 verbose stack     at cb (/home/vazia/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
217 verbose stack     at /home/vazia/.nvm/versions/node/v0.12.7/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
218 verbose cwd /home/vazia/dev/material-design-lite
219 error Linux 3.19.0-26-generic
220 error argv "/home/vazia/.nvm/versions/node/v0.12.7/bin/node" "/home/vazia/.nvm/versions/node/v0.12.7/bin/npm" "install"
221 error node v0.12.7
222 error npm  v2.11.3
223 error code EPEERINVALID
224 error peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
225 verbose exit [ 1, true ]
```
