### ISSUE TITLE
mdl-cell and 839px window

### ISSUE THREAD

**Issue by vhondarev** [google/material-design-lite#1810] opened 2015-10-24 23:58 UTC
When the size of body box-model is 839.2px it's crushes layout. Maybe it's bug or something else?
http://codepen.io/anon/pen/epMZZe

**Comment by Garbee** [comment] 2015-10-25 10:47
Demo seems to be working as expected here. 840px is the desktop breakpoint size, 839px is when it goes to tablet mode. This means due to the classes being used on these elements, the hidden block for spacing (1 cell on desktop) is hidden and the content gets resized as well.

Closing since it is working as intended. If you believe it still isn't working as it should, then please provide more details as to what the problem is and why you think it is an issue and we can re-open this.

**Closed by Garbee** 2015-10-25 10:47 UTC
