### ISSUE TITLE
adnroid-dot-com template fab button bug

### ISSUE THREAD

**Issue by jimbojetlag** [google/material-design-lite#1884] opened 2015-11-14 05:53 UTC
1. Visit http://www.getmdl.io/templates/android-dot-com/index.html
2. Scroll down and click on this fab button: 

![image](https://cloud.githubusercontent.com/assets/11205806/11162292/c5f53af0-8a93-11e5-985a-068c0c68dd28.png)
3. Now scroll up. At least in chrome, you'll get an infinite scroll up.

**Comment by Garbee** [comment] 2015-11-15 14:34
What version of Chrome are you using? On Version 48.0.2564.0 canary (64-bit) the problem isn't present. Looks like an issue internal to Chrome (as we have also had a similar problem with the doc links.) As such, closing this issue out since there is nothing we can do about it, but providing affected versions would be helpful for future searchers.

**Closed by Garbee** 2015-11-15 14:34 UTC

**Comment by jimbojetlag** [comment] 2015-11-16 19:03
You are right, upgrading to the recent version 46.0.2490.86 (64-bit) resolved the problem.
