### ISSUE TITLE
Scroll position not "remembered" when you go back

### ISSUE THREAD

**Issue by Sam-Hepworth** [google/material-design-lite#1740] opened 2015-10-13 20:01 UTC
On many (if not all) of the the MDL example pages the scroll position is not "remembered" when you go back to a previous page. The expected behavior is that the scroll position is "remembered" when you go back to a page.

**Comment by Garbee** [comment] 2015-10-13 20:03
Duplicate of #1120

**Closed by Garbee** 2015-10-13 20:03 UTC
