### ISSUE TITLE
the anchor don't work properly

### ISSUE THREAD

**Issue by psychoss** [google/material-design-lite#1797] opened 2015-10-23 07:36 UTC
when click a link, at first, that work fine, just skip to the cotent indicted by id. but when  click anthor link , it located at the same element as the previous, the window location hash do not  change as well. however, everything was work fine if used the Opera Browser。is that the Chrome Browser's problem，or something of material design lite i was not well understand. here is the page "http://www.mean101.com/css-wonderful-resource" hope you guys help me. sorry the english is not my mother language. i have tried the best to describe the problem i encountered.

update issue: if remove the "mdl-js-layout" classname,everything work fine.
i'd written a simple code as a makeshift solution , to instead of the "layout.js", but still want to knew, where is the problem.

```javascript
    var drawerButton = document.querySelector('.layout__drawer-button');
    var drawer = document.querySelector('.layout__drawer');
    var obfuscator = document.body.appendChild(document.createElement('div'));
    obfuscator.className = "layout__obfuscator"

    var toggleDrawer = function() {
        if (drawer.classList.contains('is-visible')) {
            drawer.classList.remove('is-visible')
            obfuscator.classList.remove('is-visible')
        } else {
            drawer.classList.add('is-visible')
            obfuscator.classList.add('is-visible')
        }
    }
    obfuscator.onclick = toggleDrawer;
    drawerButton.onclick = toggleDrawer;
```

**Comment by Garbee** [comment] 2015-10-24 10:16
So what exactly are the steps to reproduce the issue? Looks like you are keeping the "fix" you found on that site, which means we can't see the problem. Please provide a full working example and steps to reproduce the problem.

**Comment by psychoss** [comment] 2015-10-26 03:39
thanks for your response
the original page have been changed so much, it takes a little hard work to restore the problem 。

this page of “http://mean101.com/some-issue.html” is much like as.

please click the links of the page like some  show in the follow picture, 

![123](https://cloud.githubusercontent.com/assets/5614729/10720295/cd65a356-7b6b-11e5-94ac-1a8145812948.png)

**Comment by Garbee** [comment] 2015-10-26 11:51
I still can't  reproduce the issue in `48.0.2541.0 (Official Build) dev (64-bit)`. I click on a link, hash changes and I'm taken to that section. Scroll up and click on same link, go back to that section with same hash. Scroll up and click different link, hash changes and page goes to that section.

All seems to be working fine, maybe there is  an addon or bug in the specific build you have causing the issue. Closing this since it isn't reproducable. Can re-open if exact steps to reproduce can be provided with a demo that displays the issue.

**Closed by Garbee** 2015-10-26 11:51 UTC
Labels: Layout, pending-reproducible-sample
