### ISSUE TITLE
Ripple Effect is Broken in Opera Browser

### ISSUE THREAD

**Issue by Reubend** [google/material-design-lite#1153] opened 2015-07-21 19:32 UTC
![broken](https://cloud.githubusercontent.com/assets/13208038/8810437/f0100798-2fa3-11e5-8d39-b3a6a813b7ba.gif)

Components that use the ripple effect do not render properly in the latest stable version of the Opera  browser. In particular, button and checkboxes that use it seem to be broken.

**Comment by surma** [comment] 2015-07-22 10:55
Duplicate of #816. This is a bug in Opera. We will talk to them about this (it was working in Opera 29).

**Closed by surma** 2015-07-22 10:55 UTC
