### ISSUE TITLE
DoubleClick for publishers is not working with mdl javascript

### ISSUE THREAD

**Issue by Lidofernandez** [google/material-design-lite#4303] opened 2016-04-25 13:23 UTC
Hi guys,

I've found that DFP only works when mdl-js is disabled. 

As you can see on this repo I've created: git@github.com:Lidofernandez/material-design-lite-and-dfp.git
The DFP ads works only during the time mdl-js is not loading.

I was using Bootstrap  so far and I was thinking to change to mdl using the web starter kit but I think that is not going to be possible if this issue is not solved :(

**Comment by mfonville** [comment] 2016-04-25 17:11
@Lidofernandez I had initially also some trouble with responsive adsense ads, but worked it out by delaying the adsense-loading after MDL has loaded.

**Comment by Lidofernandez** [comment] 2016-04-25 17:14
@mfonville that can be a nice solution. how should I do that? I mean when making the build in gulp is there any way I can manage that?

**Comment by mfonville** [comment] 2016-04-25 17:17
@Lidofernandez can't help you with gulp. But what I do at least for adsense is to call window.componentHandler.upgradeDom() before executing (and loading) adsense.

**Comment by Garbee** [comment] 2016-04-26 02:09
Duplicate of #1369.

**Closed by Garbee** 2016-04-26 02:09 UTC
