### ISSUE TITLE
Menus doesn't follow MD guidance

### ISSUE THREAD

**Issue by jfily** [google/material-design-lite#1848] opened 2015-11-05 15:51 UTC
Hi,

I 've found a mistake on menu positioning

As you can see : ![bug menus](https://cloud.githubusercontent.com/assets/10220170/10973267/f09a3a34-83dc-11e5-93c4-0b56583b2f68.gif), menus are positioned exactly like MD specs said not to do.

![capture](https://cloud.githubusercontent.com/assets/10220170/10973329/437a15f8-83dd-11e5-9157-57443fe051d5.PNG)

Menu must overlap the button.

**Comment by surma** [comment] 2015-11-05 15:52
Nice catch. That seems to be a valid issue.

**Comment by The4thLaw** [comment] 2015-11-23 17:06
I just noticed that official websites like GMail, Drive, Calendar and the new Google+ display menus below the emitting element (the mobile applications indeed position the menus over it).

*Google+:*
![image](https://cloud.githubusercontent.com/assets/12219265/11343415/3cdb30b4-920c-11e5-8af3-55f7d08beb14.png)

*GMail:*
![image](https://cloud.githubusercontent.com/assets/12219265/11343426/518f6390-920c-11e5-934d-491634cb132c.png)

(sorry for the French)

It might be worth checking with the material design team if they don't have an opinion on this. Maybe they have different guidelines for desktop applications?

**Comment by hebbet** [comment] 2015-11-23 17:07
Gmail doesn't use material design on desktop.

**Comment by Garbee** [comment] 2015-11-23 17:13
Inbox does, and it handles menus the same way. Either way, the spec is fine, web teams are currently just taking the easy route and not fully abiding by the spec.

**Comment by jfily** [comment] 2015-11-23 17:21
Inbox on Android handles menus the right way... But I guess it's a generic component available on Android SDK because I never saw menus like MDL on an Material Android app.

Seems like web devs are lazy :)

**Comment by The4thLaw** [comment] 2015-11-23 17:26
> Inbox does, and it handles menus the same way. Either way, the spec is fine, web teams are currently just taking the easy route and not fully abiding by the spec.

> Seems like web devs are lazy :)

That's what I thought as well. But it's weird that they would redesign all of Google+ and leave things behind.
Well, if you're not lazy, good for us :)

**Comment by Garbee** [comment] 2015-11-23 17:27
Not necessarily lazy. Design like this is pretty simple when you have complete control over display like on Android. With the web, our standards don't exactly make it easy to handle these things well. Especially using default views like select elements. So, just achieving MD can be quite the hack at times.

Doing the extra-mile of then making the menu align on top of the button, could end up causing quite the performance problem since you need to calculate the spacing and apply it dynamically. It could very well be the teams did the work, but the performance overhead was too great. We will need to implement it and test for ourselves whether it is performant enough (and worth the maintenance overhead) to have this in MDL core.

**Comment by The4thLaw** [comment] 2015-11-23 17:31
FYI, it's implemented according to the specs in the Paper elements for Polymer.

**Comment by Garbee** [comment] 2015-12-28 10:08
Changing the alignment here is going to be tricky to get done in a way that is performant. Pushing milestone back to 2.0 since that will allow us proper time (while  already refactoring menu quite a bit) to make sure the best work is provided here.

**Comment by Garbee** [comment] 2015-12-28 10:14
Duplicate of #1070.

**Closed by Garbee** 2015-12-28 10:14 UTC
Labels: MD Alignment, Menu

**Comment by oddui** [comment] 2016-01-05 04:04
@Garbee i don't understand why it is tricky to get done in a way that is performant. It seems as simple as +/- the emitting element's height to the existing position :grey_question:
