### ISSUE TITLE
Address bar doesn't scroll off screen on Chrome for Android

### ISSUE THREAD

**Issue by gauntface** [google/material-design-lite#1756] opened 2015-10-15 16:28 UTC
This was raised on WF.

I think this is because the layout is designed to take up 100% height of the viewport and scroll within that, meaning the body doesn't exceed it - or something along those lines.

https://github.com/google/WebFundamentals/issues/2110

**Comment by surma** [comment] 2015-10-15 16:28
Duplicate of #1072

**Closed by surma** 2015-10-15 16:28 UTC
