### ISSUE TITLE
[Component Request] {Dropdown}

### ISSUE THREAD

**Issue by onexerxes** [google/material-design-lite#1671] opened 2015-09-30 20:40 UTC
Can you please implement dropdowns similar to the Polymer ones?

https://elements.polymer-project.org/elements/paper-dropdown-menu?active=paper-dropdown-menu&view=demo:demo/index.html

**Comment by Garbee** [comment] 2015-10-01 01:14
Duplicate of select requests.

**Closed** 2015-10-01 01:14 UTC

**Comment by surma** [comment] 2015-10-01 08:58
See #854
