### ISSUE TITLE
js advertisement error onload complete

### ISSUE THREAD

**Issue by shlyahten** [google/material-design-lite#2081] opened 2015-12-26 10:07 UTC
I have a problem with advertising loading. After a page fully loads material.js runs and hide my iframe ad.

**Comment by Garbee** [comment] 2015-12-26 10:54
Duplicate of #1926

**Comment by Garbee** [comment] 2015-12-26 10:54
P.S. Maybe not *directly* duplicate, but same method to get it working.

**Closed by Garbee** 2015-12-26 10:54 UTC

**Comment by shlyahten** [comment] 2015-12-26 11:28
Ok, I'll try
