### ISSUE TITLE
Improper cards implementation

### ISSUE THREAD

**Issue by kybarg** [google/material-design-lite#935] opened 2015-07-10 07:33 UTC
http://www.getmdl.io/components/index.html#cards-section

According to MD specs, cards title followed by supporting text merges padding, but not in your examples. Moreover title block has an image as background but card's image is supposed to be content, not style element. I think such structure could be used only in "Image card". Thanks

**Comment by addyosmani** [comment] 2015-07-10 09:11
@santokii your input would be appreciated on this one.

**Comment by Garbee** [comment] 2015-07-10 10:43
> According to MD specs, cards title followed by supporting text merges padding, but not in your examples

Let's change that to "but not in your implementation". The rules for when padding changes in cards is hard to decipher in the first place. Even further, we can't support every combination of styles right now. It is something I'm looking to address in Cards V2. However, without level 4 CSS selectors it will still be an opinionated subset of card styling.

Supporting every possible combination would bloat the implementation up by an extreme amount. Something we can't do when trying to stay lite.

**Comment by santokii** [comment] 2015-07-10 12:50
Hi kybarg! And thanks for the feedback! The MD specs are intended to be modular "content blocks which can be combined to create visual hierarchy within a card". The specs show just a few combinations: "The following examples illustrate some possible combinations of content blocks."

But the main difference is that the current MD card specs are just for mobile. We intentionally created this example to be responsive for desktop, which has different parameters for the usage of vertical space. I hope this makes sense!

We are obviously still trying to accommodate for more common use cases, but please send out more examples where this is not a good user experience and we will do our best to respond!

Thanks!

**Comment by kybarg** [comment] 2015-07-10 19:19
It is ok as for example, and I believe mane people can find such implementation useful but I think it should be aimed to meet most developers needs. Cards as content blocks can be shop product items, blog posts etc. so image should be <code><img></code> tag to be visible for search engines (what is impossible when used as background). I noticed there is a variant with <code><img></code>, but it isn't illustrated and title element isn't placed above. Thanks)

**Comment by kybarg** [comment] 2015-07-10 19:25
There is Word Press theme with MDL and its cards are made strict to yours example, which isn't right IMHO) Again cause search engines don't see posts images.

**Comment by Garbee** [comment] 2015-07-10 19:50
Title can be inside of our outside of the media area. I do mine outside. and yes, an img/picture/video whatever within the media area directly is perfectly fine (one way it was built to be.) Should we just have more examples of different card structures? I don't want them to get bloated and take up too much space, but a few more may help get the point across that different structures are possible.

**Comment by Gheoan** [comment] 2015-07-10 21:45
+1 for more examples of cards. Cards represent data and data can be structured in many ways.

**Comment by kybarg** [comment] 2015-07-11 09:20
I think adding all card's elements described at MD specs would be nice, but their positioning variations can be done by developers according to their project needs)

**Comment by Garbee** [comment] 2015-07-11 13:12
All the card elements are present. They are just locked into one view each.
Where some have multiple configurations that you mix and match at will.

Now with the information that there is no defined reasons for when they
should be configured in a certain way compared to another, there is no
pragmatic way to handle that. You'd end up with bunches of modifiers that
will only get confusing.

Ideally we need to support horizontal cards by default in the future.
Beyond that and a few simpler card samples, I'm not sure what action can be
taken to resolve this.

We should however try to find actionable items for the specification team
to try and resolve the confusion.

I think adding all card's elements described at MD specs would be nice, but
their positioning variations can be done by developers according to their
project needs)

—
Reply to this email directly or view it on GitHub
<https://github.com/google/material-design-lite/issues/935#issuecomment-120598086>
.

**Comment by prakyg** [comment] 2015-07-12 06:31
Is there a way to implement horizontal cards with minimal modifications in the code?

**Comment by kybarg** [comment] 2015-07-12 07:56
@prakyg Have a look at [codepen](http://codepen.io/kybarg/pen/xGjBVX)

**Comment by prakyg** [comment] 2015-07-12 14:56
Thanks a lot @kybarg !!

**Comment by Garbee** [comment] 2015-07-12 15:22
That is one way to do it. However, for core implementation we shouldn't be adding new classes like the column element there. Core should be seamless between a standard and horizontal card with just the modifier to change state; at least so long as CSS allows for it which may be troublesome without new selectors.

**Comment by kybarg** [comment] 2015-07-12 16:51
@prakyg, There is new better example http://codepen.io/kybarg/pen/rVvgag
@Garbee  You are 100% right. Have a look at new codepen, had some time "to play cards") Have some issues in IE.

**Comment by Garbee** [comment] 2015-07-12 16:54
> Have some issues in IE.

Story of our lives.

**Comment by kybarg** [comment] 2015-07-12 17:17
@Garbee You may not believe me, but I've managed to get it work even in IE9 except vertical stretch

**Comment by cliffordp** [comment] 2015-08-12 15:27
From memory, the only thing I didn't see in any of the card examples was **subtitle**. When I played with it, I couldn't figure out where it really should belong because it never looked good.

**Comment by simonjamain** [comment] 2015-12-07 14:33
Hi there, I stumbled on this while trying to put horizontal cards on my website and I post my solution for people looking for a workaround.

The problem is that the images I want to put in the card are not always the same size, and more important : the text lenght is not always the same so my cards vary in heights.
The best I came with is with tables : http://codepen.io/anon/pen/yeyOzR 

I prefer that to the other workaround because the image is in a background instead of an img kinda like "vertical" cards in MDL, and of course because height is not fixed.

**Comment by Garbee** [comment] 2015-12-25 10:47
Closing this issue on out. Our implementation is perfectly valid (aside from subtitle right now) and the reasons with which you would modify padding is entirely up to developers. Further, the image issues are not relevant. We use background images as examples since the images are not primary content for our demos. You are free to add images into the media area, or videos or whatever. Developers simply need to account for responsiveness on their own in doing so.

V2 may introduce more configurations by default, but overall trying to implement every combination of the spec internally by default is not useful or sustainable. It will lead to more bloat in the code as well as more docs which are not clear.

If developers wish to modify cards more deeply beyond what is provided by us as "sane defaults" (we hope) then it is on them in their own custom code to handle that and align to the spec.

**Closed by Garbee** 2015-12-25 10:47 UTC
Labels: Cards
