### ISSUE TITLE
Remove JS Requirement for Checkboxes

### ISSUE THREAD

**Issue by srsgores** [google/material-design-lite#2001] opened 2015-12-11 22:37 UTC
It can [easily be done without JS](http://codepen.io/srsgores/pen/objbpq), so let's simplify, is my suggestion.

**Comment by Garbee** [comment] 2015-12-12 01:30
Duplicate of another issue. We know it is doable. Our current setup is for IE9 support. Fixing in 2.0 when we drop that browser.

**Closed by Garbee** 2015-12-12 01:30 UTC
