### ISSUE TITLE
No way to close menus

### ISSUE THREAD

**Issue by chrsmith** [google/material-design-lite#4098] opened 2016-02-10 19:16 UTC
Clicking the "hamburger button" opens up a menu. However, that menu seems to have no way of being dismissed. This definitely causes a problem for easy site navigation.

Am I missing something? Is there a way to put an 'x' icon? Or perhaps bind the escape key to close it? Is this a bug/oversight in design? Or by design?

http://www.getmdl.io/components/#layout-section

**Comment by Sungodragon** [comment] 2016-02-10 19:28
We have put a button to close menu. ( in our project)
Also by clicking outside menu one can close it.
It was discussed in past.

**Comment by rtarnec** [comment] 2016-02-10 22:36
Hi, there are few discussions on StackOverflow on this topic:
http://stackoverflow.com/questions/33705796/closing-layout-drawer
http://stackoverflow.com/questions/31616145/how-to-hide-an-open-drawer-in-material-design-lite
http://stackoverflow.com/questions/31536467/how-to-hide-drawer-upon-user-click

**Comment by chrsmith** [comment] 2016-02-12 22:21
Thank you for the response, and sorry for not finding those SO posts on my own :grimacing: .

**Closed** 2016-02-15 08:19 UTC

**Comment by chrsmith** [comment] 2016-02-16 15:54
@surma are you sure that this isn't something you want to fix in Material Design Lite? The fact that many other people ran into the same problem I did, and there are multiple posts on SO indicate the following. (To me at least.)

1. Being able to close menus is something people want to do. Why is this not the default behavior?
1. It isn't clear how to do it. Perhaps the documentation should include a snippet for how to make menus disposable?

Having this closed issue at least adds another artifact some Googling could find, but I'd still urge you to make the appropriate changes to the libraries and/or documentation.

**Comment by Zodiase** [comment] 2016-02-16 16:50
The MD specs here describes the behavior of the temporary navigation drawer (that this library implements): https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-behavior (scroll down to the "Temporary" section)

Quote: 
> Closed by default, the drawer opens temporarily above all other content until a section is selected.

With that, by design the drawer should not have a close button.

What you want to ask perhaps is MDL implementing the "persistent" drawer which should have a close button.
