### ISSUE TITLE
Hash tag link causing scroll issues in Android

### ISSUE THREAD

**Issue by ccarsona** [google/material-design-lite#1900] opened 2015-11-22 22:59 UTC
This is in relation to Waterfall header first row not visible on narrow screen #1791 (closed). Specifically, sgomes response:
"Thanks for the feedback, @alextekartik! If you want the behaviour you're describing, just add the mdl-layout--fixed-header class to your mdl-layout element, which should make sure it's always visible, including in mobile."

Unfortunately, this breaks in Android phone if you use a hash tag link on the page. If you click a link, scrolling up fails to stop at the header row (infinite scrolling) - if you scroll back to the top. Example below - click one of the links (About or Services), then scroll back to the top - it keeps scrolling and scrolling. Example below:
http://www.mobotic.com/mld/bug.html

Is there a way to fix this?

**Comment by Garbee** [comment] 2015-11-23 00:15
Can you please provide clear reproduction steps and the browser + version you are using?

There is a bug in Chrome that caused infinite scroll problems, not only with MDL but across a few things. Should be fixed in the latest stable or Beta at the moment.

**Comment by ccarsona** [comment] 2015-11-23 00:33
Thanks. Chrome 46.0.2400.76  Android 5.0.2.
Not 100% I know what reproduction steps are. Using Chrome, go to the referenced link and click either the About or Service hash tag link, then scroll up the page to the header row - it just keeps going. I am simply using the Waterfall Layout. The only alteration from how it's is presented at:
http://www.getmdl.io/components/index.html#layout-section
... is the addition of the fixed-header class as noted above. It's a very simple demo: http://www.mobotic.com/mld/bug.html

Thanks for you feedback, BTW.

**Comment by Garbee** [comment] 2015-11-23 00:47
Yup, I can replicate. It at least scrolls back around a few times for me before doing a refresh. Probably a side-effect of how our layout JS is working.

Marking as a layout bug, but due to Layout being completely reworked after 1.1 it is a low priority.

**Comment by clocksmith** [comment] 2015-11-23 17:42
This happens on Chrome for Mac OSX as well. It is incredibly frustrating because it happens on the main http://www.getmdl.io/ site while I am trying to learn...

**Comment by Garbee** [comment] 2015-11-23 18:02
If it is on the main site, it is the chrome bug.

**Comment by samccone** [comment] 2015-11-24 00:15
@Garbee do you have a link to the crbug for tracking?

**Comment by Garbee** [comment] 2015-11-24 00:43
Nope. Hardly going to find it, it is long closed since it has been fixed in Canary for quite a while. Opening a new one won't do any good, except get closed as "Fixed in ToT, wait for new stable".

Cross-talk from issue #1902. Which based on that and this discussion, closing this out as an upstream Chrome bug.

@surma, @sgomes, and @addyosmani: Any of you have a link to the crbug issue about the hashes in URLs causing wackyness? I recall it coming up before and one of you mentioning filing an upstream bug again for the regression.

**Closed by Garbee** 2015-11-24 00:43 UTC
Labels: bug, confirmed, Layout
