### ISSUE TITLE
window scroll js Conflict

### ISSUE THREAD

**Issue by caliven** [google/material-design-lite#1620] opened 2015-09-19 07:32 UTC
Custom 
window.onscroll = function(){
    //...
}
When you scroll is invalid over，I think this is a conflict and material.js

**Comment by Garbee** [comment] 2015-09-19 14:43
Can you provide a codepen that reproduces the issue for us? What has been provided so far doesn't make much sense as to what the problem is.

**Comment by surma** [comment] 2015-09-20 00:29
If you use the layout component, this might not be working as expected as it is not `window` that is scrolling but the content div. Does this help?

**Comment by liuzhihuil** [comment] 2015-09-21 02:45
@Garbee I joined the blog template "index.html" page code 
"window.onscroll = function () {
         console.log (1);
 } "  Is invalid, when I remove the "material.min.js", code ok.

![scroll](https://cloud.githubusercontent.com/assets/1018916/9984618/ceccd554-604d-11e5-8db4-90355947b406.png)

**Comment by surma** [comment] 2015-09-21 09:36
@liuzhihuil Sadly, you removed a crucial part from your snippet: Are you using the MDL layout component? If so, window is not scrolling, but the `.mdl-layout--content` is.

**Comment by Garbee** [comment] 2016-01-27 16:11
As Surma stated, window doesn't scroll using the layout component but our custom content node. Verify you are checking for scroll on that.

Closing due to not having a reproducible sample for further triage.

**Closed by Garbee** 2016-01-27 16:11 UTC
Labels: pending-reproducible-sample
