### ISSUE TITLE
Checkbox and radio offsets

### ISSUE THREAD

**Issue by jdepypere** [google/material-design-lite#1217] opened 2015-07-26 18:56 UTC
**Note**: This is based on a printscreen on my devices, both on my pc and on my Nexus 5.

So this is done on the basic components site of getmdl.io. First off, the checkboxes are a bit off center compared to the ripple:
![checkboxcloseup](https://cloud.githubusercontent.com/assets/3522063/8895357/e0238a66-33d7-11e5-8c57-5575a5bda839.png)

![checkboxn5closeup](https://cloud.githubusercontent.com/assets/3522063/8895375/c36b228e-33d8-11e5-9212-aa25eb4c878a.PNG)

For the radio button:
![radiocloseup](https://cloud.githubusercontent.com/assets/3522063/8895358/f342bdc4-33d7-11e5-8255-c45d976fd23b.PNG)

![radion5closeup](https://cloud.githubusercontent.com/assets/3522063/8895377/c99ebe36-33d8-11e5-8bb2-0141bace9e75.PNG)

Comparing it to the [radios](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3cEVOUmMwZ05tU00/components_switches_radio3.png) and [checkboxes](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3cFp4WHdDaWZESmM/components_switches_check3.png) from the material design spec it looks like it isn't meant to be off-center.

**Comment by kybarg** [comment] 2015-07-26 18:59
Duplicate of #964

**Comment by addyosmani** [comment] 2015-07-27 07:59
Merging into #964. Thanks @kybarg!

**Closed by addyosmani** 2015-07-27 07:59 UTC
