### ISSUE TITLE
Text Field issue

### ISSUE THREAD

**Issue by mrfaizanhaider** [google/material-design-lite#1559] opened 2015-09-07 10:34 UTC
there is just browser-default select option available for TEXT FILEDs.

there is any soloution for material select option??

**Comment by surma** [comment] 2015-09-07 13:13
Duplicate of #854. We don’t have anything for select fields in MDL yet, sadly.

**Closed by surma** 2015-09-07 13:13 UTC

**Comment by mrfaizanhaider** [comment] 2015-09-08 11:25
so what about future???

**Comment by surma** [comment] 2015-09-08 11:48
@mrfaizanhaider Please read the issue #854 I linked to. We will implement select fields.
