### ISSUE TITLE
Adding a fixed draw adds to much padding to the left of the header

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#1078] opened 2015-07-17 01:18 UTC
In the [layout documentation](http://www.getmdl.io/components/index.html#layout-section) there's an example for "Fixed header and draw". [Here's the same example](http://codepen.io/anon/pen/gpjwYN) with a title added, you'll notice the title is aligned to far to the right, this is because 80px of padding gets added to mdl-layout__header-row which is usually okay because mdl-layout__drawer-button fills that space. But on the fixed draw the menu button is hidden leaving this extra space.

For anyone looking for a quick fix:
```
@media screen and (min-width: 851px) {
  .mdl-layout__header-row {
    padding: 0 40px 0 40px;
  }
}
```

**Comment by patrick-jones** [comment] 2015-07-22 12:07
This is related to #1032

**Comment by Garbee** [comment] 2015-07-22 12:08
Duplicate of #1032. Good catch @patrick-jones.

**Closed by Garbee** 2015-07-22 12:08 UTC
Labels: enhancement, Layout
