### ISSUE TITLE
 the [mdl-layout__drawer-button] icon not aligning correctly

### ISSUE THREAD

**Issue by vose2008** [google/material-design-lite#1661] opened 2015-09-29 12:55 UTC
this is run in [CODE PEN](https://codepen.io/pen)
and this is run in [RUNJS](http://runjs.cn/code/sg5zbjg0)
and the last one is run in Chrome 45.0.2454.99 (64-bit)
![1856cfd1-b196-4ad1-b047-00a8f0dab8fb](https://cloud.githubusercontent.com/assets/3043219/10164362/c249b9ce-66eb-11e5-8527-7093c08bcfec.png)

it's seem like about line-height

sorry about my poor english skill

**Comment by addyosmani** [comment] 2015-09-29 12:59
Thanks for your bug report. What OS are you experiencing this on? On Mac / Chrome 45 + 46 I'm seeing this:

![](http://i.imgur.com/2EC7JOc.png)

**Comment by vose2008** [comment] 2015-09-29 13:01
ye on Mac 10.10.5 / Chrome 45.0.2454.99 (64-bit)

**Comment by addyosmani** [comment] 2015-09-29 13:05
@sgomes or @surma can you try reproducing on your machines?

**Comment by sgomes** [comment] 2015-09-29 14:03
I'm having trouble with the links in the original issue, @addyosmani. How did you get to the preview?

**Comment by addyosmani** [comment] 2015-09-29 14:04
I used the second link. The first Codepen is busted :)

**Comment by sgomes** [comment] 2015-09-30 14:25
The exact same code causes no issues in codepen. I'm currently investigating why, but I'd say the problem is something to do with runjs.cn

**Comment by surma** [comment] 2015-09-30 14:38
RunJS looks completely busted for me:
<img width="591" alt="screenshot 2015-09-30 16 37 38" src="https://cloud.githubusercontent.com/assets/234957/10196142/9de5fa24-6791-11e5-8148-cb524c729ba2.png">

**Comment by sgomes** [comment] 2015-09-30 14:41
I see the same issues across all browsers in RunJS. I'm closing the bug because it seems apparent it's an issue with the site.

**Closed by sgomes** 2015-09-30 14:41 UTC
Labels: Layout

**Comment by vose2008** [comment] 2015-09-30 16:31
guys it's my fault, i apologize for the LINK about CodePen, in fact CodePen are working fine, but not work well on my own project and RUNJS. The other platform i didn't test.
1. [CodePen here again](https://codepen.io/anon/pen/OyWzKK)
2. And actually the problem with @sgomes & @surma on RunJS.cn maybe because of the GFW ( china great fire wall ) , it may let some resources can't loading . Thus your can't see the right page preview, except layout problem like my picture. ( i guess... )
3. Last the problem of my commented. the code was i write or copy form MDL all of them have same problem likes my picture.

thanks all of you in any way

**Comment by vose2008** [comment] 2015-09-30 16:35
closed .... but ..... but ... the picture are cut of form Chrome.
sadly face ( TAT )

**Comment by mwatanabe** [comment] 2015-10-29 18:09
I had same trouble on Mac Chrome 46. I had done 2 steps and found it.
1. copy the source from [reference](http://www.getmdl.io/components/index.html#layout-section/layout)
2. open it on Chrome.
It seems that the line-height of "mdl-layout__drawer-button"(50px) doesn't affect for calculating vertical-align of "material-icons".
I found work around that adding style in linked css as follows.
```
.mdl-layout__drawer-button:before {
    content: '';
}
```
sorry about my poor english skill too!

**Comment by vose2008** [comment] 2015-11-04 12:36
YES, i run my local project and in RUNJS both have same problem, but sgomes think it's RUNJS's is borken not MDL's problem, So he close this issues. i suggested that, build a new issue and link it to this issue. the present situation we were subject to,i completely think it is a bug.
是的呀，我本地测试和在runjs 上测试都是错了的，但sgomes 单单看了我runjs 上的例子就认为是 runjs 的问题... 所以呐，我建议你再开一个 issue 附带我这个链接，证明我们俩遇到了同样地问题。

**Comment by chibicode** [comment] 2015-11-10 17:27
This was an issue for me and @mwatanabe's workaround solved it for me.

**Comment by aderbas** [comment] 2016-09-05 21:07
I have this problem here today. So I decided to revive the topic.
![icon_mdl_fail](https://cloud.githubusercontent.com/assets/12519019/18257000/54464e64-7393-11e6-9c67-d078188bf1de.png)

It's funny because it happens to the customizer.

![icon_mdl_fail2](https://cloud.githubusercontent.com/assets/12519019/18257003/6a0c0b1c-7393-11e6-9053-39f46670bb45.png)

Ubuntu 14.04 / Chrome 49.0.2623.75 (64-bit)

**Comment by sgomes** [comment] 2016-09-09 07:14
Fixed in 1.2.1

**Comment by chaficnajjar** [comment] 2016-10-30 14:37
I was experiencing exactly the same issue as the OP. Turns out I was missing `<!doctype html>`.

**Comment by leonardoporro** [comment] 2016-12-16 23:38
<!doctype html> fixed my issue too.
CSS is the devil...
Thanks for sharing.
