### ISSUE TITLE
MAC OSX Chrome 50.0.2661.102 (64-bit)  TABLE RENDER

### ISSUE THREAD

**Issue by coladou** [google/material-design-lite#4365] opened 2016-05-20 06:52 UTC
<img width="1021" alt="2016-05-20 14 51 22" src="https://cloud.githubusercontent.com/assets/6190552/15419692/7656d404-1e9a-11e6-9ece-d2c46da0713c.png">

**Comment by coladou** [comment] 2016-05-20 06:53
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.blue-indigo.min.css">
    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>

**Comment by Garbee** [comment] 2016-05-20 10:13
Duplicate of #4325

**Closed by Garbee** 2016-05-20 10:13 UTC
