### ISSUE TITLE
MDL Button animations do not trigger upon "tapping" on MacBookPro touchpad

### ISSUE THREAD

**Issue by nicolasgarnier** [google/material-design-lite#376] opened 2015-06-10 22:47 UTC
The animations applied to an MDL Button such as "raised button" or the ripple do not trigger when I simply "tap" on my MacBookPro touchpad.

Animations are triggered correctly when I do a "physical" click.

To test this you need to enable the "tap to click" option on the Trackpad's menu in System preferences. Then just "tap" your trackpad instead of doing a click.

**Comment by addyosmani** [comment] 2015-07-10 09:10
I was quite sure we'd fixed this issue but forgot to close. @surma can you verify?

**Comment by surma** [comment] 2015-07-10 09:53
@addyosmani Nope. This bug is still present. I spent a good amount of time trying to figure out why this behaves this way. All the events are still being properly dispatched.

**Comment by cnyyk** [comment] 2015-07-10 13:28
Agree with @surma . I tested it this afternoon. No ripple when tap.

**Comment by Garbee** [comment] 2015-07-11 17:13
Also FYI, I just tested this on a Windows 7 machine with a touchscreen under IE 11 and the ripples don't show under this either. However they do work via click.

**Comment by DsXack** [comment] 2015-07-28 15:57
Milestone is closed. This bug will be fixed?

**Comment by Garbee** [comment] 2015-07-28 16:41
The issue isn't fixed so there is no reason for it to be closed. The milestone was an aim-for thing, but since it was P1 it was fine to launch without fixing the issue.

**Comment by DsXack** [comment] 2015-09-16 05:20
This issue is not fixed – when I "tap" on my MacBook Air touchpad I have not ripple effect

**Comment by surma** [comment] 2015-09-20 00:07
Sadly, I can confirm :(

**Comment by sompylasar** [comment] 2015-09-22 21:30
I can confirm regardless of the "Tap-to-Click" touchpad setting. The ripple animation does not work at all for me.
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36`

`IS_VISIBLE` class [gets removed](https://github.com/google/material-design-lite/blob/master/src/ripple/ripple.js#L124) on `blur` event which happens before `mousedown`. Looks like this is the cause, but I'm not sure. Hope this helps a bit.

**Comment by sompylasar** [comment] 2015-09-22 21:39
This looks like a merge error. The file from the referenced PR (#1616) contains only the `setTimeout`-wrapped `classList.remove`, but the code from `master` [contains both](https://github.com/google/material-design-lite/blob/master/src/ripple/ripple.js#L125).

Here's the commit that introduces the bug: https://github.com/google/material-design-lite/commit/bea502c9a87da4f9e0798818f5370b1d12a8f576#diff-9cbbd68311a8bf9645ae1a80a5abef78

```js
MaterialRipple.prototype.upHandler_ = function(event) {
  'use strict';

  // Don't fire for the artificial "mouseup" generated by a double-click.
  if (event && event.detail !== 2) {
    // Allow a repaint to occur before removing this class, so the animation
    // shows for tap events, which seem to trigger a mouseup too soon after
    // mousedown.
    window.setTimeout(function() {
      this.rippleElement_.classList.remove(this.CssClasses_.IS_VISIBLE);
    }.bind(this), 0);
  }
};
```

```js
  MaterialRipple.prototype.upHandler_ = function(event) {
    // Don't fire for the artificial "mouseup" generated by a double-click.
    if (event && event.detail !== 2) {
      this.rippleElement_.classList.remove(this.CssClasses_.IS_VISIBLE);
    }
    // Allow a repaint to occur before removing this class, so the animation
    // shows for tap events, which seem to trigger a mouseup too soon after
    // mousedown.
    window.setTimeout(function() {
      this.rippleElement_.classList.remove(this.CssClasses_.IS_VISIBLE);
    }.bind(this), 0);
  };
```

**Comment by sompylasar** [comment] 2015-09-22 21:54
The buggy `focus` event [described above](https://github.com/google/material-design-lite/issues/376#issuecomment-142428620) does not happen in the [Layout with Tabs example](http://www.getmdl.io/components/index.html#layout-section), so the ripple appears when I click the tabs (tapping the MacBook touchpad with "Tap-to-Click" enabled still does not result in a ripple, reason unknown).

**Comment by addyosmani** [comment] 2015-09-24 12:02
I don't think we'll have a chance to look/patch this before Monday (1.0.5) so moving into the 1.1 milestone. Also bumping prio to p0.

**Comment by johnpapa** [comment] 2016-01-09 16:35
any update on this?

**Comment by surma** [comment] 2016-01-10 17:02
I had looked into this a while ago but can’t say I made any progress. For now, we are focusing on 1.1, but we will get back to this.

**Comment by Garbee** [comment] 2016-01-10 17:54
PR #2380 is open to address this. iirc @sgomes is working on reviewing it, but due to ripples being so integrated across the components it is time consuming.

**Comment by sgomes** [comment] 2016-01-11 16:40
This should now be fixed. If anyone else can give this a second round of testing for sanity's sake, I'd appreciate it!

**Closed by sgomes** 2016-01-11 16:40 UTC
Labels: bug, Button, confirmed, P0

**Comment by DsXack** [comment] 2016-01-21 12:58
Thank you! wait for the next release!

**Comment by akotlar** [comment] 2016-02-01 04:03
This did not fix the issue for me. Not certain if my using this within an Angular app has anything to do with it.

**Comment by surma** [comment] 2016-02-01 04:06
@akotlar It’s not been released yet. Unless you build you own version from the master branch, you won’t have the fix until we push v1.1 out :)

**Comment by akotlar** [comment] 2016-02-02 23:45
@surma. I should have stayed that the #2380 commit did not address it. Apologies if that does not contain the full fix! Briefly, I'm still noticing a canceled animation coincident with the firing of a short interval mouseup event. Could confound: using FastClick library. Setting a timeout > 0 helps, but is an inelegant solution. Very interested to hear you perspective on the issue fix, trying to learn as much as I can :)

**Comment by Garbee** [comment] 2016-02-03 09:03
> Could confound: using FastClick library.

Have you tried without FastClick? We can't plug in hotfixes for any given library on the net conflicting with what we provide.

**Comment by lancebeaudry** [comment] 2016-04-12 18:29
Is there any update on this issue? A workaround?

**Comment by sgomes** [comment] 2016-04-13 10:25
@lancebeaudry As far as we know, this is working correctly, and the latest issue pointed out by @akotlar could be due to FastClick. If anyone's able to provide a test case that shows the bug, we'll be happy to investigate further.

**Comment by lancebeaudry** [comment] 2016-04-13 14:13
@sgomes I've got a mdl template on Wordpress here:
http://wordpressmaterial.com/ and the hover state doesn't work as the touch state on mobile devices. See the drawer for an example.

**Comment by thumarmahesh** [comment] 2016-06-26 05:31
Was this ever fixed?

**Comment by akotlar** [comment] 2016-06-26 16:48
I have a fix for it, will post today if possible.

**Comment by akotlar** [comment] 2016-06-26 18:00
Here is the fix https://github.com/google/material-design-lite/pull/4454

[Plnk](http://plnkr.co/edit/p1T5fRDDPbqnhKfyk0Ky?p=info)
[Youtube Demo]( https://youtu.be/kyUK9N-1wA8)
