### ISSUE TITLE
The animation on tabs is wrong

### ISSUE THREAD

**Issue by tleunen** [google/material-design-lite#1335] opened 2015-08-07 23:17 UTC
Sometimes (quite often actually), the animation on the tab bar is not correct. Most the the times, the blue underline appear, quickly disappear and re-appear with the animation.

![tabs](https://cloud.githubusercontent.com/assets/1972567/9147697/ad228332-3d38-11e5-92e4-422775d3216b.gif)

**Comment by christophwolff** [comment] 2015-08-08 07:19
Duplicate [#954](https://github.com/google/material-design-lite/issues/)

**Comment by filippomartini** [comment] 2015-08-08 10:23
https://github.com/google/material-design-lite/issues/954

**Comment by tleunen** [comment] 2015-08-08 11:00
Damn I searched before but could not find any issue of it...
Thanks!
Anyway, the other ticket suggests to refactor the anim to match the "siblings anim" in the spec (which I agree).

**Comment by Garbee** [comment] 2015-08-08 13:49
Closing as duplicate of #954.

**Comment by zcyzcy88** [comment] 2017-02-23 08:24
I write more detail to express OP's mind

### What are the steps to reproduce the bug? What is the actual behavior?

This is the slow down GIF:
![demo](https://cloud.githubusercontent.com/assets/15178410/23249453/71739e56-f9df-11e6-9fcb-745af6872628.gif)

1. Mouse up, wait the browser react
2. The underline showed suddenly 
3. The underline animating 

### What is the expected behavior?
When I mouse up, The underline start to animate immediately, no showed suddenly

### Any other information you believe would be useful?
There is a 0.01s delay in CSS, write by #311
><img width="345" alt="css_code" src="https://cloud.githubusercontent.com/assets/15178410/23250520/7e1fc274-f9e4-11e6-9aaa-80c59815555f.png">

**Comment by Garbee** [comment] 2017-02-23 15:11
Oh wow, the gif slowdown makes it much clearer as to what is happening. I thought this was just an issue about it not being by-the-spec example animation. Thanks for that @zcyzcy88.

**Closed** 2017-02-24 15:45 UTC
