### ISSUE TITLE
Grid nesting does not work

### ISSUE THREAD

**Issue by akabhirav** [google/material-design-lite#4252] opened 2016-04-06 16:04 UTC
Grid can not be nested

**Comment by Garbee** [comment] 2016-04-06 18:18
Can you please provide a [codepen](https://codepen.io) that shows a reproduction of the issue?

When providing feedback to projects, reproduction cases and clear descriptions of what is expected and what is happening instead is very much appreciated. Otherwise making something actionable out of the ticket becomes a problematic process.

Thank you.

**Comment by Garbee** [comment] 2016-07-15 18:34
Closing since we don't have a reproduction case.

**Closed by Garbee** 2016-07-15 18:34 UTC
