### ISSUE TITLE
Dashboard template 'mdl-menu__container' style issue. 

### ISSUE THREAD

**Issue by foo-baar** [google/material-design-lite#1336] opened 2015-08-08 16:28 UTC
Once you click the down arrow next to "hello@example.com" inside the drawer, the links container that it over shadows while shown stops working after its hidden, "Home, Inbox" links on drawer are now unresponsive, if you bring mouse to the border on right side of drawer then it works.

**Comment by SeanBannister** [comment] 2015-08-08 18:07
Cheers, looks like that ones already reported, #1025 was also mentioned in #1290

**Comment by surma** [comment] 2015-08-08 18:47
Yup, @SeanBannister is right, duplicate of #1025. Thanks for reporting, though :)

**Closed by surma** 2015-08-08 18:47 UTC

**Comment by foo-baar** [comment] 2015-08-09 05:02
Thanks @surma & @SeanBannister, keep up good work on MDL and documentation/Demo would be helpful.
