### ISSUE TITLE
Two scroll bars appear when big menu used.

### ISSUE THREAD

**Issue by Bilchenko** [google/material-design-lite#1928] opened 2015-12-03 14:21 UTC
When mdl-menu has bigger height that screen, Two scroll bars appear.
You can see that on http://codepen.io/anon/pen/MKgLGN  (Button with more_vert in Right Top shows menu)
Maybe need set width and height to 0 for mdl-menu__container after menu close. Or use display: none for hide menu instead of visibility: hidden.

version 1.0.6

**Comment by surma** [comment] 2015-12-03 14:53
Yeah, sorry about that :confused: Effectively a duplicate of #1356, will be addressed with #1735.

**Closed by surma** 2015-12-03 14:53 UTC

**Comment by Garbee** [comment] 2015-12-03 14:57
@surma We could set a max-height to the menus so they can only get so big before scrolling takes effect. However, in the current situation it would require a hard-coded max-height value, since 100% would be the current buggy behavior.
