### ISSUE TITLE
On scroll it doesn't hide / minimize the browser address bar on phones

### ISSUE THREAD

**Issue by zsolt247** [google/material-design-lite#4154] opened 2016-02-24 16:29 UTC
When scrolling the content on both iOS Safari and Chrome for Androind browsers it doesn't enable the minimal-ui or hide the address bar.

**Comment by Garbee** [comment] 2016-02-24 17:01
Thanks for the report.

This has come up numerous times in the past. We know it is a problem and it is going to be fixed with a complete layout component refactor in 2.x. Nothing can be done in 1.x for it internally.

Issue #1072 is the original issue, please **subscribe** to that issue for updates.

**Closed by Garbee** 2016-02-24 17:01 UTC

**Comment by kiril6** [comment] 2017-05-03 11:40
Hello i have found this problem too. I am using MDL in my project, any update for the issue is it being fixed i need this to work on iOS devices. Thanks.
