### ISSUE TITLE
Loading page shows error

### ISSUE THREAD

**Issue by kostonstyle** [google/material-design-lite#4913] opened 2016-11-15 06:06 UTC
Hi material team

I am using input as follow: 

```
<form action="#" style="margin-left: 20px;">
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="sample3" required>
        <label class="mdl-textfield__label" for="sample3">Username</label>
        <span class="mdl-textfield__error">Field is required.</span>
    </div>
</form>
```
as you can see the code above, the input field is marked as required and when I load the page, it shows me the error message even I did not touch the input field yet.  
![15-11-2016 07-02-40](https://cloud.githubusercontent.com/assets/701611/20294912/db840d58-ab01-11e6-8be0-7ec5c2d533d9.png)

How can I prevent the error message, when the field did not get touched? I am using material design lite 1.2.1.  

I found the following link [https://github.com/google/material-design-lite/issues/1502](url) that has the same problem as I mentioned above. There is a solution but could not find anywhere on the page.

Thanks

**Comment by Garbee** [comment] 2016-11-15 09:09
Duplicate of #1502

**Closed by Garbee** 2016-11-15 09:09 UTC

**Comment by kostonstyle** [comment] 2016-11-15 09:33
I know it is a duplicate, what is the solution?

**Comment by Garbee** [comment] 2016-11-15 10:00
There is no "solution" as what we are doing follows the HTML spec. In v2 we will either implement deeper manual validation to handle this setup or try to get the spec to change to align with what the web provides for desktop (since this *is* just standard HTML Validation constraints.)

As far as V1, developers are on their own to implement a work-around to this as we are currently just following the native web platform internally.

**Comment by kostonstyle** [comment] 2016-11-15 10:02
Thanks so much.
