### ISSUE TITLE
How detect click on checkbox inside datatable?

### ISSUE THREAD

**Issue by scandinave** [google/material-design-lite#1493] opened 2015-08-28 07:17 UTC
Is there a way to handle click on checkbox inside datatable? i use ember, and i don't know how i detect click on this checkbox.

**Comment by Garbee** [comment] 2015-08-28 09:56
Duplicate of #1210. 

In the future, please use StackOverflow for support and usage questions. Then file an issue here once there is a verified core problem that needs addressing.

**Closed by Garbee** 2015-08-28 09:56 UTC
