### ISSUE TITLE
top of checkboxes getting clipped

### ISSUE THREAD

**Issue by marcacohen** [google/material-design-lite#597] opened 2015-07-01 18:25 UTC
top of boxes not being rendered. 

html is 
`<label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-1">
  <input type="checkbox" id="checkbox-1" class="mdl-checkbox__input" checked />
  <span class="mdl-checkbox__label">Checkbox</span>
</label>`

rendered version looks like this:
![screen shot 2015-07-01 at 7 02 28 pm](https://cloud.githubusercontent.com/assets/658327/8461763/d8ef0f5a-2026-11e5-98d6-b52ae7919527.png)

This is Chrome Version 43.0.2357.130 (64-bit) on a MacBook.

**Comment by surma** [comment] 2015-07-20 15:56
I am not able to reproduce this and we haven’t had similar reports. I’ll close this for now.

**Closed by surma** 2015-07-20 15:56 UTC
Labels: P2
