### ISSUE TITLE
Ripple Effect Does not work on input submit

### ISSUE THREAD

**Issue by mateeyow** [google/material-design-lite#1142] opened 2015-07-21 10:02 UTC
Here's a codepen: http://codepen.io/mateeyow/pen/WvgGLo

**Comment by surma** [comment] 2015-07-21 10:17
Confirmed.

Seems like any `<input type='button'>` doesn’t work either and I’m not sure there’s anything we can do about it. Thanks for issuing, we’ll look into it.

**Comment by mateeyow** [comment] 2015-07-21 10:19
@surma Thanks, but do you even sleep? :laughing:

**Comment by surma** [comment] 2015-07-21 10:22
@mateeyow I am a diagnosed sleep-coder.

**Comment by Garbee** [comment] 2015-07-21 10:28
There isn't anything we can do. You **should** use a button element instead of input here. Inputs can't have children nodes, so the ripple effect (which is based on using some children elements and a parent container iirc) doesn't have the right elements in places it needs.

Why exactly are you trying to use an input node over a button?

**Comment by mateeyow** [comment] 2015-07-21 10:34
Yup, I used button element. I was just wondering why it doesn't work. I thought it works the same as the aesthetic of the button.

**Comment by Garbee** [comment] 2015-07-21 10:39
It's because of the childnode problem. Inputs have their own shadow dom, but touching that is beyond what MDL can and should do. The only way to make this function is to manipulate that. Following any instructions we provide, buttons are used and should be continue to get used.

I'm closing this out since it is a technological limitation on what is possible. I think building a hack to make input types work for ripple is just bloat in the end. This is since it is a niche case to begin with, the extra code is wasted for most sites. Button elements work just fine, we should encourage they get used. I can't think of any real *need* for input types to be used as submit buttons.

**Closed by Garbee** 2015-07-21 10:39 UTC
Labels: bug, Ripple

**Comment by surma** [comment] 2015-07-21 10:43
@Garbee Ah thanks! Didn’t know we already looked into this.

@mateeyow My suggestion would be along the lines of 
```HTML
<a onclick="document.formName.submit()" class="mdl-button mdl-js-ripple-effect ...">Submit</a>
```

**Comment by Garbee** [comment] 2015-07-21 10:56
Since when is:

```html
<button type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect">Submit</button>
```

Not good enough? :tongue: No need for a javascript event trigger.

We also didn't look into this before afaik. I just know how inputs work and how the ripple stuff functions. The two together don't mix.

**Comment by surma** [comment] 2015-07-21 11:01
Lol. I’m dumb. I’ll be over here, being ashamed of myself.

**Comment by mateeyow** [comment] 2015-07-21 11:03
How does that make me feel? :sob:
