### ISSUE TITLE
event.stopPropagation() in tooltip.js makes it impossible to add a click event on button with tooltip

### ISSUE THREAD

**Issue by Cowboy-coder** [google/material-design-lite#1461] opened 2015-08-24 14:47 UTC
I'm not sure why `event.stopPropagation()` is used instead of `event.preventDefault()` here:

https://github.com/google/material-design-lite/blob/master/src/tooltip/tooltip.js#L65

Changing to event.preventDefault() solves my issues and I'm wondering if there's any good reasons why stopPropagation is used here?

**Comment by Garbee** [comment] 2015-08-24 16:26
Can you provide a codepen or other live example of the code you are trying to use which is having a problem?

**Comment by Cowboy-coder** [comment] 2015-08-25 08:29
This reproduces the problem:
http://codepen.io/anon/pen/QbeQvO

However... maybe `event.preventDefault()` is not the solution either. I think maybe you should neither use `stopPropagation` or `preventDefault` and just let the event pass through. Because... if you want to add a tooltip on an anchor link then preventDefault will make it not follow the link... which is unexpected behavior I would say.

**Comment by Garbee** [comment] 2015-08-25 11:59
Upgraded the example a bit available with [this fork](http://codepen.io/anon/pen/WvVJov). Directly assigning the event to the button works fine. So what you need should be achievable, will just require rethinking the way you setup your listeners.

Any particular reason you need to delegate listeners? Looks like changing this functionality now would be a breaking change.

**Comment by Cowboy-coder** [comment] 2015-08-25 13:26
I think delegate listeners is a common (and good) practice?
But for us in our case we're using React together with material-design-lite and I guess React underneath when you add a click-property it just delegates it.
But I've always used delegate listeners in the past as well to be able to add/remove DOMElements without having to re-attach/remove listeners.

But I managed to solve it on my side by using onMouseUp instead of click. It's not perfect but it works. 
But yeah maybe for a 1.1.x release this should be fixed (if possible :) ).

**Comment by Garbee** [comment] 2015-08-25 15:47
Delegated event listeners are a performance antipattern. They should be avoided.

We can't fix in 1.x at all. It is a breaking change so it must go into 2.x at the earliest.

**Comment by jabbett** [comment] 2015-08-25 20:09
It looks as if Backbone is doing the same delegation as React - so it's a problem for our project too. (We can't get the tooltips to display beyond the edge of a card anyway, so I think we'll drop use of tooltips altogether, anyhow.)

**Comment by kctang** [comment] 2015-08-28 01:18
Same issue with Meteor based project. Events defined in a template will not work when tooltips are assigned to buttons.

    Template.myForm.events({
        'click button': function() {
            console.log('not happening when button has tooltip');
        }
    });

For now, will be dropping use of tooltips in places where interaction like clicking is needed (which is common).

**Comment by vasiliy-pdk** [comment] 2015-09-10 14:18
Same with Marionette.js

**Comment by vasiliy-pdk** [comment] 2015-09-10 14:53
By the way. Why is the click event handler necessary for the tooltip? I had tried to remove click event handler and this resolved the problem. I did not saw any visible changes in the tooltips behavior.

**Comment by Garbee** [comment] 2015-09-10 15:08
I don't know why the tooltip had this added in the first place. However, it has been there since launch therefore sites may be coded that depend upon it working as it does. Which is why it is a breaking change to fix in 1.x.

**Comment by surma** [comment] 2015-09-10 15:28
For context: The click handler is necessary for mobile because there’s no such thing as hovering on mobile. Clicking on the target element shows the tooltip, clicking outside hides it again.

**Comment by Garbee** [comment] 2015-09-10 19:05
So sounds like there is nothing for us to fix here. App developers need to handle this case by applying event listeners more directly and not using delegated listening.

Unless someone has an alternative method for touch support, closing this out given the context.

**Closed by Garbee** 2015-09-10 19:05 UTC
Labels: BC Break, Tooltip

**Comment by faergeek** [comment] 2015-10-14 13:03
Should tooltip work on iPhone? It doesn't work at least in iOS Simulator, sadly I don't have a real hardware to test.

It actually works strange even on Android, events fired twice.

May be it should be written in a more straight forward way?
I could try to find a better solution for that if needed.

**Comment by surma** [comment] 2015-10-14 13:12
Yes, tooltips are supposed to work on iOS and they do work for me on both the simulator and physical devices.

![tooltip](https://cloud.githubusercontent.com/assets/234957/10484556/932ce7c2-727d-11e5-99b8-6228b302bf66.gif)

**Comment by tleunen** [comment] 2015-10-14 13:17
With the current implementation, does it mean it's impossible to get a tooltip on a button and have both work properly?
Wouldn't be better to add a small question mark beside the element for the tooltip on mobile devices?

**Comment by surma** [comment] 2015-10-14 13:22
@tleunen Aside from the fact that I think tooltips on a button are not a good idea: Yes, that will currently not work.

As always, we are staying as close to the spec as possible – a question mark or any other visual indicator for a tooltip is not in there. In general: Tooltips should probably be avoided on mobile in the first place because hovering is not really a concept and it makes the UX a little wonky.

**Comment by tleunen** [comment] 2015-10-14 13:26
Hmm.. Unless I'm missing something, the spec shows a tooltip on a button...
https://www.google.com/design/spec/components/tooltips.html#tooltips-tooltips-mobile-
The refresh is a button, but it also describes it as a "press and hold state", which is different than what we currently have.

**Comment by surma** [comment] 2015-10-14 13:29
@tleunen I was refering to a visual indicator for the presence of a tooltip not being in the spec. We are aware that tooltips on buttons are in the spec, but with the current implementation they are not possible. It’s a technical limitation as we haven’t figured out how to support the tooltips on mobile well enough.

**Comment by faergeek** [comment] 2015-10-14 13:31
@surma And because of that I suggest help to implement it well enough :-)
I'm recording a few frames with the problem on iOS ATM.

**Comment by faergeek** [comment] 2015-10-14 13:36
Here it is, it works but there's a problem when we click on one tooltip and then the other one:

![tooltip](https://cloud.githubusercontent.com/assets/3524621/10485196/8b8795d0-7291-11e5-9556-10e460450c91.gif)

**Comment by faergeek** [comment] 2015-10-14 15:38
@surma Are you agree that it needs a fix or it's unreproducible on a real hardware?

**Comment by surma** [comment] 2015-10-15 13:31
Yup, agreed :smile:

**Comment by Download** [comment] 2015-11-25 10:57
Stopping propagation is generally considered bad practice, though it's done often. [This article](https://css-tricks.com/dangers-stopping-event-propagation/) gives a good insight into the problems with in and if you search around a little on this topic you'll find both many bug reports on it, as well as postings where people are trying to warn about or explain the problems with stopping propagation.

Furthermore, I am not so sure about the argument that changing this behavior would be a breaking change... When we follow this reasoning than nearly *any* change is a breaking change. The question should be what the *specified* behavior is. We have seen actual, reported, problems as a result of stopping propagation and only a suspicion that sites might be depending on it. But depending on undocumented behavior is always risky isn't it? The spec is there to tell you what you can depend on and what not.

**Comment by Garbee** [comment] 2015-11-25 11:55
We are aware of the general notion that stopping propagation is bad. However it is the only way to make sure tooltips happen on mobile without causing secondary actions, like form submits or the button action to occur.

The fact is, stopping propagation does have its place and this is one of them. If you want tooltips on buttons to work on mobile without causing the button main event to fire, it is needed. 

That being said, is there an alternative to achieve the same result we currently have without stopping propagation? We can go over "best practices" all day long, but unless we have a valid alternative this isn't going to change until 2.x at the earliest.

**Comment by Download** [comment] 2015-11-26 10:03
> We are aware of the general notion that stopping propagation is bad.

Great. Sorry, I did not want to lecture you, just got the impression from reading the issue that you were not aware of this so wanted to give you a good link to read up on it. The referenced article really helped my own understanding of the problem.

Thanks for your awesome project btw!
