### ISSUE TITLE
[Component Request] Dialogs

### ISSUE THREAD

**Issue by dflorey** [google/material-design-lite#933] opened 2015-07-10 06:10 UTC
Please include:
* Description
Please add dialogs

* Material Design Spec link
https://www.google.de/design/spec/components/dialogs.html

* Use Case(s)
Show dialogs ;-)

**Comment by kybarg** [comment] 2015-07-10 06:12
Issue #781

**Comment by addyosmani** [comment] 2015-07-10 09:12
Dupe of #781

**Closed by addyosmani** 2015-07-10 09:12 UTC
