### ISSUE TITLE
Card subtitle not aligning correctly

### ISSUE THREAD

**Issue by thomassross** [google/material-design-lite#5031] opened 2017-02-08 01:00 UTC
Using MDL version 1.3.0, on Chromium 55 (and Firefox 52) on Debian Linux (Stretch), the subtitle of cards (`mdl-card__subtitle-text`) does not align properly:
![Initial Problem](http://i.imgur.com/XZKGT7a.png)

I found #1002 which is the exact same issue, but the workaround listed there does not work, the Title is still on the right. The [jsfiddle](https://jsfiddle.net/dzL25bmq/1/) linked there demonstrates the issue:
![Problem with Workaround](http://i.imgur.com/KRZw3fL.png)

Does anyone have a workaround for this?

Thanks,
Thomas.

**Comment by Garbee** [comment] 2017-02-08 12:15
Duplicate of #1002.

**Closed as completed by Garbee** 2017-02-08 12:15 UTC

**Comment by thomassross** [comment] 2017-02-08 15:35
Hi,

Yes, I have listed that issue in my issue, the problem is that the workaround there does not work. Is there a new workaround that works for 1.3?

**Comment by Garbee** [comment] 2017-02-08 16:58
[Same](https://jsfiddle.net/chz2e0jz/) as the [one mentioned](https://github.com/google/material-design-lite/issues/1002#issuecomment-170718247) in the previous issue.

**Comment by thomassross** [comment] 2017-02-08 20:28
Oh, didn't see the `.mdl-card__title-text`. Thanks!
