### ISSUE TITLE
MDL and Infinite Scroll

### ISSUE THREAD

**Issue by sevekim** [google/material-design-lite#1584] opened 2015-09-09 20:27 UTC
Hi. 

So, I am using infinite scroll (http://infiniteajaxscroll.com/docs/getting-started.html).

However when the main content is inside of "mdl-js-layout" the infinite scroll function does not work (shown below)

      <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer">
	<header class="mdl-layout__header">
		Head
	</head>
	<main class="mdl-layout__content">
		<div class="rfp_hide" id="rhm_post_show">
			<?php
			if ( get_query_var('paged') ) {
				$paged = get_query_var('paged');
			} elseif ( get_query_var('page') ) {
				$paged = get_query_var('page');
			} else {
				$paged = 1;
			}
			$args = array( 				
				'paged'=>$paged,
				'posts_per_page' => 5,				
				'orderby' => 'date',			
				'order' => 'DESC'
				);
			$loop = new WP_Query( $args );
			global $post, $paged; 
			while ( $loop->have_posts() ) : $loop->the_post(); 
			?>
			<div class="rhm_post_container">
				Post
			</div>
			<?php endwhile; ?>
			<?php wp_reset_postdata(); ?>		
		</div>
		<nav id="rh_nav_below">
			<ul>
				<li class="rh_nav_previous"><?php previous_posts_link( '&laquo; PREV', $loop->max_num_pages) ?></li> 
				<li class="rh_nav_next"><?php next_posts_link( 'NEXT &raquo;', $loop->max_num_pages) ?></li>
			</ul>
		</nav>
	</main>
    </div>

    <script>
	var container = document.querySelector('#rhm_post_show');
	var msnry = new Masonry( container, {
	  // options
	  itemSelector: '.rhm_post_container',
	  gutter: 10
	});

	var ias = $.ias({
	  container:  '#rhm_post_show',
	  item:       '.rhm_post_container',
	  pagination: '#rh_nav_below',
	  next:       '.rh_nav_next a',
	  delay: 100
	});

	ias.on('render', function(items) {
	  $(items).css({ opacity: 0 });
	});

	ias.on('rendered', function(items) {
	  msnry.appended(items);
	});

	 ias.extension(new IASSpinnerExtension());
	 ias.extension(new IASNoneLeftExtension({html: '<div class="ias-noneleft" style="text-align:center"><p><em>You reached the end!</em></p></div>'}));
     </script>

So, if I remove the mdl-js-layout in the most outer div, then infinite scroll works otherwise it does not work.

Does anyone know how I can address this issue?

Thanks

**Comment by surma** [comment] 2015-09-09 22:16
MDL is targeting static content for now, so use-cases with infinite scroll are not supported by us right now. However, there are people who have made MDL work with dynamic sites and you can probably get valuable help by heading over to StackOverflow and using the `material-design-lite` tag.

Closing this as this is not a bug with MDL.

**Closed by surma** 2015-09-09 22:16 UTC

**Comment by sevekim** [comment] 2015-09-20 06:57
Hi. So i am getting no results from Stackoverflow for over 1 week and I have no idea to to make this work.

Is there a support that I can get with this ?

Thanks!

**Comment by Garbee** [comment] 2015-09-20 15:34
We do not provide support  in this issue tracker. For numerous reasons it simply isn't the right place for it. If StackOverflow isn't working out then you need to find somewhere else online that has a good support  community or a place that offers paid help for programming.

We can try to help if there is a clear and direct problem with MDL. Your question here involves 2 or 3 things other than MDL and asking how they fit together, this is clearly in the support realm which we can't help with here.
