### ISSUE TITLE
[mdl-menu] Menu position does not match Material Design spec

### ISSUE THREAD

**Issue by apokusin** [google/material-design-lite#4825] opened 2016-10-05 20:52 UTC
**v1.2.1**
All browsers

*What is the expected behavior?*
Simple menus appear over their emitting element, not below.

*What is the actual behavior?*
Simple menus appear below their emitting element.

## Resources
- [MDL v2 Menu component](https://github.com/google/material-design-lite/issues/4474)

- [Material Design Lite implementation](https://getmdl.io/components/#menus-section)
![screen shot 2016-10-05 at 1 47 31 pm](https://cloud.githubusercontent.com/assets/1258230/19130962/596e1e9a-8b02-11e6-8650-17da9230445a.png)

- [Material Design Spec](https://material.google.com/components/menus.html#menus-simple-menus)
![screen shot 2016-10-05 at 1 46 03 pm](https://cloud.githubusercontent.com/assets/1258230/19130977/6bec7b20-8b02-11e6-8e94-ee639f7de4ba.png)

**Comment by Garbee** [comment] 2016-10-06 13:20
Duplicate of #1848.

**Closed by Garbee** 2016-10-06 13:20 UTC
