### ISSUE TITLE
[Component Request] {Component}

### ISSUE THREAD

**Issue by louie113** [google/material-design-lite#4557] opened 2016-07-14 13:10 UTC
I'm sure that bottom navigation must be included in GETMDL.IO
https://material.google.com/components/bottom-navigation.html
It's very useful component i think.

**Comment by Garbee** [comment] 2016-07-14 13:23
Duplicate of #4503.

Please search existing issues before filing new ones.

Thank you.

**Closed by Garbee** 2016-07-14 13:23 UTC
