### ISSUE TITLE
Nothing happens when tapping cards in blog template on iOS devices

### ISSUE THREAD

**Issue by minimaxir** [google/material-design-lite#1055] opened 2015-07-15 14:43 UTC
See title.

Issue reproduces with my iPhone 6 and iPad Air 2 both running iOS 8.4. Does not happen with Chrome on my Nexus 7 (touching cards for navigation works correctly).

**Comment by surma** [comment] 2015-07-20 12:32
@minimaxir I am not sure if we fixed it in the mean time by accident or something else is going on, but I can’t reproduce the issue on my iPhone 5 (8.4) or the iOS simulator (8.3) for both getmdl.io and on master.

Can you re-check if the issue is still present on the [live-version](http://www.getmdl.io/templates/blog/index.html)?

**Comment by surma** [comment] 2015-07-28 16:16
Can’t reproduce on iPhone 6 either. Closing for now. Please re-open if you still have the issue.

**Closed by surma** 2015-07-28 16:16 UTC
