### ISSUE TITLE
Multiple line textfield demo seems broken on website

### ISSUE THREAD

**Issue by rpominov** [google/material-design-lite#1487] opened 2015-08-27 14:14 UTC
This is how it looks at least on Mac/Chrome:

![](http://g.recordit.co/EkW9ilWYiW.gif)

http://www.getmdl.io/components/index.html#textfields-section

**Comment by Garbee** [comment] 2015-08-27 14:22
Can you define what you mean by broken? Seems to be functioning normally to me.

**Comment by rpominov** [comment] 2015-08-27 14:25
I remember it was automatically changing it's height when you type. Or perhaps I've seen it somewhere else, sorry if this is the case :)

**Comment by Garbee** [comment] 2015-08-27 14:30
The default textarea element doesn't seem to do this. Nor should the example since its height is hard-set to 150px.

It is working as per the [spec for textfields](https://www.google.com/design/spec/components/text-fields.html#text-fields-floating-labels):

>Multi-line text fields automatically break to a new line for overflow text **and scroll vertically when the cursor reaches the lower edge**.

Closing since it is working as intended.

**Closed by Garbee** 2015-08-27 14:30 UTC

**Comment by rpominov** [comment] 2015-08-27 14:33
Right. I've probably seen automatic height change here http://material-ui.com/#/components/text-fields. Sorry for wrong report.
