### ISSUE TITLE
Minor bug with element stays on top of content being invisible

### ISSUE THREAD

**Issue by scsmash3r** [google/material-design-lite#1290] opened 2015-08-03 22:12 UTC
So eventually I'm digging into Google Material Design: http://www.getmdl.io/

Everything was go nicely until I found a minor bug regarding hidden elements. http://www.getmdl.io/templates/dashboard/index.html - here is the example. Just click on the arrow button near <code>hello@example.com</code> to trigger menu show, and then close it. The problem is that you won't be able to hover over that zone where the menu was - in other words, you can't click 2 upper links in the sidebar.

So the element's visibility is hidden, but it's still there, on page. The question: is there any quick solution to fix this stuff? By far the best I was able to write is CSS overwrite:

<code>
.mdl-menucontainer {
height:0px !important;
}
.mdl-menucontainer.is_visible {
height:auto;
}
</code>
But it's a dirty solution, and I always try to avoid using !important rule. Any other workarounds or how it can be fixed?

**Comment by Garbee** [comment] 2015-08-07 11:38
Duplicate of #1025

**Closed by Garbee** 2015-08-07 11:38 UTC
Labels: confirmed, Menu, P1
