### ISSUE TITLE
Search Component Broken In Template

### ISSUE THREAD

**Issue by simpsondigital** [google/material-design-lite#4727] opened 2016-09-07 21:33 UTC
Version: MDL 1.x
Browser: Chrome
OS: OS X 10.11.6

Problem:

The search component in the "Dashboard" template header is broken. It should be laying out neatly aligned to the left of the "More Options" button, but it's breaking and flowing below the header.

See issue here: https://getmdl.io/templates/dashboard/index.html

![image](https://cloud.githubusercontent.com/assets/3050736/18329408/3d154210-7521-11e6-9a28-be36dce3f25b.png)

**Comment by Garbee** [comment] 2016-09-08 10:37
Duplicate of #4532

**Closed by Garbee** 2016-09-08 10:37 UTC
