### ISSUE TITLE
mdl-layout__drawer doesnt show hamburguer on android browsers

### ISSUE THREAD

**Issue by MarcosGalaviz** [google/material-design-lite#1911] opened 2015-11-24 20:55 UTC
Hi, does anyone know why the hamburguer icon of mdl-layout__drawer doesnt apear on android browsers and how can i fix it?

Thanks a lot

**Comment by Garbee** [comment] 2015-11-24 22:32
What version of android? Might be one that doesn't support ligatures. In which case duplicate of #1859

**Comment by MarcosGalaviz** [comment] 2015-11-25 16:31
Hi thanks,  in all the versions the hamburguer icon doesn apear :( but the menu is there, if I touch in that part (where the hamburguer shuld be) the menu opens :( i read somewhere that is because the icon is a SVG, and sugested to change it for .PNG but i dont know how to do that :(

**Comment by Garbee** [comment] 2015-11-25 16:55
> in all the versions the hamburguer icon doesn apear

Can you please be more specific about what versions you have tested? "All" is very broad and we have tested in quite a few versions manually to make sure it is working for newer devices at least.

Right now, developers are unable to easily mess with the layout setup. We are working in 2.x to provide full control. For right now though, the JS provided is fairly closed off and we can't open it up easily.

**Comment by MarcosGalaviz** [comment] 2015-11-25 17:12
I have Android 4.3 :(

**Comment by sgomes** [comment] 2015-12-04 13:25
Thanks for the info, @MarcosGalaviz!

4.3 does have the pre-Chromium Android browser that doesn't support ligatures. So yes, this is a duplicate of #1859. Feel free to follow that bug to stay up to date on our work there!

**Closed by sgomes** 2015-12-04 13:25 UTC
