### ISSUE TITLE
Fixed navbar bug in mobile browser

### ISSUE THREAD

**Issue by Bound3R** [google/material-design-lite#1250] opened 2015-07-29 15:21 UTC
by using the options: navbar fixed and drawer_layout, for the menu, I found that in some cases it does not hide the navigation bar of the browser.
Eg: in the android web template the navigation bar is always fixed, in ios this situation is 

![screenshot_2015-07-28-12-52-14](https://cloud.githubusercontent.com/assets/5579520/8941087/3dc7cbe4-3533-11e5-8f44-c535de84714d.png)

( the page is about half, and not moving navigation bar of web browser)

**Comment by mspl13** [comment] 2015-07-29 16:03
This seems to be a duplicate of #1072. A [small workaround](https://github.com/google/material-design-lite/issues/1072#issuecomment-123445135) was already mentioned.

**Comment by surma** [comment] 2015-07-29 16:09
@mspl13 Correct. This will probably not be resolved upstream before v2.

**Closed by surma** 2015-07-29 16:09 UTC
