### ISSUE TITLE
mdl-layout-title bug

### ISSUE THREAD

**Issue by Furyon** [google/material-design-lite#1399] opened 2015-08-16 05:21 UTC
![image link](https://cloud.githubusercontent.com/assets/7620367/9292121/d11f23d6-4408-11e5-9fc4-105af61ab0b2.png)

http://www.getmdl.io/templates/dashboard/index.html

**Comment by surma** [comment] 2015-08-16 09:14
Duplicate of #1074. Fix will be available to you with 1.0.3 :)

**Closed by surma** 2015-08-16 09:14 UTC
