### ISSUE TITLE
Implement Toggle Button v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4493] opened 2016-06-29 19:08 UTC
Spec reference: https://www.google.com/design/spec/components/buttons.html#buttons-toggle-buttons

**Comment by alexgig** [comment] 2016-08-24 18:47
Duplicate of #4470?

**Comment by traviskaufman** [comment] 2016-08-24 22:31
@alexgig I see where the confusion comes from but they actually refer to two different things. Icon toggles are one, and toggle buttons such as those you see within the button bar mocks are another. They are very similar in nature.

**Comment by alexgig** [comment] 2016-08-25 16:36
Cool. Thought I might be able to help lighten the load by getting something off the list. Maybe next time :-)

Hope your day's going well.

Best,
Alex

**Comment by sfdexter** [comment] 2016-12-16 19:19
Superceded by https://github.com/material-components/material-components-web/issues/26

**Closed by sfdexter** 2016-12-16 19:19 UTC
Labels: in-tracker, v2-component
