### ISSUE TITLE
Table border and dividers issue in Chrome

### ISSUE THREAD

**Issue by lyngbach** [google/material-design-lite#4342] opened 2016-05-12 09:17 UTC
Recently I have noticed some strange behaviour in Chrome when showing tables in MDL.

It doesn't show the table's border and td's divider lines until you start hovering over the table with your mouse.
I asked others to check it out aswell on your documentation site (https://getmdl.io/components/index.html#tables-section) to make sure it wasent my browser specific or some addon.

It does seems to work fine and in Firefox and Edge and most likely a browser issue, but is there currently any plans to address this or is there someone with a workaround until the Chrome team "fix" this?

**Comment by Garbee** [comment] 2016-05-12 13:02
Duplicate of #4325

**Closed by Garbee** 2016-05-12 13:02 UTC
