### ISSUE TITLE
"Android" themed demo website side menu doesn't scroll on Chrome 45 OS-X Yosemite

### ISSUE THREAD

**Issue by babakness** [google/material-design-lite#1615] opened 2015-09-17 18:47 UTC
The "Android" themed demo website's side menu will not scroll using the scroll-wheel / two-finger-slide-gesture on Chrome 45.0.2454.93 on Yosemite, OS-X 10.10.2

When emulating a phone such as the iPhone using Chrome's built-in tool (inspector) however it does work (it scrolls in emulation mode where the click is the same as a "touch" event).

**Comment by surma** [comment] 2015-09-20 00:18
This is most likely a duplicate of #1110. Closing this in favor of said issue.

**Closed by surma** 2015-09-20 00:18 UTC
