### ISSUE TITLE
mocha' errored after 149s, Error in plugin 'gulp-mocha-phantomjs'

### ISSUE THREAD

**Issue by WG-C** [google/material-design-lite#1342] opened 2015-08-10 10:23 UTC
gulp all: 
```
  at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
[18:15:53] 'mocha' errored after 149 ms
[18:15:53] Error in plugin 'gulp-mocha-phantomjs'
test failed
```

OSX

**Comment by surma** [comment] 2015-08-10 10:35
Which version of `npm` and `node` are you running? I can’t reproduce this issue.

**Comment by HuaTiMeiTian** [comment] 2015-08-10 10:39
```
node -v
v0.12.7
```

```
npm -v
2.12.1
```

```alibaba cnpm: 
cnpm -v
3.1.0
```

**Comment by HuaTiMeiTian** [comment] 2015-08-10 10:42
```
    "gulp-marked": "^1.0.0",
    "gulp-minify-html": "^1.0.0",
    "gulp-mocha-phantomjs": "^0.8.1",    //  【   0.6 ， 0.8 same error  】
    "gulp-open": "^0.3.2",
    "gulp-rename": "^1.2.0",
```

**Comment by HuaTiMeiTian** [comment] 2015-08-10 10:45
```
[18:15:53] Starting 'mocha'...
child_process.js:1136
  var err = this._handle.spawn(options);
                         ^
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (child_process.js:1136:26)
    at exports.spawn (child_process.js:995:9)
    at Object.<anonymous> (/Users/username/Desktop/mdl/material-design-lite/node_modules/gulp-mocha-phantomjs/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
[18:15:53] 'mocha' errored after 149 ms
[18:15:53] Error in plugin 'gulp-mocha-phantomjs'
test failed
```

**Comment by surma** [comment] 2015-08-10 10:48
As I said, [I can’t reproduce the issue](http://showterm.io/a4d888e542851dd83a40c#fast). You you do the following and tell me if that changes anything:
(Danger: This *will* delete everything you have not committed)

```
git fetch origin
git checkout master
git reset --hard origin/master
git clean -fxd
npm install
gulp all

```

**Comment by HuaTiMeiTian** [comment] 2015-08-10 11:13
```
[19:12:15] Using gulpfile ~/Desktop/mdl/material-design-lite/gulpfile.js
[19:12:15] Starting 'clean'...
[19:12:15] Starting 'styles'...
[19:12:16] Finished 'clean' after 469 ms
[19:12:19] 'styles' all files 475.51 kB
[19:12:19] Finished 'styles' after 3.68 s
[19:12:19] Starting 'mocha'...
child_process.js:1136
  var err = this._handle.spawn(options);
                         ^
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (child_process.js:1136:26)
    at exports.spawn (child_process.js:995:9)
    at Object.<anonymous> (/Users/username/Desktop/mdl/material-design-lite/node_modules/gulp-mocha-phantomjs/node_modules/phantomjs/bin/phantomjs:22:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
[19:12:19] 'mocha' errored after 221 ms
[19:12:19] Error in plugin 'gulp-mocha-phantomjs'
test failed
```

**Comment by HuaTiMeiTian** [comment] 2015-08-10 11:29
Could you give me a compiled version? I can't access the getdml.io(and getmdl.io.storage.googleapis.com/index.html),i'm in China, all Google's IP  blocked, I need to see the official documents

or put your getmdl.io compiled code on github pages or email to me : 211761329@qq.com

 i compile the source code last month , same error....

i need the document at getmdl.io 

thank you !!

**Comment by accessibleweb** [comment] 2015-09-03 22:20
Same problem for me

**Comment by cubicwork** [comment] 2015-10-01 07:15
@accessibleweb did the method you mentioned really works ?

**Comment by accessibleweb** [comment] 2015-10-01 11:19
@cubicwork Sure, it works as you can see it fail in mocha, mocha is only for testing so just comment it

**Comment by cubicwork** [comment] 2015-10-01 11:26
@accessibleweb i still wonder that how it behaviors normal if it didn't pass the test. By the way this is really a good solution to quick fix the problem. at least we can get a build from it.

**Comment by cubicwork** [comment] 2015-10-11 03:16
@WG-C @accessibleweb see #1672 
problem has been solved.

**Comment by lxbzmy** [comment] 2015-10-12 02:30
I meet the problem too. 
After clone new git repo and npm install ,error disappeared.

**Comment by traviskaufman** [comment] 2016-07-11 22:22
closing due to inactivity

**Closed by traviskaufman** 2016-07-11 22:22 UTC
