### ISSUE TITLE
Any way to remove the space for hamburger icon?

### ISSUE THREAD

**Issue by 7bitex** [google/material-design-lite#1368] opened 2015-08-12 05:22 UTC
I put a `mdl-layout-title` in the header but it will automatically leave the space for a hamburger icon on the left, and I'm not going to put a hamburger there. Is there any way to remove the space?

**Comment by SeanBannister** [comment] 2015-08-12 07:43
Looks like this has already been reported in #1032 and fixed. I was under the impression it was fixed before 1.0.2 (haven't had a chance to check) if not it'll be in 1.0.3.

I mentioned a quick fix for this at #1078

**Comment by sgomes** [comment] 2015-08-12 11:12
#1032 only applies to fixed drawers, though. Is that your use case, @7bitex?

**Comment by 7bitex** [comment] 2015-08-12 11:20
Thanks @SeanBannister, I've found your solution and it didn't work for me.

And to @sgomes, it's not the same use case as mine. I don't need a drawer at all. I only need a header with the title in the right place.

**Comment by sgomes** [comment] 2015-08-12 12:51
Thanks, @7bitex! This is not a duplicate of #1032, in that case.

I'm reluctant to change the default behaviour, because that would be a BC break, and I'm also reluctant to add yet another optional class to complicate `mdl-layout` behaviour further.

Would adding a small rule to your CSS work for you, @7bitex? The following should do the trick:

```css
.mdl-layout__header-row {
  padding-left: 24px !important;
}
```

The above will override the default padding on all header rows to a less odd-looking 24px. You can play with that value until you get a positioning you like.

You may want to scope it accordingly as well, by adding a class to your `mdl-layout__header` and targeting that, but that's the gist of it!

**Comment by 7bitex** [comment] 2015-08-12 13:57
@sgomes Thanks for the solution and it works, and I think I should use media queries to . I'm wondering why the header and the drawer are combined into one component instead of two separate ones? Hope the header could have more usages e.g. using a back arrow instead of the hamburger icon.

**Comment by sgomes** [comment] 2015-08-12 14:04
Good to hear that did the trick, @7bitex! And yes, media queries are probably a good idea, to adjust that spacing at different screen sizes.

As for why we have a single layout component, rather than multiple ones, that decision came from the close interactions they have between themselves, and trying to make it as easy as possible to use. This is one of the points we'll definitely reconsider in a v2, though, thanks!

**Closed** 2015-08-12 14:43 UTC
