### ISSUE TITLE
Sticky toolbar does not stick in iOS chrome

### ISSUE THREAD

**Issue by jimbojetlag** [google/material-design-lite#939] opened 2015-07-10 12:18 UTC
https://github.com/google/material-design-lite/issues/925#issuecomment-120389982

**Comment by surma** [comment] 2015-07-20 13:56
I have [reproduced this issue](https://youtu.be/bwJG5H0Muao). AFAICT, this happens in every UIWebView. Will investigate on how to fix this.

**Comment by surma** [comment] 2015-07-29 12:33
To work around this issue some very invasive work needs to be done on the components page. We’ll hold off on this, since an overhaul on the components page is planned anyways.

**Comment by sgomes** [comment] 2016-03-09 13:32
This should be fixed with current iOS Chrome. Please reopen if it's still an issue.

**Closed by sgomes** 2016-03-09 13:32 UTC
Labels: confirmed, future
