### ISSUE TITLE
onclick event for table row fired twice on clicking checkbox for selectable table

### ISSUE THREAD

**Issue by ctalpandey** [google/material-design-lite#4979] opened 2016-12-14 14:07 UTC
Check https://codepen.io/ctalpandey/pen/gLBJXm which is example of https://getmdl.io/components/index.html#tables-section itself but only modified to add row onclick event i.e. alert(#row-number). Click anywhere on row except checkbox; alert message is displayed once. Click checkbox, same alert message displayed twice.

**Comment by Garbee** [comment] 2016-12-14 16:42
This is caused by the structure used for the auto-generated checkboxes. Which are also deprecated, please see the [wiki](https://github.com/google/material-design-lite/wiki/Deprecations#automatic-selection-checkboxes) for how you should do things manually to have the control needed to fix this.

The problem here is, `<label>` being used as the wrapping parent of the checkbox. That causes a click even, but they cause click events on the associated inputs as well. Which means, a second click bubbles out of the row.

We can't fix this in V1 as existing sites may depend upon `<label>` being the structure. The [wiki](https://github.com/google/material-design-lite/wiki/Deprecations#automatic-selection-checkboxes) shows how you can manually create the checkbox markup to have complete control. Once you set them up with `<span>` instead of `<label>` as the wrapper this problem should go away.

Since there is nothing actionable here due to BC concerns for V1, I'll go ahead and close this issue out. V2 shouldn't be affected by this since we won't be auto-generating the checkboxes at all from what we have discussed previously for the plans regarding this.

Thank you.

**Closed by Garbee** 2016-12-14 16:42 UTC
