### ISSUE TITLE
Error with autocomplete in chrome

### ISSUE THREAD

**Issue by fgvicente** [google/material-design-lite#5008] opened 2017-01-12 16:28 UTC
Error with autocomplete in chrome
![screenshot from 2017-01-12 13 27 10](https://cloud.githubusercontent.com/assets/3626864/21898255/08e6ad7c-d8cb-11e6-955c-fd4026501cb9.png)

**Comment by Garbee** [comment] 2017-01-12 16:35
Duplicate of #903

**Closed as completed by Garbee** 2017-01-12 16:35 UTC
