### ISSUE TITLE
[Component Request] {Stappers}

### ISSUE THREAD

**Issue by stringariSM** [google/material-design-lite#5009] opened 2017-01-12 16:55 UTC
Please include:
* Description
Steppers display progress through a sequence of logical and numbered steps. They may also be used for navigation.
Steppers may display a transient feedback message after a step is saved.

* Material Design Spec link: 
https://material.io/guidelines/components/steppers.html

* Use Case(s):
Steppers display progress through a sequence by breaking it up into multiple logical and numbered steps.

**Comment by Garbee** [comment] 2017-01-12 17:10
Duplicate of #4501

**Closed as completed by Garbee** 2017-01-12 17:10 UTC
