### ISSUE TITLE
Textfield with date input ui bug in iOS Safari

### ISSUE THREAD

**Issue by nkpgardose** [google/material-design-lite#4349] opened 2016-05-13 00:05 UTC
Having a date input textfield with no placeholder produces this ui bug in iOS safari
<img width="298" alt="screen shot 2016-05-13 at 8 04 04 am" src="https://cloud.githubusercontent.com/assets/3381818/15234158/546ae042-18e1-11e6-82ed-4c812e005776.png">

Here's my code snippet:
```html
<div class="mdl-textfield mdl-js-textfield">
  <input class="mdl-textfield__input js-textfield-required" type="date" name="account[dob]" id="account_dob">
  <label class="mdl-textfield__label" for="account_dob">Date of birth*</label>
  <span class="mdl-textfield__error">
    You must be 18 years or older to register
  </span>
</div>
```
Here's a sample code: https://codepen.io/anon/pen/JXVYBz?editors=1000

**Comment by Garbee** [comment] 2016-05-13 10:14
Duplicate of #853.

`type=date` is a more specialized input type, so we currently have no plans to support it considering the spec has specific requirements for what will need to be a custom date picker.

For now you'll need to fix this oddity in your own code if you want to use the date input type.

**Closed by Garbee** 2016-05-13 10:14 UTC
