### ISSUE TITLE
Regression: Form display alignment issue on Firefox

### ISSUE THREAD

**Issue by slybridges** [google/material-design-lite#1885] opened 2015-11-14 12:37 UTC
While using MDL `v1.0.6`, I've been bitten by the same issue as described in #788 where button does not properly allign on `Firefox` (works properly on Safari/Chrome).

CodePen using the same example as in #788: http://codepen.io/anon/pen/yYGrNO 

This is a regression introduced in version `1.0.3` onwards as if you change the css back to version `1.0.2` in CodePen, it aligns properly on Firefox (tested on latest Firefox v42.0 on OSX 10.11).

Regression was introduced in commit 92d2ef2.

Changing the `display` property of `.mdl-textfield__input` back to `inline-block`fixes the issue.

Happy to make a PR, but unsure how it may impact other layout issues.

**Comment by Garbee** [comment] 2015-11-14 12:45
I'm not sure what the best method for us to handle this would be, since changing to block was to fix another specific problem (and at the time it worked properly in each engine.) Thanks for reporting the regression.

**Comment by Garbee** [comment] 2015-11-14 12:47
Ah, taking a look the fix only went into `master` it may have never been cherry-picked into `mdl-1.0` for a patch release. So, could already be fixed in 1.1, just won't make it into a 1.0 series patch (since we are focusing on 1.1 now over more patch releases.)

**Comment by surma** [comment] 2015-11-19 20:28
@Garbee So this issue has been fixed in master and will be rolled out with 1.1? Can we close this?

**Comment by Garbee** [comment] 2015-11-19 20:43
I'd assume so. But I'd like to pull master clean and verify once I'm home just to be certain it is fixed for 1.1.

**Comment by Garbee** [comment] 2015-12-04 10:50
Just verified and it seems to be working correctly for me from master. Which means 1.1 will include the fix.

**Closed by Garbee** 2015-12-04 10:50 UTC
Labels: confirmed, research, Textfield

**Comment by slybridges** [comment] 2015-12-04 12:42
:+1: Thanks @Garbee !

**Comment by charsi** [comment] 2017-02-12 14:37
This seems to be recurring in 1.3.0 https://codepen.io/anon/pen/WRLRjb. Looks good in Chrome but not in firefox.

**Comment by JoeStech** [comment] 2018-01-19 05:37
I am also experiencing this regression in 1.3.0.
