### ISSUE TITLE
[Component Request] Expand/Collapse Menu

### ISSUE THREAD

**Issue by j-elmer123** [google/material-design-lite#4793] opened 2016-09-26 17:15 UTC
Please include:
* Description : A menu that can do expand/collapse animation, mainly used as generalization of many detailed menu.
* Material Design Spec link : https://material.google.com/components/lists-controls.html#lists-controls-types-of-list-controls
* Use Case(s) : mainly used as generalization of many

**Comment by traviskaufman** [comment] 2016-09-26 18:45
This is a duplicate of #4499.

We'll have this as a generic component for v2 (check the milestone on the issue for a more specific timeline), which you should be able to arbitrarily add to a card, a list, etc.

**Closed by traviskaufman** 2016-09-26 18:45 UTC
