### ISSUE TITLE
Page does not auto scroll back to top when touching iOS status bar

### ISSUE THREAD

**Issue by duyluandethuong** [google/material-design-lite#1512] opened 2015-08-30 22:37 UTC
In all pages, including the main page of MDL and all templates, when you touch the status bar in Mobile Safari, it should scrolls the page back to top. But it does not. I am investigating the mdl css file to find the issues, while informing you guys about this. Will update the issue once I find something.

**Comment by surma** [comment] 2015-08-30 23:13
This is effectively a duplicate of #1072 (same cause). Sadly, this cannot be fixed before v2. So closing in favor of that issue.

**Closed by surma** 2015-08-30 23:13 UTC
