### ISSUE TITLE
Showing a menu over navigation breaks nav elements

### ISSUE THREAD

**Issue by GradyD** [google/material-design-lite#1105] opened 2015-07-19 03:20 UTC
If you go to http://www.getmdl.io/templates/dashboard/index.html. Mouse over Home and Inbox, they are clickable and have a hover color. If you click the arrow next to the users email and click the arrow again or click outside of the menu that appears and try to mouse over Home or Inbox its not clickable and you don't get the hover color.

**Comment by kongd** [comment] 2015-07-19 06:42
Yup, running into the same issue here.

**Comment by kybarg** [comment] 2015-07-19 06:45
+1

**Comment by Garbee** [comment] 2015-07-19 11:02
Duplicate of issue #1025

**Closed by Garbee** 2015-07-19 11:02 UTC
