### ISSUE TITLE
Problem with .mdl-layout__drawer-button

### ISSUE THREAD

**Issue by Eliezer-Pujols** [google/material-design-lite#1472] opened 2015-08-26 01:14 UTC
Why is this happening? Help!!!!!!!

- My code:
  http://subefotos.com/ver/?80c17e04f9d64e96173eea0755bd73afo.png

- Result:
  http://subefotos.com/ver/?69cb2a46ef5c0f473f0f694193a32d8do.png

**Comment by surma** [comment] 2015-08-26 11:23
@Eliezer-Pujols I am not quite sure what I am looking at :smile: Here’s a few things I’d like to make you aware of:

* This issue tracker is for issues, bugs and feature requests with MDL. If you need support (i.e. MDL is working correctly but you are not sure how to use it), please go over to StackOverflow and use the `material-design-tag`.
* Be more specific where your expectations and your results differ. I have no idea what is upsetting you, because you are only saying “Why is this happening?”. What is *this*? Screenshots are good, but I’d prefer having the images inlined into the issue than relying on some 3rd party image host.
* *Never* provide your code as an image. At the very least copy and paste into a code block so we can use it. Bonus points for actually putting your code into a [CodePen](https://codepen.io) so we can fiddle around.

Im closing this issue as I’m assuming this is a support request. But feel free to reopen this, if you are actually experiencing a bug :)

**Closed by surma** 2015-08-26 11:23 UTC

**Comment by Eliezer-Pujols** [comment] 2015-08-26 20:26
You looked, but it did not see... The button of the booth not this one in the center. In Codepen this arranges, but without Codepen not. Because of it I did not show it to him in codepen.

**Comment by surma** [comment] 2015-08-27 11:20
@Eliezer-Pujols If the issue is not reproducible in a CodePen, it is very likely that there are some other stylings or scripts interfering, or you are not using the newest MDL version. This is definitely something for StackOverflow and the `material-design-lite` tag :)

**Comment by Garbee** [comment] 2015-08-27 11:50
This has come up a few times. I think everyone realized they were missing something in the layout markup structure in the end. Having a hard time tracking down the older issues about it.

**Comment by Eliezer-Pujols** [comment] 2015-08-27 22:55
Thanks, found it helpful!!!! :+1:
