### ISSUE TITLE
Checkbox has a white space at certain zoom levels

### ISSUE THREAD

**Issue by kbprakash** [google/material-design-lite#4081] opened 2016-02-05 18:59 UTC
if you keep zooming the page,  checkbox component has white space( between the border and check mark) at certain zoom levels.
<img width="682" alt="screen shot 2016-02-05 at 10 16 00 am" src="https://cloud.githubusercontent.com/assets/310100/12855994/6b4a58e2-cbf7-11e5-985f-b1593841d2dc.png">

**Comment by lucasljj** [comment] 2016-02-05 20:02
related #987

**Comment by Garbee** [comment] 2016-06-02 19:55
Duplicate of #987

**Closed by Garbee** 2016-06-02 19:55 UTC
