### ISSUE TITLE
Can't create and upgrade a slider element before inserting to the DOM

### ISSUE THREAD

**Issue by alextekartik** [google/material-design-lite#1071] opened 2015-07-16 12:24 UTC
The doc explaining how to create a dynamic element (button in this case) shows that you can upgrade an element before inserting to the DOM

```
componentHandler.upgradeElement(button);
document.getElementById('container').appendChild(button);
```

However this does not work for slider (seems to be related that it creates a wrapper around it). Calling upgradeElement throws: "Uncaught TypeError: Cannot read property 'insertBefore' of null"

Maybe the doc should explain how to create dynamically a slider (maybe shows that the container should be created as well before upgrading). Or maybe upgradeElement should return the element to be inserted into the DOM (i.e. the container in this case)

Example that shows the bug here: http://codepen.io/alextekartik/pen/pJZoBE (only one slider is created)

**Comment by Garbee** [comment] 2015-07-16 12:30
1) How would upgradeElement know where you want to inject something? This would need to be added as a new method and imo isn't of high enough value to add. So having the componentHandler do injection as well is off the table in my mind.

2) The button example works, other components may not allow for the same flow. This should be covered in the new docs I'm writing so developers know to understand the components and how they function in order to know the best upgrade and injection path.

**Comment by alextekartik** [comment] 2015-07-16 12:36
I think there are some cases where you want to create the element before inserting to the DOM. Currently I'm playing with react dart and mdl and slider does not play that well for this specific case. The trick I did was to create a div wrapper where I put the slider before upgrading it. upgradeElement creates another div wrapper no matter what. Even if I already have a div wrapper with mdl-slider__container class, upgradeElement is still creating yet another div wrapper with the same class insider, maybe this could be avoided

**Comment by Garbee** [comment] 2015-07-16 12:39
Eh, that would be a slider component issue and not likely to be dealt with. Unless we added a class to look for as the container, there is no reliable way to handle knowing if the parent container is *the* intended container or something else. i.e. adding a slider element right under <body> could lead to <body> becoming the container which on downgrade would get destroyed (once we implement destruction on downgrade.)

**Comment by timothylrobb** [comment] 2015-07-19 00:55
I found this same issue with the text field component.  I'm certain that it was intended that the componentHandler.upgradeElement() function was meant to work across all components, but it currently is not.  I will dig into the library to see if I can understand how it works.  Perhaps I can provide an answer or a fix.

**Comment by Garbee** [comment] 2015-07-19 01:13
@timothylrobb It does work, you simply need to add some into the document itself before upgrading them. The example covers the case (with button) where it can be upgraded before since it doesn't rely on other nodes outside of the containing element.

**Comment by timothylrobb** [comment] 2015-07-19 02:55
Thank you for clarifying that.  I am dynamically building components for my app and some components by design contain other components.  In this case, the text field is a component that is appears inside of another component.  I was hoping that when I call my new TextFieldComponent() class, it's constructor would be able to generate the object, apply the component upgrade, and return itself to be added to the containing component.  Looks like I will have to wait until after the parent component is added to the DOM to upgrade the contained components. (with the exception of the buttons).

**Comment by timothylrobb** [comment] 2015-07-19 03:20
I just discovered the solution.  It is possible to upgrade a component before it is added to the DOM.  componentHandler.upgradeElement() takes two parameters.  The first is the element object.  The second is a string that represents the registered js class name.  I had to browse through the material.js source code to find what the string should be for the textfield component.  On line 2824 I found this:   classAsString: 'MaterialTextfield',

That 'MaterialTextfield' was the string that made it work.  I'm guessing that it will work with the Slider to if you use the string 'MaterialSlider'.

**Comment by alextekartik** [comment] 2015-07-19 08:06
Indeed button and textfield can be upgraded (with the proper class parameter, although I wonder why it does not guess that from the element class name). The issue was regarding the slider (and some others) since upgrading it means wrapping it by another element (so it needs to know the parent for upgrading)

**Comment by timothylrobb** [comment] 2015-07-19 23:48
You are right.  That one was a bit tricky.  Here is what worked for me:

    var p = document.createElement("p");
    p.setAttribute("style", "width: 300px");
    var slider = document.createElement("input");
    slider.className = "mdl-slider mdl-js-slider";
    slider.setAttribute("type", "range");
    slider.setAttribute("id", "s1");
    slider.setAttribute("min", "0");
    slider.setAttribute("max", "10");
    slider.setAttribute("value", "4");
    slider.setAttribute("step", "2");
    p.appendChild(slider);
    componentHandler.upgradeElement(p.childNodes[0], "MaterialSlider");
    document.appendChild(p);

I appears that if you send upgradeElement() a reference to the correct childNode of the parent element, it will be able to complete the upgrade successfully.  Just sending it the "slider" element failed because "slider" didn't have a parent.

Hope that helps.

**Comment by Garbee** [comment] 2015-07-20 00:07
>I wonder why it does not guess that from the element class name

This has been added and will be in the next patch release. Among other goodies with the component handler.

**Comment by sgomes** [comment] 2016-12-19 13:24
Per the comments above, it should be fixed now. Please let me know if it's not and I'll reopen.

**Closed by sgomes** 2016-12-19 13:24 UTC
Labels: Documentation, v1-bug
