### ISSUE TITLE
Different alignment of the textarea field on firefox

### ISSUE THREAD

**Issue by EmanoelLopes** [google/material-design-lite#4284] opened 2016-04-19 20:54 UTC
I found that the textarea field has different behavior in firefox. 

![mdl-textarea-alignment-issue](https://cloud.githubusercontent.com/assets/4943185/14655108/39449e80-0657-11e6-951c-4594e912ae81.jpg)

Keeping the rows value in one (```<textarea class="mdl-textfield__input" type="text" rows="1" id="sample5"></textarea>```)  in other browsers , including IE9 alignment in a grid works well with other input fields, however, in firefox this alignment is different.
The problem can be seen in this [pen](http://codepen.io/EmanoelLopes/pen/EKLaEx)

**Comment by callahad** [comment] 2016-05-12 14:02
Looks good to me on OS X:

![screen shot 2016-05-12 at 08 58 13](https://cloud.githubusercontent.com/assets/24193/15217200/09fcf8e0-1820-11e6-9cf4-31f10290e018.png) :-/

**Comment by Garbee** [comment] 2016-05-12 16:42
Reproduces on Ubuntu 16.04 on Firefox.

**Comment by callahad** [comment] 2016-05-12 17:11
Huh. Also reproduces on Fedora 23 and Windows 10.

**Comment by Garbee** [comment] 2016-05-12 17:15
Might be an OS-Specific upstream bug in Firefox's engine... I'm not seeing anything in the CSS or box modal that is directly causing this.

**Comment by callahad** [comment] 2016-05-12 17:45
Yeah, especially since the bug manifests on both Linux and Windows, but not OS X or Firefox for Android.

I've filed [Bug 1272430](https://bugzilla.mozilla.org/show_bug.cgi?id=1272430) to look into this upstream.

**Comment by Garbee** [comment] 2016-07-15 18:41
As this seems like an upstream issue, I'm closing this out as there isn't anything we can do about it internally. At least without breaking things for existing sites.

If anyone can figure something out that is non-breaking, `mdl-1.x` is open for PRs.

Thank you.

**Closed by Garbee** 2016-07-15 18:41 UTC
Labels: bug, Textfield
