### ISSUE TITLE
.mdl-card .mdl-tooltip

### ISSUE THREAD

**Issue by markopaju** [google/material-design-lite#4289] opened 2016-04-20 14:27 UTC
as the mdl-card has overflow: hidden; and if theres an tooltip inside the card - it gets cut off. Why does the card have the overflow hidden?

**Comment by Dunexus** [comment] 2016-04-24 15:46
The card has the overflow hidden to crop things like images with the border-radius (2px) of the card.

**Comment by markopaju** [comment] 2016-04-25 08:30
Hey,

there's a class .mdl-card__media what should hold the image if needed.
border top left radius + border to right radius and overflow hidden for the .mdl-card__media div.
all the other holders ( .mdl-card__title, .mdl-card__supporting-text, .mdl-card__actions  ) have the padding so none of the inner elements shouldn't overlap.
if it's the .mdl-card__title and its bg image - border top left radius + border to right radius and it should be fine.

Or am i missing something?

**Comment by Garbee** [comment] 2016-05-11 11:37
This is answered up in #4334. So I'm closing this since the issue is from the same cause. Sorry for not seeing this sooner, things have been crazy the past month or so here.

**Closed by Garbee** 2016-05-11 11:37 UTC
