### ISSUE TITLE
Mobile safari url header not shrinking on scroll dow

### ISSUE THREAD

**Issue by JhoongRoh** [google/material-design-lite#1410] opened 2015-08-17 16:53 UTC
mdl-1.0.2 (have not tested 1.0.3)

I've verified this with my own site and the templates on the official mdllite site. In addition, the bottom safari menu doesn't disappear when scrolling down as well.

Normally, when scrolling down, the url header should minimize:
![image](https://cloud.githubusercontent.com/assets/3443329/9310733/6a9b1c6e-44c6-11e5-9abf-f7581b9cf826.jpg)
![image](https://cloud.githubusercontent.com/assets/3443329/9310734/6abdd06a-44c6-11e5-8108-a8ebe388e6ae.jpg)

**Comment by surma** [comment] 2015-08-18 14:04
Duplicate of #1072. It seems like we won’t be able to fix this before v2 :confused:

**Closed by surma** 2015-08-18 14:04 UTC
