### ISSUE TITLE
Snackbar Container is not center aligned to the browser window

### ISSUE THREAD

**Issue by Rahul-Sagore** [google/material-design-lite#4107] opened 2016-02-12 03:46 UTC
MDL version: 1.1.1
Browser: ALL
Browser version: ALL
Operating system: ALL
Operating system version: ALL

**What steps will reproduce the problem:**
1. Goto Component section of material design light website
2. Click on Snackbar menu
3. Click on "Show" button to display snackbar message.

**What is the expected result?**
The Snackbar container should be center aligned, but it is not. 

**What happens instead of that?**
It display it 50% from left + width of the container. You have used " left: 50% " css property to absolutely position the container to the 50% from the left. But the container will have its own width which will display it more ahead than 50% from left.

**Solution:** I just did css changes in _snackbar.scss file, translating snackbar container -50% from X axis, which will translate it -50% from its center origin to the left,  making it absolutely center align.

**Pull-request :** https://github.com/google/material-design-lite/pull/4106

**Bug ScreenShot:** https://drive.google.com/file/d/0BxtQPnyvB1xpR2FSSDQ0MWkyTlk/view
See the weird position of snackbar message in above screenshot

**Comment by Garbee** [comment] 2016-02-12 12:39
Thank you for providing such a detailed issue report. It is however a duplicate of an existing issue. I am going close this so we can focus the discussion on existing open issue about the topic.

The existing open issue is #4091.

**Closed by Garbee** 2016-02-12 12:39 UTC
