### ISSUE TITLE
Badge on icons

### ISSUE THREAD

**Issue by tleunen** [google/material-design-lite#1225] opened 2015-07-27 22:35 UTC
On the documentation website, we can see a special styles applied on badge when it's on an icon.
```
.mdl-badge.material-icons:after {
    right: -10px;
}
```

Is there any reason why it's not the default behavior? Seems like by default, the badge is too far from the icon so almost every developer using it will need to change its position anyway.

What do you think? Would it make sense to set this as a default style?

**Comment by cliffordp** [comment] 2015-07-28 11:25
I was thinking the same
:+1:

**Comment by surma** [comment] 2015-07-28 11:54
Yes, there definitely should and will be a class for “icons on badges”. Due to our desire to ship we opted to make the demo work. This will be fixed soon™

**Comment by Garbee** [comment] 2015-07-28 14:29
Duplicate of #708.

**Comment by Garbee** [comment] 2015-07-28 14:30
oops, not duplicate of #708. Re-opening for now. I know this is a duplicate though since someone brought up the custom alignment we use in the examples.

**Comment by surma** [comment] 2015-07-28 14:39
No it is a duplicate. Even I forgot about my own issue :D

**Closed by surma** 2015-07-28 14:39 UTC

**Comment by Garbee** [comment] 2015-07-28 14:47
Oh ok, I thought this was about the alignment of icons in badges. Thanks for double-checking!

**Comment by tleunen** [comment] 2015-07-28 14:52
Good catch. Is this for 1.0.2, 1.1 or later?

**Comment by Garbee** [comment] 2015-07-28 15:00
Surely not 1.0.2 since that tag is an urgent fix plus a few other things people keep complaining about. The update would flow into the next minor update since it is a feature addition. However, we have yet to lay out the targets for 1.1 fully so whether it will target that or something else is still unknown.

#708 will be updated with more information as things are figured out.
