### ISSUE TITLE
Layouts lose content scroll position on browser back button

### ISSUE THREAD

**Issue by jimbojetlag** [google/material-design-lite#1378] opened 2015-08-12 15:17 UTC
Here is a quick way of reproducing this:

- Visit this template page http://www.getmdl.io/templates/dashboard/index.html
- Resize your browser height to be small enough to see scroll bar of the main content.
- Browse to a new address.
- Press browser back button.
- The main content of the layout has lost its scroll position, and is reset to be at top.

This could be an annoying, and indeed blocking, problem for long contents with links to visit other pages.

**Comment by surma** [comment] 2015-08-12 15:28
This is a duplicate of #1120.

TL;DR: It will hopefully get fixed with the layout rewrite, which can only happen for v2. Before that, we have to live with that behavior now :confused:

**Closed by surma** 2015-08-12 15:28 UTC
