### ISSUE TITLE
menus-section popup window leaves traces of itself on second click

### ISSUE THREAD

**Issue by strk** [google/material-design-lite#4549] opened 2016-07-12 17:09 UTC
Clicking twice on the 3 vertical dots in the example page leaves traces of the popup window with Firefox 47 on Linux. See screenshot:
![getmdl_bug](https://cloud.githubusercontent.com/assets/289678/16776123/27454fb4-4864-11e6-8d72-14a4d1739a21.png)

**Comment by strk** [comment] 2016-07-12 17:10
Distribution is Ubuntu 14.04, if that matters.

**Comment by anfelor** [comment] 2016-07-19 14:22
This bug also occurs in the elm clone, see: https://github.com/debois/elm-mdl/issues/83

**Comment by anfelor** [comment] 2016-07-20 10:54
Created bug for Mozilla Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=1288059

**Comment by aforemny** [comment] 2016-07-25 19:30
This bug is still present for me in Firefox 47.0.1 on Linux x86_64.

**Comment by HriBB** [comment] 2016-08-10 03:45
I can confirm this. Firefox 47.0 on Ubuntu 15.10. Even if this is a bug in Firefox, we should find a solution for this issue.

**Comment by karazon** [comment] 2016-08-12 13:53
I can also confirm this for Firefox 48.0 on Windows 10 (1607) and Windows 8.1

**Comment by Garbee** [comment] 2016-08-15 16:38
This has worked previously and we haven't changed the functionality of the menu. Therefore this is a regression in Firefox. Please file a bug with them so they can address this internally.

If they WONTFIX a report about the root cause of this, then we can assess at that time whether we should work to address this internally. At which point we can re-open this issue if we will handle patching it in v1.

Thank you.

**Closed by Garbee** 2016-08-15 16:38 UTC
Labels: v1-bug
