### ISSUE TITLE
any plans to add a calendar component?

### ISSUE THREAD

**Issue by sonwh98** [google/material-design-lite#1598] opened 2015-09-14 17:44 UTC

**Comment by Garbee** [comment] 2015-09-14 17:48
Duplicate of #782

**Closed by Garbee** 2015-09-14 17:48 UTC

**Comment by sonwh98** [comment] 2015-09-14 20:09
#782 is for a date picker. I was thinking more along the lines of google calendar

**Comment by Garbee** [comment] 2015-09-14 20:41
Is there a component specified for calendars in material design? To my
knowledge there isn't.
