### ISSUE TITLE
Auto check checkboxes on table

### ISSUE THREAD

**Issue by djalmaaraujo** [google/material-design-lite#1355] opened 2015-08-10 20:55 UTC
I could not find in docs how to populate a table with some checkboxes checked by default. Is that possible? I notice that adding the ```.is-selected``` class changes the background, but not the state of the checkbox for that particularly ```<tr>```.

**Comment by sgomes** [comment] 2015-08-11 09:53
Thanks, @djalmaaraujo, that sounds perfectly doable: when creating the checkboxes, we can initialise them to checked if the `is-selected` class is present on the row.

**Comment by surma** [comment] 2015-08-11 10:02
@sgomes According to SemVer this should be for 1.1

**Comment by sgomes** [comment] 2015-08-11 10:03
Sounds good, marking appropriately.

**Comment by djalmaaraujo** [comment] 2015-08-11 14:31
So its a bug or we are expecting to do this soon?
Em ter, 11 de ago de 2015 às 07:03, Sérgio Gomes <notifications@github.com>
escreveu:

> Sounds good, marking appropriately.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/material-design-lite/issues/1355#issuecomment-129803036>
> .
>
-- 
Djalma Araújo
+55 81 8980.0660
nossomos.cc

**Comment by surma** [comment] 2015-08-11 14:34
@djalmaaraujo It should be added soon-ish. Right now we are focusing on 1.0.3 which is slated to be released this week. After that, we’ll try to make 1.1 happen, which would include a fix for this.

**Comment by djalmaaraujo** [comment] 2015-08-11 14:59
Great, I'll try to contribute too.
Em ter, 11 de ago de 2015 às 11:35, Surma <notifications@github.com>
escreveu:

> @djalmaaraujo <https://github.com/djalmaaraujo> It should be added
> soon-ish. Right now we are focusing on 1.0.3 which is slated to be released
> this week. After that, we’ll try to make 1.1 happen, which would include a
> fix for this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/material-design-lite/issues/1355#issuecomment-129908096>
> .
>
-- 
Djalma Araújo
+55 81 8980.0660
nossomos.cc

**Comment by Garbee** [comment] 2015-08-11 18:43
> So its a bug or we are expecting to do this soon?

On the "bug" note, it is not a bug since the functionality has never been built or considered. Just a missing feature that needs to be added, which is why it goes to the next minor milestone.

**Comment by djalmaaraujo** [comment] 2015-08-11 19:32
@Garbee Thanks for the answer. I think I have an idea on how to submit this feature, do I have to point to master or an specific branch? Also, you guys want to close this issue, it's fine for me.

**Comment by surma** [comment] 2015-08-11 20:07
No, just go ahead and open a PR. We will review it and merge it when the merging window for 1.1 opens. The issue will be closed *after* the merge happened :)

**Comment by djalmaaraujo** [comment] 2015-08-11 21:08
@surma Awesome. Also, I noticed that we don't have specs for the datatable. I'm adding to the actual PR a couple of tests. Maybe we can improve later. Dunno. Let me know if it's good.

https://github.com/google/material-design-lite/pull/1367

**Comment by sgomes** [comment] 2015-08-12 09:15
@djalmaaraujo If by specs you mean an entry in the Material Design specification, there is one: https://www.google.co.uk/design/spec/components/data-tables.html

Bear in mind we only implement a very limited subset of functionality, though.

Thanks for the PR!

**Comment by Garbee** [comment] 2015-08-12 13:58
I think the test can use some updates for consistency with the rest. Take a look at [radio](https://github.com/google/material-design-lite/blob/master/test/unit/radio.js#L23) to see how it sets up a test document fragment. Yes, I know Layout test and tabs iirc handle things with string templates as well, they have yet to be refactored.

Also the `second-row` class shouldn't exist. A quick `nth-child(2)` selector will do just fine and minimize what is in the test template.

**Comment by djalmaaraujo** [comment] 2015-08-12 14:11
@Garbee You think I should create the whole table with javascript methods instead of using a string?

**Comment by Garbee** [comment] 2015-08-12 14:15
Yup, quick function to create and return the fragment of the table. Also, prudent to make the function return a plain table with no extra classes other than necessary. Then within the test method target the row and add the `is-selected` class before upgrading, since that is only applicable to that test and not every test conducted.

**Comment by djalmaaraujo** [comment] 2015-08-12 14:17
@Garbee Got it. Will do some refactoring.

**Comment by Garbee** [comment] 2015-08-13 12:50
With the test update, any specific reason the `el` variable is done? It seems unnecessary since you can upgrade and work against the table variable directly.

**Comment by djalmaaraujo** [comment] 2015-08-13 13:21
@Garbee Should be good now. Thanks for the catch.

**Comment by Garbee** [comment] 2015-12-25 12:44
We've gone full reverse on DataTable's JS. It is now officially [deprecated](https://github.com/google/material-design-lite/wiki/Deprecations#data-tables). Developers should handle anything like this using their own code logic for hard-coded tables.

We are not going to remove this particular addition from 1.1. Just do note that you should be handling tables manually from now on.

**Closed by Garbee** 2015-12-25 12:44 UTC
Labels: confirmed, enhancement

**Comment by djalmaaraujo** [comment] 2015-12-25 16:39
👍

**Comment by codechippy** [comment] 2018-03-18 18:20
I  have pulled together some example code on how to add and remove rows with check boxes here

https://github.com/codechippy/MDL-Dynamic-Tables
