### ISSUE TITLE
clone and npm install

### ISSUE THREAD

**Issue by puchesjr** [google/material-design-lite#1158] opened 2015-07-22 02:15 UTC
I receive an error when attempting to install dependencies with ```npm install && npm install -g gulp```
```
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mocha-phantomjs@3.6.0 wants phantomjs@1.9.1 - 1.9.7-15

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jrodkey/sandbox/material-design-lite/npm-debug.log
```
However, after completing, I can still run gulp and gulp serve with no issue.

**Comment by Garbee** [comment] 2015-07-22 09:56
Duplicate of #1089

**Closed by Garbee** 2015-07-22 09:56 UTC
