### ISSUE TITLE
Ripple button has no ripple effect with Macbook trackpad "Tap to Click" enabled.

### ISSUE THREAD

**Issue by cnyyk** [google/material-design-lite#936] opened 2015-07-10 07:59 UTC
Hi, 
Thanks so much for you guys' great works on this amazing project.

I found that the button with ripple must **click down heavily**( can hear the ticktock ) to see the ripple effect.
If only use finger tap the trackpad, there's no ripple effect.

Maybe this is a bug, or it's the buttons' work way.

**Comment by yuyokk** [comment] 2015-07-10 08:57
I think there is an issue for this already https://github.com/google/material-design-lite/issues/376

**Comment by addyosmani** [comment] 2015-07-10 09:11
Dupe of #376, however I was pretty sure we had fixed this before launch. We absolutely should be supporting tap to trigger the ripples too.

**Closed by addyosmani** 2015-07-10 09:11 UTC
