### ISSUE TITLE
Page does not scroll

### ISSUE THREAD

**Issue by friksa** [google/material-design-lite#2559] opened 2016-01-03 13:22 UTC
Using Safari 9.0.2 on OS X 10.11.2 (latest versions)

1) go to http://www.getmdl.io/styles/index.html
2) scroll down and click on preview icons
3) click the back button in the browser

The page will not scroll up or down now.

**Comment by VamosErik88** [comment] 2016-01-03 14:34
same issue here. hope to get a workaround solution :+1:

**Comment by Garbee** [comment] 2016-01-03 16:14
Works in Chrome here. Sounds like a Safari-specific issue.

Can anyone with access to both Safari and Chrome/Firefox test across browsers to verify?

**Comment by joshas** [comment] 2016-01-03 22:11
@friksa Can you scroll after clicking somewhere on the page (to set focus on page)? How do you scroll - using mouse wheel or keyboard?

**Comment by oddui** [comment] 2016-01-04 03:49
@Garbee Same issue in safari(9.0.1). Good in firefox and chrome.

It seems to happen on any link to a new page and clicking back. The scrolling would work after a window re-size.

**Comment by friksa** [comment] 2016-01-04 09:24
@oddui  yes it happens with any link to another site and clicking back.

@joshas using a MacBook Pro and trackpad with 2 fingers to scroll.  Clicking in the browser to get focus does not help.  Clicking to another tab and back does not help.  Resizing the browser or reloading the page fixes the issue.

**Comment by Garbee** [comment] 2016-01-04 09:37
So, sounds like a Safari-specific issue with how the layout JS operates on the back command. Not sure if there is anything we can do about this.

**Comment by friksa** [comment] 2016-01-04 13:00
That definitely makes this project a non-starter for me unfortunately.  I have not seen this issue with any other similar projects... but was looking for something that works with Angular2.

**Comment by Garbee** [comment] 2016-01-04 13:04
Yea, if this is recreating only in Safari under very specific circumstances, then Safari has a bug somewhere. It should get tracked down with a minimal reproduction case somehow and reported up to them.

Considering how there isn't any way for us to detect this and we are modifying how layout works entirely in V2, closing this out since there is nothing actionable for us. If anyone can track it down to something specific to be looked into, then we can re-open an address the problem.

**Closed by Garbee** 2016-01-04 13:04 UTC

**Comment by friksa** [comment] 2016-01-04 13:12
Should it be documented as a known issue?

**Comment by Garbee** [comment] 2016-01-04 13:21
If more issues come in from other developers about this problem, then we can look into noting the problem with Safari in the docs. Otherwise, it is a niche thing that isn't worth worrying about at this time. People already barely read the docs, so adding a note is likely to get overlooked still.

**Comment by surma** [comment] 2016-01-04 13:21
Also, it has been reported multiple times. There’s a lot of issues in the tracker regarding this. Admittedly, not the most discoverable, but it is there.

**Comment by Garbee** [comment] 2016-01-04 13:30
Looking through every issue result for "Safari" and "back" that is open and closed, I'm only seeing this one for back functionality being problematic. So maybe it was reported in an non-direct way before?

**Comment by surma** [comment] 2016-01-04 13:32
I actually misread the issue. Nvm me. This has not been reported on its own then, but it all falls into the “We screwed up layout” issue.

**Comment by Garbee** [comment] 2016-01-04 13:40
Yea, and I'd rather we not start shoving notices in for everything considering 1.1 is the last minor of the horrid layout JS hell.

With the next site design, we can try to integrate some clear section for pointing out browser issues with what we provide. Right now though, way too easy to get overlooked. So not enough RoI for adding it into the current setup.

**Comment by friksa** [comment] 2016-01-04 14:09
Btw, this happens even inside your site when you click on any link and use the browser back button in Safari.

I download the project and identified the line causing the issue in the material.css.  If I remove height: 100% from .mdl-layout, it works without a problem.

```css
.mdl-layout {
  width: 100%;
  /*height: 100%;*/
```

**Comment by Garbee** [comment] 2016-01-04 14:38
Yup, Layout issues with the way we need to handle things with the current setups magic. We can't go removing the height since things may depend upon it. Who knows what will break.

Being fixed in the next major.

**Comment by oddui** [comment] 2016-01-05 02:34
I was reading https://developers.google.com/web/tools/ today and found it is affected by this issue. It might be good to have a workaround built in. #2583
