### ISSUE TITLE
[Component Request] {Lists - Primary Actions}

### ISSUE THREAD

**Issue by elwinbuisman** [google/material-design-lite#4607] opened 2016-07-28 13:02 UTC
* Description: Not a new component, but addition to an existing component. I'm currently working on a messaging app and I'm need to add click/ touch actions to a list component to open another view. Surrounding a list with <a> pretty much wrecks the whole thing.

* Material Design Spec link: https://material.google.com/components/lists.html#lists-actions

* Use Case(s): As a user i want to click/ touch an item to open a subsequent view.

**Comment by Garbee** [comment] 2016-07-28 15:40
Duplicate of #4473

**Closed by Garbee** 2016-07-28 15:40 UTC
