### ISSUE TITLE
Overrides on tag level is bad!

### ISSUE THREAD

**Issue by Silom** [google/material-design-lite#1293] opened 2015-08-04 13:05 UTC
You override all kinds of tags such as p, h1 - h6 and so on.

This is going to mess up basically every project that tries to implement this package.

Could you please clean that up and only use it in your very class scope?

I mean I would love to use and contribute to this repo, but I simply can't since this gives my team the big overhead we don't need.

For example:
If you try to implement an icon-font, you gonna have big layout issues due all the line-heights.

I know that your style guide tells you how the set line-heights, but this is a lite version of the original concept right?

Lets be honest, no agency really cares about material design, they just use the buttons and inputs and this is what I expect from a package called ”material-design-lite".

I could name more, but my conclusion is that no one ever should override default browser tags and a company like google with all that experience should really know..

Either rename your package to material-design-full-framework or get rid of the overrides.

Thanks for reading, I'm not trying to blame anyone here but I invested shit tons of time breaking your own concept apart to something that the real world can use.

**Comment by addyosmani** [comment] 2015-08-04 13:12
@Silom Thanks for the honest feedback. Half the feedback we've received on MD typography defaults are that users want more defaults prescribed when dropping MDL in their pages whilst the other half want us to disable them unless you're intentionally using opt-in classes. The agency perspective is quite valid here, but so is the hobbyist building a theme that doesn't know what typography config they should be using in an MDL project. 

This area is quite tricky as once you consider components like cards, they have specific requirements around margin and spacing that assume defaults like Roboto are being used at a specific font size. There's likely a sweet-spot we can reach where MDL stays hands off on defaults for body/heading text unless you opt-in, but we otherwise do what is visually correct for components / cards / templates.

**Comment by Silom** [comment] 2015-08-04 13:23
@addyosmani I can understand your dilemma, but doesn't your concept also say "Be humble and don't over-promise".

I think this package is promising something else.

Would it be possible to make two builds? One that is truly light and one that is the whole framework.

**Comment by innerpeace0** [comment] 2015-08-04 13:37
I'm using a [custom style sheet] (https://github.com/angular/material/issues/705) (scroll down to my comment) for those tags using angular-material. Something similar might work with MDL.

**Comment by Silom** [comment] 2015-08-04 13:44
@innerpeace0 this is helping, thanks. I just put all the line-heights to initial.
It still peeves me to override so many things.. all that trafic for nothing..

**Comment by Garbee** [comment] 2015-08-06 18:49
Looks like a duplicate of #1037. This was solved with a build flag for custom builds.

**Comment by sgomes** [comment] 2015-08-07 10:42
@Silom: to elaborate on what @Garbee mentioned, one possible option is to take advantage of the `$target-elements-directly` variable in [`_variables.scss`](https://github.com/google/material-design-lite/blob/master/src/_variables.scss), if you're able to roll and host your own build of MDL. As mentioned, you may have to do some tweaks to make sure alignment is right everywhere, but it should give you a clean slate where it comes to defaults.

**Comment by traviskaufman** [comment] 2016-07-11 21:58
Closing due to lack of activity; v2 will provide a more modular approach to typography (and components in general) where you can pull in exactly what you need and configure it exactly how you want it to behave.

We are still in the very early stages of v2 and are currently working towards an alpha. Our master branch is where all v2 work is happening if you are interested in keeping up with its progress. 😄

**Closed by traviskaufman** 2016-07-11 21:58 UTC
Labels: Typography

**Comment by traviskaufman** [comment] 2016-07-11 22:01
ref. #4542
