### ISSUE TITLE
No dark theme

### ISSUE THREAD

**Issue by tjvg91** [google/material-design-lite#4967] opened 2016-12-09 02:04 UTC
Wish there was a dark version of MDL. Google has specs for it.

**Comment by Garbee** [comment] 2016-12-09 15:03
Dupe of #328. Currently in V2's development area and will be launching with V2 once it is stable (still a good while.) Dark mode functionality won't be added to V1 as it it too big of an update and V1 is now getting only critical fixes from the core team.

Thank you.

**Closed by Garbee** 2016-12-09 15:03 UTC
