### ISSUE TITLE
Buttons do not vertically align with inline form elements in Firefox

### ISSUE THREAD

**Issue by Deilv** [google/material-design-lite#2020] opened 2015-12-17 14:06 UTC
Using a simple mdl-textfield followed by a button inline, they align properly in Chrome and Edge, but not in Firefox. I have setup a [codepen](http://codepen.io/deilv/pen/rxeOOK) to demonstrate the issue.

The included CSS is a fix to the problem which is only applied to the second mdl-cell. I haven't checked if this breaks something else, but if not I'd be more than happy to submit a PR.

**Comment by Deilv** [comment] 2015-12-17 14:12
I'm also including a couple of screenshots of how it looks like (Firefox) and how it should look to match the other browsers.

![original](https://cloud.githubusercontent.com/assets/1664998/11871529/d495b328-a4d8-11e5-8ce7-024ae18458af.png)

![modified](https://cloud.githubusercontent.com/assets/1664998/11871528/d4780120-a4d8-11e5-8198-8bd469f40353.png)

**Comment by Garbee** [comment] 2015-12-17 14:42
Duplicate of #1885 it looks like.

**Closed by Garbee** 2015-12-17 14:42 UTC
