### ISSUE TITLE
Menu positioning (and transform/translate)

### ISSUE THREAD

**Issue by kengruven** [google/material-design-lite#1599] opened 2015-09-14 19:03 UTC
(I don't know if this is technically a bug or not, but it was certainly unexpected behavior that I had to investigate and work around.  I'm sure you all can tell me if my expectations were wrong or not.  Let's call it a "documentation request", for now!)

Component (if any): mdl-menu

What are you trying to do or find out more about?  Positioning (see below)

Where have you looked?  http://www.getmdl.io/components/#menus-section, other Github issues (including closed issues), general web searches, the MDL source code (success!).

Where did you expect to find this information?  On the MDL "Menus" component page, perhaps.

Explanation:

When you make a "mdl-menu", it looks at the for="..." attribute to figure out what the emitting element was, and positions the menu next to that (depending on which positioning class you used, like "mdl-menu--bottom-left", etc).  To compute the menu position (in the default case), it adds offsetTop + offsetHeight [1], to get the bottom edge of the element.  Normally this works fine, and is exactly what you want.

[1]: https://github.com/google/material-design-lite/blob/master/src/menu/menu.js#L179-L217

However, I was using the "top: 50%; transform: translateY(-50%)" idiom (trick?) to vertically center an element (the button that toggles the menu) within its parent element.  Unfortunately, offsetTop+offsetHeight doesn't take into account CSS transformation, so this puts the menu too low on the page (by 50% of the button's height).

In my case, I know how big the element and its parent are, so it's not a big deal to rewrite my CSS to just place it exactly where it needs to be, without using "transform" at all.  Still, this was surprising behavior, to me, and maybe it deserves a note in the docs, that you can't use "transform" with it.

Alternatively, there is a class called "mdl-menu--unaligned" which is described in the source code as "Do not position the menu automatically. Requires the developer to manually specify position."  At first, this looked like something I could use here, but there doesn't seem to be any documentation for this at all.  It's probably not hard to figure out, but if it's not documented, I'm a bit afraid it could go away without warning in a future version.

**Comment by surma** [comment] 2015-09-20 00:00
Hey @kengruven, you found something, that we are aware of and that also affects tooltips. The problem is that both tooltips and the menu use `absolute` or `fixed` positioning. The problem is, that both behave weird when transforms are used and we are still trying to figure out how to work around that for v1.2 or even v2.

I’ll close this issue as it is somewhat working as intended. As I said, we are aware of the issue.

As a side remark: Why aren’t you using `flexbox` to achieve vertical centering?

**Closed by surma** 2015-09-20 00:00 UTC

**Comment by kengruven** [comment] 2015-09-22 16:35
> As a side remark: Why aren’t you using flexbox to achieve vertical centering?

It's a combination of:
 - This is a 'legacy' app that's being converted to MDL from various other layout/styling frameworks
 - Only very recently have we decided to drop IE9 support
 - There's a finite number of hours in the day, and updating working CSS is not a priority right now

**Comment by Sliqric7053** [comment] 2017-03-23 08:47
Hi @surma

Wrt (closed this on Sep 20, 2015), is there any update you can share with us?
The documentation that @kengruven was referring to is still missing.
Kindly shed some light in this regard.
Many thanks

Rich
