### ISSUE TITLE
radio-button and checkmarks render artifacts in Chrome 

### ISSUE THREAD

**Issue by musicformellons** [google/material-design-lite#4394] opened 2016-06-02 09:25 UTC
My radio-buttons are eggshaped and inside dots are not centered well. Checkmarks background is not centered well. See pictures.

When I look at the MDL website radiobuttons in Chrome they are perfect..., which seems odd.

In Chrome:
![screenshot from 2016-06-02 11-15-40](https://cloud.githubusercontent.com/assets/10334123/15740297/9b7e928e-28b4-11e6-83bb-8ab3ce6b9392.png)

![screenshot from 2016-06-02 11-16-15](https://cloud.githubusercontent.com/assets/10334123/15740304/a3c258fe-28b4-11e6-8098-f2942c9e3918.png)

![screenshot from 2016-06-02 11-21-39](https://cloud.githubusercontent.com/assets/10334123/15740313/ad64400c-28b4-11e6-8f6a-d808d0a12007.png)

In Firefox these are ok.

It probably is a Chrome issue. I just discovered it is worse when using 110% zoom; at other zooms results are much better/ flawless. As MDL and Chrome are both google, this should be fixable!?

**Comment by Garbee** [comment] 2016-06-02 11:07
Can you please provide a [codepen](http://codepen.io) where this problem reproduces? It is extremely difficult to understand what is causing these issues without a reproducible sample. Things are working as expected here, so there could be external code messing with your setup causing this.

**Comment by musicformellons** [comment] 2016-06-02 11:29
Here it is:
https://jsbin.com/pigaveg/edit?html,output

When I make a picture of the fiddle from Chrome at 110% it looks like (see especially the second radiobutton; also bullet is not in center of circle:
![screenshot from 2016-06-02 13-27-12](https://cloud.githubusercontent.com/assets/10334123/15743461/e72307d6-28c5-11e6-99b6-bb1e13ff7248.png)

**Comment by Garbee** [comment] 2016-06-02 19:54
Duplicate of #987

**Comment by Garbee** [comment] 2016-06-02 19:54
Thanks for the sample. Made me realize it is Chrome + Zoom + different pixels densities problem. Not much we can do about it internally.

**Closed by Garbee** 2016-06-02 19:54 UTC
Labels: Checkbox, pending-reproducible-sample, Radio
