### ISSUE TITLE
mdl-menu disappears when used in content area with mdl-layout--fixed-drawer mdl-layout--fixed-header

### ISSUE THREAD

**Issue by van-nguyen** [google/material-design-lite#4640] opened 2016-08-06 06:34 UTC
##### What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)

1.1.3
##### What browser(s) is this bug affecting (including version)?

iOS 9 Safari
##### What OS (and version) are you using?

iOS 9
##### What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?

Layout

> > mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header

Content

> > mdl-layout__content
> > 
> > > > mdl-menu mdl-menu--bottom-left mdl-js-menu
##### What is the expected behavior?

Scrolling down does not flicker content area
Clicking on menu does not make everything disappear
##### What is the actual behavior?

Scrolling down flickers content area
Clicking on menu makes everything disappear
##### Any other information you believe would be useful?

Only saw this happen on iOS 9 so far, desktop is fine.
A full demo available at: https://www.priceski.com/

before clicking menu (dropdown)
<img src="https://cloud.githubusercontent.com/assets/1149825/17455183/2ad2795c-5bf3-11e6-888b-47a567054efe.PNG" width="300">

after clicking menu (dropdown)
<img src="https://cloud.githubusercontent.com/assets/1149825/17455184/2f7ad3be-5bf3-11e6-8fb1-0aaa24632e78.PNG" width="300">

**Comment by Garbee** [comment] 2016-08-06 09:42
Assigning to Sergio to triage this one next week. I have a feeling Safari Mobile has a bug here that we need to work around.

**Comment by Deilv** [comment] 2016-08-29 09:29
Has anyone been able to reproduce this? The page you provide works fine on my iOS9/Safari.

**Comment by Garbee** [comment] 2016-08-29 11:39
Looks like the site has changed to use a standard select element over the menu component. Therefore marking as pending a reproducible sample since we don't have the original code to test against.

Please provide a reproduction case via [codepen](http://codepen.io) to be sure it won't change in the future. Thank you.

**Comment by HriBB** [comment] 2016-09-22 13:43
Just hit this in React MDL. Very annoying.

Reproducible example with React MDL https://tleunen.github.io/react-mdl/components/menu/ and with Vanilla MDL Vanilla MDL https://codepen.io/anon/pen/ALOQVj

Steps to reproduce:
1. scroll down
2. open menu
3. close menu

On Chrome, page jumps up and down. On Safari, menu position is not properly updated if you open menu, close it, scroll up/down, then open menu again.

In general, menu component does not work very well.

**Comment by sgomes** [comment] 2016-09-22 13:54
I can't reproduce the issue in Chrome, I'm afraid. Any chance you could share a quick video? I might be doing something wrong.

In Safari, I do see a jump from an incorrect position to a correct one immediately after the menu opens.

**Comment by HriBB** [comment] 2016-09-22 14:45
https://drive.google.com/file/d/0ByT35Ygmx6eFbFc4dUxvSWEwWWc/view

In both cases I first open the menu, close it, then open the menu, scroll to top and close it.

I am using Chrome Version 53.0.2785.116 (64-bit) on OSX El Capitan. I tried disabling all my extensions just in case, but the problem still exists.

**Comment by vegansk** [comment] 2016-09-29 01:58
Reproduced with the same results on Chrome 53.0.2785.116 (64-bit), Ubuntu 14.04.

**Comment by Deilv** [comment] 2016-09-29 19:17
I confirm as well on Chrome 53.0.2785.116 / Windows 10 Pro. The issue appears only after you scroll down a bit. Will investigate...

**Comment by kpost** [comment] 2016-10-05 09:01
+1 I'm having the same issue in my project. Can't figure out what exactly happens too, no css seems to change, but the page jumps quite rigorously. Don't have the issue in Firefox btw. Very weird.

**Comment by petrov-ro** [comment] 2016-10-06 07:11
Same problem on chrome 53.0.2785.143 m. It's ok on mobile chrome 52.0.2743.98 android 5.1.0

**Comment by Bilchenko** [comment] 2016-10-10 10:32
Hi, I have problems with mdl-menu and mdl-grid since update win desktop Chrome to 53.0.2785.116. Menu appears in different place, scroll has overflow artifacts. 
test page has:
grid
menu
grid

https://codepen.io/AlexeiBilchenko/pen/vXRVEy

**Comment by sgomes** [comment] 2016-10-10 11:26
Thanks, everyone, this is proving a tricky bug to track down :(
At the moment, and given that it only happens for certain people, it's seeming like a regression in Chrome. There might be a workaround, but I'm not sure how to even start looking for it.

Could someone who is being affected please try [Chrome Canary](https://www.google.com/chrome/browser/canary.html) to see if the bug is still present? Thank you!

**Comment by kpost** [comment] 2016-10-10 12:26
I can confirm it works on Chrome Canary. I suspect it's a one time chrome-related (not webkit, it works in safari) bug?

**Comment by sgomes** [comment] 2016-12-13 13:38
Given the silence on this thread, I'm going to assume the bug is gone. Please let me know if it's not, and I'll reopen!

**Closed by sgomes** 2016-12-13 13:38 UTC
Labels: Menu, pending-reproducible-sample, v1-bug
