### ISSUE TITLE
Add Alert Dialogs

### ISSUE THREAD

**Issue by smcardle** [google/material-design-lite#1604] opened 2015-09-15 19:49 UTC
Part of the Dialogs spec for material design outlines their use for alerts
https://www.google.com/design/spec/components/dialogs.html#dialogs-behavior

These are simple dialogs that contain a small amount of text and actions such as "OK" & "Cancel"

The default browser alert does not look like a material design component and supporting process flow with it is difficult at best.

The type of use case we have is where a user selects to remove some content, such as a loaded image etc. Rather than just remove the image we would like to prompt the user by asking them if they are sure before removing the affected elements etc.

In the mean time... Does anybody have any suggestions on a simple solution to address this use case without reverting to third party libraries.

Regards

**Comment by Garbee** [comment] 2015-09-15 19:52
Duplicate of #781

**Closed by Garbee** 2015-09-15 19:52 UTC

**Comment by smcardle** [comment] 2015-09-15 20:15
opps...

Missed that one :)
