### ISSUE TITLE
Infected with Trojan:Win32/Spursint.A virus?

### ISSUE THREAD

**Issue by tropicfruit** [google/material-design-lite#1812] opened 2015-10-26 15:24 UTC
While downloading from http://www.getmdl.io/ my anti virus (MSSE) tells that the zip is infected with Trojan:Win32/Spursint.A and put int in quarantine.

Anyone else experiencing this issue? Maybe a false positive?

**Comment by Garbee** [comment] 2015-10-26 15:26
Duplicate of #1754.

Surely false positive. Users of MSSE need to report it to MS so they can figure out why their software is calling it out and get it fixed.

**Closed by Garbee** 2015-10-26 15:26 UTC

**Comment by tropicfruit** [comment] 2015-10-26 15:28
Thx for the quick reply.
