### ISSUE TITLE
Datatable row borders have overlap

### ISSUE THREAD

**Issue by janpieterz** [google/material-design-lite#1858] opened 2015-11-07 15:53 UTC
As seen in the image, above every blue line the crossing of the row borders with the table border results in a double transparent border, making a tiny darker square visible.

![image](https://cloud.githubusercontent.com/assets/383634/11015896/00b67560-8570-11e5-9091-39dc6883341b.png)

**Comment by Garbee** [comment] 2015-11-07 19:56
Can you please provide a codepen that displays the issue?

**Comment by janpieterz** [comment] 2015-11-07 20:09
In my Chrome it does this on getmdl.com itself, the screenshot is literally taken from the website.

**Comment by Garbee** [comment] 2015-11-07 20:12
Ah yes, very miniscule but it is there. Not really sure if there is anything that can be done here about it though. Any suggestions?

**Comment by janpieterz** [comment] 2015-11-08 09:48
I couldn't find any concrete fix since it is the usage of rgba that makes it behave this way.
I did get a fix working by setting the gray scale hard to a value (#E1E1E1), which obviously removes the transparency. I did look in the spec and couldn't find a specification of transparent borders though, so this might be a valid solution

Some reference material:
http://stackoverflow.com/questions/5722972/border-color-rgba-borders-overlap-at-the-corners-giving-a-darker-color-than-i

**Comment by Garbee** [comment] 2015-11-08 12:38
Looks like a browser rendering bug to me. I'm not seeing the same boxes in MS Edge or Firefox. At least not as easily as I see them in Chrome (although Edge seems to have an alignment issue with our header checkbox.)

Edge:
![data-table](https://cloud.githubusercontent.com/assets/868301/11020365/a5163d5e-85eb-11e5-80d1-deb5d1576c20.png)

Firefox:
![data-table-ff](https://cloud.githubusercontent.com/assets/868301/11020366/a91c7c1a-85eb-11e5-8c4f-aae679c73381.png)

**Comment by janpieterz** [comment] 2015-11-08 13:00
@Garbee Correct me if I'm wrong, but it looks like both of your screenshots actually do have the boxes. My Edge does actually show it as well. The difference is they don't have it on the top row, only on the three 'middle' ones.

**Comment by Garbee** [comment] 2015-11-08 13:20
If it is there it isn't nearly as prominent to me. Maybe I just can't see in in these two. Either way, assigning to @sgomes to take a look since he did the initial implementation. If we can change to a no-opacity color then fine, otherwise I don't see where this is noticeable enough to warrant action considering how minuscule the problem actually is.

**Comment by sgomes** [comment] 2015-11-10 12:15
Sorry, this is a limitation of trying to implement the spec in HTML :-/

As mentioned, this happens because the borders are semitransparent, and thus produce a darker colour on the one pixel where they overlap in each intersection. One potential solution would be to use a linear gradient on a border image, but that would have some issues of its own:
- It would be a performance hit, particularly on large tables
- It would be an awkward implementation, relying on something like `calc(100% - 2px)`, which would further limit our IE9 compatibility
- It would likely still produce problems in some browsers, since linear gradients aren't pixel-perfect everywhere

Since the issue is pretty small and I can't come up with a good fix, I'll close this bug for now. If anyone does comes up with a good implementation that solves the issue, though, do let us know!

**Closed by sgomes** 2015-11-10 12:15 UTC
Labels: Data Table, research
